# STW Daily Discord bot Copyright 2022 by the STW Daily team.
# Please do not skid our hard work.
# https://github.com/dippyshere/stw-daily

# This document contains item names and desrciptions.

[en]
heroxp_name			= "Hero XP"
heroxp_desc			= "Used to level heroes and defenders. Can be found in llamas and by retiring heroes or defenders."
voucherbasic_name	= "Mini Reward Llama"
voucherbasic_desc	= "Claim your free reward llama in the Loot tab."
heror_name			= "Rare Hero"
heror_desc			= "One random hero."
herovr_name			= "Epic Hero"
herosr_name			= "Legendary Hero"
managerr_name		= "Epic Lead Survivor"
managerr_desc		= "One random lead survivor."
workersr_name		= "Legendary Survivor"
workersr_name		= "One random survivor."
meleer_name			= "Rare Melee Weapon Schematic"
meleer_desc			= "One random melee weapon schematic."
trapr_name			= "Rare Trap Schematic"
trapr_desc			= "One random trap schematic."
rangedr_name		= "Rare Ranged Weapon Schematic"
rangedr_desc		= "One random ranged weapon schematic."
xpboost_name		= "XP Boost"
xpboost_desc		= "Activate an XP Boost to gain Account XP boost points. Boost points earn [XpBoost.Self.Value] more experience for yourself, as well as give a [XpBoost.Team.Value] bonus to all other players on your team! If you are a Founder, you automatically grant a 5% bonus to all your team mates. The more players that use XP Boosts, the bigger the bonus for everyone!"
teamxpboost_name	= "Teammate XP Boost"
teamxpboost_desc	= "Activate a Teammate XP Boost to give a teammate Account XP boost points. Boost points earn [XpBoost.Self.Value] more experience for a teammate, as well as give a [XpBoost.Team.Value] bonus to you and the other players on your team!  The more players that use XP Boosts, the bigger the bonus for everyone!"
mtxswap_name		= "V-Bucks Voucher"
mtxswap_desc		= "Turns into X-Ray Tickets for everyone, and also V-Bucks if you have a Founders account."
gold_name			= "Gold"
gold_desc			= "Special currency earned by completing missions and opening mini llamas. Can be traded for items in the Event Store."
reagent01_name		= "Pure Drop of Rain"
reagent01_desc		= "Resource used to evolve all types of items."
reagent02_name		= "Lightning in a Bottle"
reagent02_desc		= "Resource used to evolve all types of items. Found primarily in Plankerton."
reagent03_name		= "Eye of the Storm"
reagent03_desc		= "Resource used to evolve all types of items. Found primarily in Canny Valley."
reagent04_name		= "Storm Shard"
reagent04_desc		= "Resource used to evolve all types of items. Found primarily in Twine Peaks."
firecracker_name	= "Freedom's Herald"
firecracker_desc	= "Pistol: Special. Launches firecrackers that bounce off walls, and will knockback and damage enemies in a small radius when they explode."