"""
STW Daily Discord bot Copyright 2023 by the STW Daily team.
Please do not skid our hard work.
https://github.com/dippyshere/stw-daily

This file is the cog for the auth and kill command. handles auth sessions.
"""

import math

import discord
import discord.ext.commands as ext
from discord import Option
from discord.commands import (  # Importing the decorator that makes slash commands.
    slash_command,
)

import stwutil as stw


class Auth(ext.Cog):
    """
    Cog for the auth command
    """

    def __init__(self, client):
        self.client = client
        self.emojis = client.config["emojis"]

    async def auth_command(self, ctx, token='', repeated=False):
        """
        The main function of the auth command

        Args:
            ctx (discord.ext.commands.Context): The context of the command
            token: The token to authenticate with
            repeated: Whether or not the command has been repeated

        Returns:
            None
        """

        desired_lang = await stw.I18n.get_desired_lang(self.client, ctx)

        auth_info = await stw.get_or_create_auth_session(self.client, ctx, "auth", token, True, True,
                                                         desired_lang=desired_lang)
        if not auth_info[0]:
            return

        # i am braindead
        ainfo3 = ""
        try:
            ainfo3 = auth_info[3]
        except:
            pass

        try:
            user_document = await stw.get_user_document(ctx, self.client, ctx.author.id, desired_lang=desired_lang)
            currently_selected_profile_id = user_document["global"]["selected_profile"]
            keycard = user_document["profiles"][str(currently_selected_profile_id)]["settings"]["keycard"]
        except:
            keycard = "keycard"

        # what is this black magic???????? I totally forgot what any of this is
        if auth_info[0] is not None and ainfo3 != "logged_in_processing" and auth_info[2] != []:
            await stw.slash_edit_original(ctx, auth_info[0], auth_info[2])
        elif await stw.validate_existing_session(self.client, auth_info[1]["token"]):
            embed = await stw.create_error_embed(self.client, ctx,
                                                 stw.I18n.get('auth.embed.currentauth.title', desired_lang),
                                                 f"{stw.I18n.get('auth.embed.currentauth.description1', desired_lang)}\n"
                                                 f"```{auth_info[1]['account_name']}```\n"
                                                 f"{stw.I18n.get('auth.embed.currentauth.description2', desired_lang, self.emojis['stopwatch_anim'], '<t:{0}:R>'.format(math.floor(auth_info[1]['expiry'])))}",
                                                 prompt_newcode=True, title_emoji="whitekey", thumbnail=keycard,
                                                 colour="auth_white", auth_push_strong=False,
                                                 desired_lang=desired_lang)
            await stw.slash_edit_original(ctx, auth_info[0], embed)
        else:
            embed = await stw.create_error_embed(self.client, ctx,
                                                 description=f"{stw.I18n.get('auth.embed.currentauth.expired.description1', desired_lang)}\n"
                                                             f"```{auth_info[1]['account_name']}```\n"
                                                             f"{stw.I18n.get('auth.embed.currentauth.expired.description2', desired_lang)}\n"
                                                             f"⦾ {stw.I18n.get('auth.embed.currentauth.expired.description3', desired_lang)}\n"
                                                             f"⦾ {stw.I18n.get('auth.embed.currentauth.expired.description4', desired_lang)}",
                                                 desired_lang=desired_lang,
                                                 promptauth_key="util.error.embed.promptauth.strong1.auth")
            await stw.slash_edit_original(ctx, auth_info[0], embed)

    async def kill_command(self, ctx):
        """
        The main function of the kill command

        Args:
            ctx (discord.ext.commands.Context): The context of the command
        """
        desired_lang = await stw.I18n.get_desired_lang(self.client, ctx)
        white = self.client.colours["auth_white"]
        try:
            user_document = await stw.get_user_document(ctx, self.client, ctx.author.id, desired_lang=desired_lang)
            currently_selected_profile_id = user_document["global"]["selected_profile"]
            keycard = user_document["profiles"][str(currently_selected_profile_id)]["settings"]["keycard"]
        except:
            keycard = "keycard"
        if await stw.manslaughter_session(self.client, ctx.author.id, "override"):
            embed = discord.Embed(
                title=await stw.add_emoji_title(self.client, stw.I18n.get('auth.kill.embed.title', desired_lang),
                                                "whitekey"),
                description=f"```{stw.I18n.get('auth.kill.embed.description', desired_lang)}```\n", colour=white)
        else:
            embed = discord.Embed(
                title=await stw.add_emoji_title(self.client,
                                                stw.I18n.get('auth.kill.missing.embed.title', desired_lang),
                                                "whitekey"),
                description=f"```{stw.I18n.get('auth.kill.missing.embed.description', desired_lang)}```\n",
                colour=white)

        embed = await stw.set_thumbnail(self.client, embed, keycard)
        embed = await stw.add_requested_footer(ctx, embed, desired_lang)
        await stw.slash_send_embed(ctx, self.client, embed)

    @ext.command(name='auth',
                 aliases=['login', 'authenticate', 'uth', 'ath', 'auh', 'aut', 'aauth', 'auuth', 'autth', 'authh',
                          'uath', 'atuh', 'auht', 'quth', 'wuth', 'suth', 'xuth', 'zuth', 'ayth', 'a7th', 'a8th',
                          'aith', 'akth', 'ajth', 'ahth', 'aurh', 'au5h', 'au6h', 'auyh', 'auhh', 'augh', 'aufh',
                          'autn', 'aquth', 'awuth', 'asuth', 'axuth', 'azuth', 'ayuth', 'a7uth', 'au7th', 'a8uth',
                          'au8th', 'aiuth', 'auith', 'akuth', 'aukth', 'ajuth', 'aujth', 'ahuth', 'auhth', 'aurth',
                          'autrh', 'au5th', 'aut5h', 'au6th', 'aut6h', 'auyth', 'autyh', 'augth', 'aufth', 'autfh',
                          'autgh', 'authg', 'authy', 'autuh', 'authu', 'autjh', 'authj', 'autnh', 'authn', 'autbh',
                          'authb', 'lgoin', 'authcode', 'gettoken', 'a', '/auth', 'code', 'ode', 'cde', 'coe', 'cod',
                          'ccode', 'coode', 'codde', 'ocde', 'cdoe', 'coed', 'xode', 'dode', 'fode', 'vode', 'cide',
                          'c9de', 'c0de', 'cpde', 'clde', 'ckde', 'cose', 'coee', 'core', 'cofe', 'coce', 'coxe',
                          'codw', 'cod3', 'cod4', 'codr', 'codf', 'codd', 'cods', 'xcode', 'cxode', 'dcode', 'cdode',
                          'fcode', 'cfode', 'vcode', 'cvode', 'ciode', 'coide', 'c9ode', 'co9de', 'c0ode', 'co0de',
                          'cpode', 'copde', 'clode', 'colde', 'ckode', 'cokde', 'cosde', 'codse', 'coede', 'codee',
                          'corde', 'codre', 'cofde', 'codfe', 'cocde', 'codce', 'coxde', 'codxe', 'codwe', 'codew',
                          'cod3e', 'code3', 'cod4e', 'code4', 'coder', 'codef', 'coded', 'codes', 'ogin', 'lgin',
                          'loin', 'logn', 'logi', 'llogin', 'loogin', 'loggin', 'logiin', 'loginn', 'olgin', 'loign',
                          'logni', 'kogin', 'oogin', 'pogin', 'ligin', 'l9gin', 'l0gin', 'lpgin', 'llgin', 'lkgin',
                          'lofin', 'lotin', 'loyin', 'lohin', 'lobin', 'lovin', 'logun', 'log8n', 'log9n', 'logon',
                          'logln', 'logkn', 'logjn', 'logib', 'logih', 'logij', 'logim', 'klogin', 'ologin', 'plogin',
                          'lpogin', 'liogin', 'loigin', 'l9ogin', 'lo9gin', 'l0ogin', 'lo0gin', 'lopgin', 'lolgin',
                          'lkogin', 'lokgin', 'lofgin', 'logfin', 'lotgin', 'logtin', 'loygin', 'logyin', 'lohgin',
                          'loghin', 'lobgin', 'logbin', 'lovgin', 'logvin', 'loguin', 'logiun', 'log8in', 'logi8n',
                          'log9in', 'logi9n', 'logoin', 'logion', 'loglin', 'logiln', 'logkin', 'logikn', 'logjin',
                          'logijn', 'logibn', 'loginb', 'logihn', 'loginh', 'loginj', 'logimn', 'loginm', 'getcode',
                          'getauth', 'getlogin', 'exchange', '/login', '/code', '/a', '/authcode', '/gettoken',
                          '.login', '.code', '.a', '.authcode', '.gettoken', 'المصادقة', 'প্রমাণ', 'autenticación',
                          'اعتبار', 'tod', 'પ્રમાણીકરણ', 'אישור', 'प्रमाणन', '認証', 'प्रमाणीकरण', 'ਪ੍ਰਮਾਣਿਕਤਾ', 'аутх',
                          'mwandishi', 'அங்கீகாரம்', 'รับรองความถูกต้อง', 'yetki', 'تصنیف', '授权', '授權', 'token',
                          'cuth', 'aubh', 'muth', 'acth', 'uuth', 'agth', 'huth', 'autqh', 'aoth', 'abuth', 'aueth',
                          'euth', 'puth', 'aunh', 'aujh', 'aumh', 'aruth', 'auph', 'auqh', 'kuth', 'austh', 'awth',
                          'auah', 'auoth', 'juth', 'aupth', 'acuth', 'aueh', 'arth', 'futh', 'authi', 'atuth', 'guth',
                          'aouth', 'autsh', 'aputh', 'aqth', 'authl', 'auoh', 'auch', 'auteh', 'authe', 'iuth',
                          'autht', 'aubth', 'autdh', 'apth', 'authc', 'anth', 'vuth', 'aunth', 'auuh', 'yuth', 'atth',
                          'aumth', 'autkh', 'aulh', 'authx', 'audth', 'autch', 'authw', 'ruth', 'auqth', 'authr',
                          'axth', 'aeth', 'anuth', 'autlh', 'autxh', 'authp', 'auwh', 'authv', 'auzth', 'autwh',
                          'auath', 'autvh', 'afuth', 'autph', 'aucth', 'auxh', 'aath', 'aluth', 'auvh', 'auvth', 'alth',
                          'luth', 'adth', 'auih', 'afth', 'amuth', 'outh', 'avth', 'audh', 'authd', 'autzh', 'autha',
                          'amth', 'abth', 'authk', 'authq', 'buth', 'authz', 'avuth', 'azth', 'authf', 'auzh', 'autmh',
                          'aeuth', 'auxth', 'auths', 'aguth', 'autah', 'nuth', 'aukh', 'aush', 'aulth', 'authm',
                          'autih', 'asth', 'auwth', 'a6th', 'a^th', 'a&th', 'a*th', 'au4h', 'au$h', 'au%h', 'au^h',
                          'dlogin', 'logiy', 'logix', 'lopin', 'wogin', 'loxgin', 'logini', 'logian', 'logir', 'logino',
                          'flogin', 'eogin', 'vogin', 'loginu', 'lyogin', 'logcn', 'logins', 'lorin', 'logan', 'leogin',
                          'lbogin', 'lolin', 'logina', 'lsgin', 'slogin', 'logyn', 'loxin', 'loegin', 'logiqn', 'mogin',
                          'loginl', 'logig', 'cogin', 'zogin', 'lagin', 'lhogin', 'logen', 'logmn', 'logie', 'blogin',
                          'rogin', 'lzogin', 'gogin', 'loginx', 'logxin', 'legin', 'locgin', 'uogin', 'logbn', 'nlogin',
                          'logicn', 'logind', 'ldgin', 'longin', 'lngin', 'lowgin', 'loghn', 'logipn', 'aogin',
                          'logirn', 'lomin', 'lmgin', 'logine', 'lojin', 'lqogin', 'logif', 'logiv', 'logil', 'logzin',
                          'logizn', 'logdn', 'logign', 'logisn', 'logixn', 'logcin', 'lcogin', 'lognin', 'lzgin',
                          'lwogin', 'loging', 'lvgin', 'logifn', 'lvogin', 'logfn', 'lqgin', 'bogin', 'logvn', 'lggin',
                          'losgin', 'lodin', 'yogin', 'logia', 'lorgin', 'logid', 'lognn', 'loein', 'loginq', 'lxgin',
                          'lfgin', 'jlogin', 'iogin', 'togin', 'lhgin', 'logivn', 'ljgin', 'loginp', 'lugin', 'logtn',
                          'xogin', 'loginc', 'loginv', 'loggn', 'hogin', 'logwin', 'rlogin', 'logiz', 'mlogin',
                          'ltogin', 'ldogin', 'clogin', 'loginz', 'laogin', 'logrin', 'lodgin', 'ylogin', 'logint',
                          'loginw', 'logip', 'logiyn', 'glogin', 'lozgin', 'locin', 'logiq', 'ljogin', 'lxogin',
                          'hlogin', 'logzn', 'logqin', 'lrogin', 'ltgin', 'logrn', 'logis', 'vlogin', 'lomgin',
                          'lmogin', 'lowin', 'ulogin', 'loginf', 'louin', 'logiw', 'logwn', 'logiwn', 'lbgin', 'qlogin',
                          'loqgin', 'loain', 'loagin', 'elogin', 'lnogin', 'logien', 'nogin', 'ilogin', 'losin',
                          'lsogin', 'alogin', 'xlogin', 'lougin', 'logii', 'logic', 'loginr', 'loqin', 'jogin', 'lozin',
                          'loiin', 'logik', 'logsn', 'fogin', 'logsin', 'dogin', 'logain', 'logmin', 'logitn', 'wlogin',
                          'logxn', 'logpn', 'logiu', 'logqn', 'lrgin', 'lwgin', 'lygin', 'tlogin', 'lojgin', 'lgogin',
                          'logink', 'logein', 'lfogin', 'looin', 'sogin', 'logidn', 'lcgin', 'lonin', 'zlogin', 'logit',
                          'lokin', 'luogin', 'qogin', 'logio', 'logdin', 'logpin', 'loginy', ';ogin', '/ogin', '.ogin',
                          ',ogin', '?ogin', '>ogin', '<ogin', 'l8gin', 'l;gin', 'l*gin', 'l(gin', 'l)gin', 'log7n',
                          'log&n', 'log*n', 'log(n', 'logi,', 'logi<', 'cjde', 'codoe', 'kode', 'jode', 'mode', 'codte',
                          'qode', 'czde', 'tcode', 'codea', 'cgde', 'lode', 'cuode', 'chde', 'coade', 'coae', 'coie',
                          'codey', 'cgode', 'coge', 'cody', 'codc', 'coqde', 'codbe', 'codo', 'cohe', 'pode', 'mcode',
                          'codeb', 'cone', 'codge', 'cyde', 'codue', 'crode', 'cdde', 'codhe', 'cede', 'codeq', 'chode',
                          'codve', 'codq', 'codec', 'cvde', 'aode', 'codz', 'codme', 'codg', 'codl', 'lcode', 'codel',
                          'codep', 'cobe', 'coden', 'cojde', 'iode', 'codj', 'cohde', 'cotde', 'ccde', 'coye', 'come',
                          'kcode', 'jcode', 'acode', 'sode', 'yode', 'cfde', 'codek', 'coze', 'ocode', 'codex', 'cooe',
                          'oode', 'cote', 'cbde', 'cozde', 'rode', 'tode', 'cowe', 'cqde', 'cxde', 'codx', 'cjode',
                          'cwode', 'codet', 'codze', 'codem', 'czode', 'zcode', 'uode', 'ctde', 'codev', 'codb',
                          'icode', 'csde', 'cwde', 'cole', 'codke', 'csode', 'codeo', 'hode', 'codk', 'coude', 'codn',
                          'ctode', 'rcode', 'pcode', 'codez', 'codt', 'codye', 'codne', 'codi', 'codej', 'cyode',
                          'codqe', 'codp', 'caode', 'cope', 'codeh', 'ncode', 'coje', 'codeg', 'covde', 'bcode',
                          'conde', 'cobde', 'cogde', 'gode', 'bode', 'cove', 'ycode', 'codm', 'hcode', 'coqe', 'coke',
                          'ceode', 'scode', 'coda', 'codje', 'eode', 'cowde', 'cade', 'ecode', 'wcode', 'node', 'coue',
                          'codv', 'ucode', 'zode', 'codu', 'comde', 'codh', 'codle', 'cnde', 'cmode', 'cude', 'wode',
                          'crde', 'codei', 'codeu', 'codae', 'cbode', 'cnode', 'cqode', 'codie', 'coyde', 'gcode',
                          'qcode', 'codpe', 'c8de', 'c;de', 'c*de', 'c(de', 'c)de', 'cod2', 'cod$', 'cod#', 'cod@',
                          'authenticute', 'authnticate', 'amthenticate', 'authhenticate', 'authenticaie',
                          'authenticatxe', 'authenticaet', 'aduthenticate', 'autehnticate', 'auhenticate',
                          'uathenticate', 'authentictae', 'anthenticate', 'authenticfate', 'authgenticate',
                          'authentibate', 'authentiate', 'authetnicate', 'authenticwate', 'authenticdte',
                          'rauthenticate', 'yuthenticate', 'authentciate', 'authenticae', 'authentiqate',
                          'authenticater', 'authentcate', 'autzhenticate', 'authennticate', 'uthenticate',
                          'autventicate', 'autheenticate', 'buthenticate', 'authentzicate', 'authenticavte',
                          'atuhenticate', 'authenticatj', 'authemticate', 'aothenticate', 'augthenticate',
                          'futhenticate', 'authentihcate', 'authenitcate', 'authienticate', 'authenticace',
                          'aupthenticate', 'authenticste', 'autheznticate', 'authenticat', 'autheticate',
                          'autgenticate', 'authenpicate', 'authensicate', 'autyenticate', 'authentimcate',
                          'authentiacte', 'akthenticate', 'autheneticate', 'auihenticate', 'autrenticate',
                          'xuthenticate', 'authenuticate', 'sauthenticate', 'authenticapte', 'authentocate',
                          'auhtenticate', 'athenticate', 'outhenticate', 'auuhenticate', 'auvhenticate',
                          'authenticated', 'authentisate', 'authenticatle', 'autenticate', 'authenticatqe',
                          'authenicate', 'aubhenticate', 'authenticte', 'authehticate', 'authenticatt', 'authsenticate',
                          'authbnticate', 'authxenticate', 'authneticate', 'authentimate', 'authentikcate',
                          'authenticatex', 'authenrticate', 'ahuthenticate', 'acthenticate', 'huthenticate',
                          'authengicate', 'authenticaute', 'authtenticate', 'authentfcate', 'autlhenticate',
                          'jauthenticate', 'authebticate', 'authentncate', 'kauthenticate', 'abthenticate',
                          'authenticatke', 'authyenticate', 'authenticahte', 'authentkcate', 'authenticaze',
                          'authenticrate', 'aujthenticate', 'authenticatz', 'authenticatel', 'aruthenticate',
                          'autjhenticate', 'authentigate', 'authenticatl', 'wauthenticate', 'authentihate',
                          'authenticvte', 'authenoicate', 'authentigcate', 'authenpticate', 'ruthenticate',
                          'authentnicate', 'authenticaue', 'authsnticate', 'aithenticate', 'eauthenticate',
                          'autchenticate', 'azuthenticate', 'aumhenticate', 'authentvcate', 'authenticaten',
                          'authqnticate', 'authenticabe', 'authenticatte', 'authenticacte', 'authgnticate',
                          'authenticatet', 'authenticqate', 'authanticate', 'authentmicate', 'autheqticate',
                          'authenticaee', 'authejnticate', 'authencticate', 'authenticatn', 'authexticate',
                          'amuthenticate', 'authentiycate', 'authenjicate', 'authendticate', 'austhenticate',
                          'authventicate', 'authenjticate', 'authepnticate', 'nauthenticate', 'authenticyate',
                          'authenttcate', 'authentictte', 'autheiticate', 'authentiocate', 'authenticats',
                          'authednticate', 'authentiscate', 'autheneicate', 'authenficate', 'authjnticate',
                          'suthenticate', 'authentiqcate', 'authenlicate', 'authdnticate', 'authknticate',
                          'autpenticate', 'authenticateg', 'autherticate', 'authenticcate', 'autbenticate',
                          'authenthcate', 'authendicate', 'authenticatd', 'authentichte', 'authenzticate',
                          'authenticatg', 'quthenticate', 'authenticaty', 'aiuthenticate', 'authenticgate',
                          'authenticnte', 'authenticatye', 'authbenticate', 'authenticatr', 'authenticxate',
                          'authentioate', 'authecnticate', 'authenticalte', 'authentidate', 'afthenticate',
                          'agthenticate', 'authejticate', 'auhhenticate', 'authrnticate', 'autheoticate',
                          'authentilate', 'aumthenticate', 'ajuthenticate', 'aauthenticate', 'authenticale',
                          'authentitcate', 'authenticatej', 'authenticatp', 'authenxicate', 'authenticatec',
                          'auythenticate', 'authenticatf', 'authentmcate', 'qauthenticate', 'authentzcate',
                          'authenticateq', 'authentivate', 'authenticath', 'authenticatev', 'authenticame',
                          'authentscate', 'authmenticate', 'autmenticate', 'authenticare', 'authqenticate',
                          'aufhenticate', 'autheeticate', 'authentizate', 'authentibcate', 'authenticsate',
                          'authenticatk', 'authenticatpe', 'authenhicate', 'authenticata', 'authentycate',
                          'oauthenticate', 'juthenticate', 'authenticlate', 'awuthenticate', 'authentaicate',
                          'autheyticate', 'authcenticate', 'authenticadte', 'autihenticate', 'authenthicate',
                          'authwenticate', 'authenticgte', 'authenticyte', 'authentiacate', 'asthenticate',
                          'authefticate', 'atuthenticate', 'authenticaste', 'autaenticate', 'lauthenticate',
                          'authentpicate', 'authesticate', 'aouthenticate', 'auqhenticate', 'authenticagte',
                          'authentucate', 'authentwicate', 'kuthenticate', 'authenticaye', 'gauthenticate',
                          'authenticxte', 'authenticane', 'authenticawe', 'authenyicate', 'authentictate',
                          'authenticatep', 'zauthenticate', 'yauthenticate', 'authentijcate', 'authnnticate',
                          'authensticate', 'authenticazte', 'authenticatge', 'autcenticate', 'authenqicate',
                          'aurhenticate', 'authentieate', 'authentixate', 'authengticate', 'aeuthenticate',
                          'authenticatne', 'authentrcate', 'authenticamte', 'autheniicate', 'authenticati',
                          'authenlticate', 'authenticaate', 'authenticote', 'authenticatae', 'authentjcate',
                          'authenticatce', 'authenticlte', 'authenkticate', 'authenticatje', 'iauthenticate',
                          'authenticatei', 'authenticatem', 'althenticate', 'authentidcate', 'authenticeate',
                          'auchenticate', 'authentccate', 'authenticatme', 'autohenticate', 'authenticatc',
                          'authezticate', 'authenticatw', 'authentikate', 'autkhenticate', 'authentuicate',
                          'nuthenticate', 'authvnticate', 'authentiaate', 'authentgcate', 'autheuticate',
                          'aqthenticate', 'authenticaxte', 'authenticato', 'authenticaxe', 'authenticiate',
                          'auvthenticate', 'authentixcate', 'authenticathe', 'autmhenticate', 'authenbticate',
                          'auwthenticate', 'autdhenticate', 'asuthenticate', 'authenticatbe', 'auuthenticate',
                          'authentficate', 'authenticajte', 'authetticate', 'uuthenticate', 'authnenticate',
                          'authenticatef', 'autjenticate', 'authenticatde', 'authenticpate', 'adthenticate',
                          'auhthenticate', 'aunthenticate', 'vuthenticate', 'authenticfte', 'autehenticate',
                          'authwnticate', 'authenticaqe', 'authenticatek', 'authenticade', 'authexnticate',
                          'autlenticate', 'awthenticate', 'authpnticate', 'authenticatue', 'authetnticate',
                          'authenticaote', 'authentiiate', 'authentiwate', 'authelnticate', 'audhenticate',
                          'authcnticate', 'auothenticate', 'autwhenticate', 'autvhenticate', 'muthenticate',
                          'authenticatre', 'authenticdate', 'atthenticate', 'authentilcate', 'arthenticate',
                          'aulhenticate', 'authentivcate', 'authenticaoe', 'autthenticate', 'authenticzte',
                          'bauthenticate', 'authenwicate', 'authentyicate', 'authencicate', 'aukhenticate',
                          'authoenticate', 'autqhenticate', 'authentpcate', 'authjenticate', 'autnenticate',
                          'authenmticate', 'authenwticate', 'auzhenticate', 'aquthenticate', 'afuthenticate',
                          'authentifate', 'autheonticate', 'auahenticate', 'authfenticate', 'authonticate',
                          'authznticate', 'authenticatze', 'authenticatq', 'authentickte', 'authtnticate',
                          'authenticave', 'authennicate', 'authmnticate', 'autoenticate', 'authevnticate',
                          'authenticmte', 'authenticake', 'authenticaje', 'akuthenticate', 'acuthenticate',
                          'dauthenticate', 'authentxicate', 'authaenticate', 'authenticabte', 'autuenticate',
                          'authenvticate', 'authentqicate', 'authdenticate', 'authenticite', 'authentxcate',
                          'authentdicate', 'authentlcate', 'duthenticate', 'authenticatew', 'authenvicate',
                          'authenmicate', 'authentacate', 'authenticawte', 'cauthenticate', 'puthenticate',
                          'authenticpte', 'authenticatm', 'authentqcate', 'authentricate', 'authenkicate',
                          'authefnticate', 'authecticate', 'authenticatfe', 'authenticatee', 'auxhenticate',
                          'autzenticate', 'tauthenticate', 'authrenticate', 'authenticateo', 'authenhticate',
                          'authenticete', 'authentoicate', 'authentiicate', 'aguthenticate', 'authenticbate',
                          'authenticvate', 'authekticate', 'aushenticate', 'authenxticate', 'aughenticate',
                          'authenticatu', 'authenqticate', 'hauthenticate', 'authenticaae', 'authfnticate',
                          'authenticuate', 'autqenticate', 'authentirate', 'authehnticate', 'guthenticate',
                          'authenticatea', 'authenticcte', 'authlnticate', 'authinticate', 'ayuthenticate',
                          'authxnticate', 'autheinticate', 'authenticaqte', 'auxthenticate', 'authepticate',
                          'fauthenticate', 'autienticate', 'autheknticate', 'aukthenticate', 'audthenticate',
                          'authernticate', 'authentiwcate', 'aputhenticate', 'aethenticate', 'autrhenticate',
                          'authenticwte', 'euthenticate', 'authenticqte', 'autheqnticate', 'authentitate',
                          'aythenticate', 'autwenticate', 'authentcicate', 'authebnticate', 'authevticate',
                          'pauthenticate', 'auphenticate', 'auithenticate', 'autphenticate', 'authentgicate',
                          'auohenticate', 'avuthenticate', 'authenoticate', 'authenaicate', 'anuthenticate',
                          'authenticzate', 'auteenticate', 'avthenticate', 'authentkicate', 'aubthenticate',
                          'autheunticate', 'aurthenticate', 'authenticaite', 'authenticjate', 'authedticate',
                          'tuthenticate', 'authenticrte', 'authenuicate', 'autuhenticate', 'authenticafte',
                          'authynticate', 'authemnticate', 'authenticatx', 'authentipate', 'autkenticate',
                          'authentbcate', 'auehenticate', 'auwhenticate', 'autxhenticate', 'authenticoate',
                          'vauthenticate', 'authenticafe', 'autfenticate', 'authenticateu', 'authenticatve',
                          'authenticatoe', 'auyhenticate', 'autyhenticate', 'aujhenticate', 'abuthenticate',
                          'autheanticate', 'authlenticate', 'authenticatwe', 'authentiyate', 'apthenticate',
                          'authentvicate', 'authentinate', 'authentecate', 'autahenticate', 'xauthenticate',
                          'authenteicate', 'authentiuate', 'authenbicate', 'autshenticate', 'authenticape',
                          'authpenticate', 'authenticatse', 'autfhenticate', 'authenticbte', 'autdenticate',
                          'authenticase', 'iuthenticate', 'autsenticate', 'authegticate', 'authenticnate',
                          'aufthenticate', 'auqthenticate', 'ajthenticate', 'authentsicate', 'authentjicate',
                          'authhnticate', 'auttenticate', 'autheaticate', 'zuthenticate', 'aunhenticate',
                          'authentickate', 'authenticatez', 'authenticmate', 'aathenticate', 'authuenticate',
                          'authentincate', 'autbhenticate', 'authenticatie', 'authentticate', 'aulthenticate',
                          'authenticakte', 'auathenticate', 'authenyticate', 'authenticatv', 'autheniticate',
                          'authentizcate', 'authentiecate', 'authenzicate', 'luthenticate', 'azthenticate',
                          'authunticate', 'authzenticate', 'authentijate', 'authenticaete', 'authentbicate',
                          'autghenticate', 'authentichate', 'aluthenticate', 'authewnticate', 'wuthenticate',
                          'autheynticate', 'authentdcate', 'authenfticate', 'authenticateb', 'authenticayte',
                          'autnhenticate', 'authentipcate', 'authenaticate', 'uauthenticate', 'auzthenticate',
                          'authesnticate', 'authenticahe', 'autxenticate', 'authenticjte', 'authentircate',
                          'authentwcate', 'authewticate', 'authenticateh', 'authenticates', 'mauthenticate',
                          'authegnticate', 'axuthenticate', 'authenticage', 'authenticatey', 'authentifcate',
                          'authenticante', 'authelticate', 'auethenticate', 'axthenticate', 'authkenticate',
                          'authenticarte', 'cuthenticate', 'authenticatb', 'authenricate', 'aucthenticate',
                          'ahthenticate', 'authentlicate', 'authentiucate', 'a6thenticate', 'a7thenticate',
                          'a8thenticate', 'a^thenticate', 'a&thenticate', 'a*thenticate', 'au4henticate',
                          'au5henticate', 'au6henticate', 'au$henticate', 'au%henticate', 'au^henticate',
                          'auth4nticate', 'auth3nticate', 'auth2nticate', 'auth$nticate', 'auth#nticate',
                          'auth@nticate', 'authe,ticate', 'authe<ticate', 'authen4icate', 'authen5icate',
                          'authen6icate', 'authen$icate', 'authen%icate', 'authen^icate', 'authent7cate',
                          'authent8cate', 'authent9cate', 'authent&cate', 'authent*cate', 'authent(cate',
                          'authentica4e', 'authentica5e', 'authentica6e', 'authentica$e', 'authentica%e',
                          'authentica^e', 'authenticat4', 'authenticat3', 'authenticat2', 'authenticat$',
                          'authenticat#', 'authenticat@', 'gentcode', 'getbcode', 'getcoode', 'getcjode', 'getcoed',
                          'getcole', 'gztcode', 'getcxode', 'geftcode', 'getcokde', 'getcde', 'getcodje', 'getcodo',
                          'gtecode', 'gectode', 'getcpode', 'getcwode', 'gtcode', 'gecode', 'getocde', 'gefcode',
                          'etcode', 'getcdoe', 'getcobde', 'getcod', 'getcodfe', 'getcogde', 'gltcode', 'getcody',
                          'getcodet', 'getlcode', 'getcoe', 'getjcode', 'getrode', 'getcodeo', 'gestcode', 'getyode',
                          'gemcode', 'getncode', 'getcdde', 'getqode', 'getcodea', 'gntcode', 'getcodl', 'egtcode',
                          'getcoda', 'getlode', 'gbetcode', 'getode', 'ggetcode', 'getcodde', 'getcojde', 'getcyode',
                          'gqtcode', 'gietcode', 'getcoge', 'wetcode', 'getcodc', 'ogetcode', 'getcodce', 'getwode',
                          'ketcode', 'setcode', 'geqcode', 'letcode', 'getvode', 'getsode', 'lgetcode', 'gevcode',
                          'getcoke', 'getcooe', 'getcodes', 'getcodne', 'getcodoe', 'petcode', 'getcnode', 'getcodue',
                          'getcose', 'getkcode', 'getcote', 'getcobe', 'getcodev', 'getcwde', 'gwetcode', 'ygetcode',
                          'gketcode', 'gletcode', 'gemtcode', 'getcolde', 'geytcode', 'geacode', 'getnode', 'ghetcode',
                          'gvtcode', 'gectcode', 'gbtcode', 'getcoie', 'metcode', 'gethcode', 'goetcode', 'getctode',
                          'gmtcode', 'getconde', 'getvcode', 'gencode', 'getcomde', 'getcede', 'gctcode', 'getdcode',
                          'getcodex', 'getcodez', 'getcove', 'getcodz', 'gehtcode', 'getcodae', 'ngetcode', 'getcnde',
                          'gelcode', 'gescode', 'getcodu', 'hgetcode', 'getcoded', 'geteode', 'getcowe', 'getxcode',
                          'gettcode', 'geticode', 'getcodt', 'getscode', 'gcetcode', 'zgetcode', 'getcoze', 'getclode',
                          'gertcode', 'gvetcode', 'cetcode', 'getcodh', 'geztcode', 'getxode', 'getgcode', 'geccode',
                          'gextcode', 'geptcode', 'gtetcode', 'getcodeg', 'getcaode', 'getpode', 'getcodeu', 'getcodem',
                          'gdtcode', 'geecode', 'getcodi', 'getcodep', 'getcgde', 'betcode', 'tetcode', 'getccode',
                          'getcoude', 'getcozde', 'gnetcode', 'gekcode', 'getcide', 'tgetcode', 'getecode', 'gjetcode',
                          'gutcode', 'getcodeb', 'getcrde', 'gfetcode', 'getcbode', 'getcodve', 'getgode', 'getdode',
                          'yetcode', 'getcodwe', 'gxtcode', 'getocode', 'getcome', 'getcodei', 'getucode', 'gstcode',
                          'getcodke', 'geltcode', 'getcjde', 'getcoxe', 'getcbde', 'getwcode', 'getcude', 'gpetcode',
                          'getcsde', 'getkode', 'getcgode', 'gyetcode', 'geocode', 'gmetcode', 'getcodq', 'getcodye',
                          'netcode', 'gftcode', 'gethode', 'getcohe', 'getqcode', 'getcade', 'ugetcode', 'getcocde',
                          'geucode', 'getcotde', 'getcofe', 'getcdode', 'gezcode', 'igetcode', 'getcodn', 'getcodbe',
                          'gaetcode', 'gebcode', 'getcyde', 'getcodxe', 'getcodg', 'geqtcode', 'geycode', 'gettode',
                          'getfode', 'getcofde', 'getcoide', 'vgetcode', 'qetcode', 'gitcode', 'gretcode', 'getcoede',
                          'gzetcode', 'gercode', 'geatcode', 'getaode', 'ghtcode', 'gqetcode', 'getcodqe', 'getcodte',
                          'gdetcode', 'getcore', 'gjtcode', 'getcvde', 'getcfde', 'getcods', 'getcodw', 'dgetcode',
                          'gepcode', 'getacode', 'getpcode', 'fetcode', 'gektcode', 'getciode', 'grtcode', 'getfcode',
                          'getcorde', 'getcoae', 'getcodse', 'sgetcode', 'getcuode', 'gedtcode', 'getcodx', 'getcodre',
                          'uetcode', 'getcodme', 'gehcode', 'getcodee', 'getcvode', 'getcoyde', 'hetcode', 'getcodie',
                          'getcqode', 'agetcode', 'getccde', 'kgetcode', 'getcope', 'getcodk', 'fgetcode', 'getzode',
                          'getcodge', 'getcodpe', 'getczde', 'getcodeh', 'getcowde', 'gewtcode', 'bgetcode', 'ietcode',
                          'getmode', 'getcodj', 'getcrode', 'rgetcode', 'gevtcode', 'getcoden', 'geitcode', 'getcovde',
                          'gedcode', 'guetcode', 'getcsode', 'getcohde', 'retcode', 'getcodey', 'getcoce', 'getcqde',
                          'getcodf', 'getczode', 'jetcode', 'gegcode', 'getcodew', 'gsetcode', 'geetcode', 'getcoade',
                          'gytcode', 'xgetcode', 'getckde', 'getcodhe', 'jgetcode', 'getrcode', 'vetcode', 'getjode',
                          'gotcode', 'getuode', 'getcopde', 'gegtcode', 'getclde', 'eetcode', 'oetcode', 'egetcode',
                          'getcmde', 'getiode', 'gwtcode', 'gejtcode', 'zetcode', 'getcodm', 'gewcode', 'getcone',
                          'mgetcode', 'getoode', 'getcodel', 'getcodd', 'getcoee', 'getchde', 'getcodv', 'gptcode',
                          'gebtcode', 'detcode', 'pgetcode', 'geicode', 'geutcode', 'getycode', 'gejcode', 'cgetcode',
                          'getcodle', 'xetcode', 'getcoder', 'getcosde', 'getcodef', 'getcodp', 'qgetcode', 'ggtcode',
                          'getceode', 'gatcode', 'getcodze', 'getcoqe', 'getcpde', 'gttcode', 'getcxde', 'gktcode',
                          'getmcode', 'aetcode', 'getzcode', 'getcoue', 'getcoje', 'gexcode', 'getcodej', 'getcodek',
                          'getbode', 'getcodb', 'getchode', 'gxetcode', 'getcoye', 'geotcode', 'getcoqde', 'getckode',
                          'getcoxde', 'wgetcode', 'getcmode', 'getctde', 'getcodeq', 'getcodec', 'getcodr', 'getcfode',
                          'g4tcode', 'g3tcode', 'g2tcode', 'g$tcode', 'g#tcode', 'g@tcode', 'ge4code', 'ge5code',
                          'ge6code', 'ge$code', 'ge%code', 'ge^code', 'getc8de', 'getc9de', 'getc0de', 'getc;de',
                          'getc*de', 'getc(de', 'getc)de', 'getcod4', 'getcod3', 'getcod2', 'getcod$', 'getcod#',
                          'getcod@', 'tken', 'tokdn', 'zoken', 'oken', 'toen', 'tokex', 'torken', 'tosen', 'otoken',
                          'tokek', 'tokn', 'tokwen', 'tqoken', 'qoken', 'tfken', 'toekn', 'tokeo', 'toklen', 'topen',
                          'tokenc', 'tokej', 'tokne', 'toke', 'otken', 'tokedn', 'tnoken', 'tojen', 'ltoken', 'tokee',
                          'woken', 'ptoken', 'btoken', 'tokegn', 'touen', 'tokbn', 'tokez', 'tokien', 'tokea', 'toqken',
                          'joken', 'tokyn', 'txoken', 'tokmen', 'stoken', 'tkoen', 'tokene', 'eoken', 'toiken',
                          'tokeen', 'toked', 'tokwn', 'tokenm', 'toaken', 'teken', 'tnken', 'tokenh', 'loken', 'mtoken',
                          'tsoken', 'tokln', 'tokem', 'etoken', 'tkken', 'tokenn', 'goken', 'towken', 'tocen', 'toaen',
                          'tokeh', 'tokaen', 'wtoken', 'tokeb', 'soken', 'xoken', 'tuken', 'tokeq', 'tokeyn', 'tcoken',
                          'tokken', 'twoken', 'tozken', 'tdoken', 'ftoken', 'roken', 'tokec', 'toben', 'tokenr',
                          'tokent', 'tokev', 'tokejn', 'tokebn', 'tdken', 'boken', 'qtoken', 'tuoken', 'tohen', 'tokxn',
                          'tokrn', 'tohken', 'tokenj', 'tokein', 'tokens', 'toketn', 'touken', 'tofen', 'tokan',
                          'tosken', 'tofken', 'tiken', 'tokes', 'tokoen', 'tsken', 'toien', 'toknen', 'tvken', 'tokel',
                          'tokhn', 'tokenp', 'toker', 'foken', 'tonken', 'tokemn', 'htoken', 'hoken', 'tokvn', 'gtoken',
                          'tokmn', 'tokzn', 'toten', 'tokben', 'poken', 'tmoken', 'tokevn', 'tokesn', 'troken', 'tozen',
                          'tokern', 'koken', 'tyoken', 'tobken', 'tzoken', 'tokekn', 'tokenv', 'tgoken', 'tokena',
                          'tokehn', 'tokean', 'toksen', 'tokey', 'utoken', 'tlken', 'vtoken', 'xtoken', 'tokend',
                          'tooen', 'tboken', 'moken', 'tzken', 'toqen', 'tbken', 'toeen', 'tokfn', 'tokhen', 'tokqen',
                          'ktoken', 'tocken', 'ntoken', 'tmken', 'tokgn', 'toknn', 'tyken', 'toren', 'toxen', 'toyen',
                          'tokewn', 'aoken', 'tokeln', 'tolen', 'tokeny', 'tokkn', 'voken', 'tomen', 'tokden', 'tokenl',
                          'trken', 'tokei', 'tokenz', 'tokeun', 'tojken', 'ttoken', 'toden', 'toket', 'tokezn',
                          'tokenw', 'tokenu', 'uoken', 'tokexn', 'toktn', 'tgken', 'tioken', 'tokjen', 'tokeon',
                          'teoken', 'toven', 'tokenf', 'towen', 'tloken', 'toksn', 'tokepn', 'yoken', 'tokeg', 'tokzen',
                          'tokenx', 'thoken', 'tpoken', 'tpken', 'tokxen', 'tooken', 'tokpen', 'ioken', 'tjoken',
                          'tolken', 'ctoken', 'tokecn', 'coken', 'tokeno', 'tfoken', 'tvoken', 'tokeu', 'tokfen',
                          'tokjn', 'tokeqn', 'toyken', 'ztoken', 'taken', 'ttken', 'tokefn', 'tokcn', 'todken',
                          'tokeni', 'tqken', 'tokgen', 'ooken', 'ytoken', 'toeken', 'tokren', 'tokef', 'toxken',
                          'topken', 'totken', 'tokqn', 'txken', 'itoken', 'tokten', 'tokpn', 'twken', 'togken', 'tjken',
                          'togen', 'tokep', 'tokenb', 'tkoken', 'rtoken', 'doken', 'tokven', 'noken', 'tokon', 'tonen',
                          'tokuen', 'tokyen', 'tomken', 'tokun', 'tokenk', 'dtoken', 'tokeng', 'atoken', 'jtoken',
                          'taoken', 'tcken', 'tokin', 'thken', 'tovken', 'tokenq', 'tokew', 'tokcen', '4oken', '5oken',
                          '6oken', '$oken', '%oken', '^oken', 't8ken', 't9ken', 't0ken', 't;ken', 't*ken', 't(ken',
                          't)ken', 'to.en', 'to,en', 'to>en', 'to<en', 'tok4n', 'tok3n', 'tok2n', 'tok$n', 'tok#n',
                          'tok@n', 'toke,', 'toke<', 'gettken', 'gettqken', 'gettoekn', 'getqtoken', 'grettoken',
                          'gettokne', 'gttoken', 'gsettoken', 'gettokenh', 'gettkoen', 'getoken', 'gettloken',
                          'gtetoken', 'kgettoken', 'gethoken', 'gyettoken', 'gettiken', 'ugettoken', 'gettoyen',
                          'gettoke', 'fgettoken', 'gzttoken', 'hgettoken', 'jettoken', 'gettokeen', 'gettoen',
                          'gettoknn', 'ettoken', 'gettokjen', 'ghettoken', 'dettoken', 'gettoktn', 'gettokon',
                          'gettokden', 'gettokn', 'gettpoken', 'gettqoken', 'gettokebn', 'yettoken', 'egttoken',
                          'gettokeng', 'gettokyn', 'gettokeno', 'gevtoken', 'tettoken', 'ggettoken', 'glttoken',
                          'getftoken', 'gettokeh', 'gelttoken', 'gettofken', 'rgettoken', 'gnttoken', 'gettokenc',
                          'gettokem', 'geqttoken', 'gettosken', 'getotken', 'eettoken', 'gettokeln', 'gettokpn',
                          'getqoken', 'pgettoken', 'bettoken', 'gettokesn', 'hettoken', 'gettoyken', 'gettokhn',
                          'gettokan', 'gpttoken', 'geteoken', 'gehtoken', 'gettoeken', 'gepttoken', 'getnoken',
                          'settoken', 'qettoken', 'rettoken', 'gettokmen', 'gettokrn', 'gjttoken', 'gettvoken',
                          'geittoken', 'gattoken', 'pettoken', 'gettwoken', 'gewtoken', 'gettokes', 'gettsoken',
                          'gettokeni', 'gettokenr', 'lgettoken', 'getxtoken', 'gyttoken', 'gettokekn', 'cettoken',
                          'wgettoken', 'gettokeon', 'gettokens', 'gettohken', 'vgettoken', 'getkoken', 'gettoren',
                          'gebttoken', 'gettokev', 'gettokfen', 'gettokedn', 'gettokien', 'geztoken', 'gettokenf',
                          'gtettoken', 'gettokgn', 'gqettoken', 'getbtoken', 'gettpken', 'gettokei', 'gettonken',
                          'gettokoen', 'getjtoken', 'getfoken', 'gettokmn', 'gettokenu', 'gettohen', 'getrtoken',
                          'gettokwen', 'gettokenk', 'gettokef', 'gettokex', 'zettoken', 'gettokenn', 'gettoeen',
                          'gzettoken', 'getboken', 'geytoken', 'gettaoken', 'bgettoken', 'gettokein', 'gestoken',
                          'gettokemn', 'gettokeb', 'getztoken', 'gettgoken', 'getdoken', 'guttoken', 'gefttoken',
                          'gettokeny', 'tgettoken', 'gentoken', 'gettokend', 'gettokeq', 'gettokeqn', 'igettoken',
                          'gettokejn', 'getthken', 'getvoken', 'getctoken', 'gbttoken', 'gettokln', 'fettoken',
                          'gcttoken', 'getttoken', 'iettoken', 'gettokqen', 'gettfoken', 'vettoken', 'gettdken',
                          'getltoken', 'gettozken', 'gjettoken', 'gettokpen', 'geotoken', 'gettoaken', 'gettokena',
                          'gettouen', 'gettjken', 'geetoken', 'getitoken', 'gettbken', 'gettmken', 'gettoksen',
                          'gettrken', 'gkettoken', 'xettoken', 'getsoken', 'gezttoken', 'gettofen', 'gegttoken',
                          'getthoken', 'ogettoken', 'gettooken', 'getstoken', 'gettcoken', 'gettokey', 'geuttoken',
                          'gettokin', 'genttoken', 'gettokuen', 'getyoken', 'getpoken', 'gettokene', 'gettokefn',
                          'gerttoken', 'getooken', 'gettcken', 'gectoken', 'gettokenj', 'getgoken', 'gettopen',
                          'kettoken', 'gettovken', 'gettokean', 'lettoken', 'gettokdn', 'gewttoken', 'gettxoken',
                          'gettoaen', 'gettokjn', 'gettokep', 'gegtoken', 'gwttoken', 'mettoken', 'gettoiken',
                          'grttoken', 'getteken', 'gettoqken', 'gettokexn', 'gvettoken', 'gesttoken', 'gettokecn',
                          'gettomken', 'gnettoken', 'xgettoken', 'gettokenz', 'getaoken', 'gettokezn', 'gettboken',
                          'gvttoken', 'gettyken', 'gettokken', 'gettokea', 'gevttoken', 'gettokej', 'gettokzn',
                          'gettokwn', 'gettokevn', 'gertoken', 'gextoken', 'gettokent', 'gwettoken', 'goettoken',
                          'gettokgen', 'getytoken', 'gettozen', 'gpettoken', 'gettokkn', 'getutoken', 'gettoked',
                          'gottoken', 'gettokenq', 'geptoken', 'gettowken', 'getetoken', 'gettoket', 'geettoken',
                          'gettogen', 'gekttoken', 'gettoker', 'gettioken', 'gettokenw', 'getteoken', 'gmttoken',
                          'gettolen', 'gettoxken', 'ghttoken', 'gettaken', 'gqttoken', 'gettokten', 'gettolken',
                          'getotoken', 'gexttoken', 'ngettoken', 'gettokren', 'getzoken', 'getioken', 'glettoken',
                          'getwtoken', 'gettokeyn', 'gettokven', 'aettoken', 'gittoken', 'gettokhen', 'getmoken',
                          'gethtoken', 'gfttoken', 'gettouken', 'gettuken', 'getuoken', 'gettokenl', 'gettooen',
                          'oettoken', 'gettzken', 'gxttoken', 'gettnken', 'gettojken', 'egettoken', 'geltoken',
                          'gettokehn', 'getptoken', 'gettocen', 'gettoknen', 'ggttoken', 'gbettoken', 'gettokqn',
                          'gettoven', 'gettowen', 'gettoden', 'dgettoken', 'gettokzen', 'gettokenv', 'gettokel',
                          'gettogken', 'gejttoken', 'geitoken', 'gettokeun', 'gettokenp', 'gehttoken', 'getatoken',
                          'gebtoken', 'gettokfn', 'gettwken', 'gettosen', 'gettfken', 'gettoqen', 'gfettoken',
                          'gettokee', 'gettobken', 'getdtoken', 'agettoken', 'nettoken', 'gettokew', 'getxoken',
                          'gettocken', 'gettojen', 'gedttoken', 'gettmoken', 'getroken', 'gettoketn', 'sgettoken',
                          'gettgken', 'qgettoken', 'gettokewn', 'gettokcen', 'gettdoken', 'gettokenx', 'gaettoken',
                          'geqtoken', 'geftoken', 'guettoken', 'gettkoken', 'cgettoken', 'gettokepn', 'gxettoken',
                          'geatoken', 'getmtoken', 'gemttoken', 'getktoken', 'getcoken', 'gettxken', 'gettodken',
                          'gettokben', 'geattoken', 'gdttoken', 'gettokenm', 'gejtoken', 'zgettoken', 'geottoken',
                          'gsttoken', 'gettjoken', 'gettuoken', 'gettlken', 'getttken', 'gtttoken', 'gettoben',
                          'gdettoken', 'gettyoken', 'gettnoken', 'getvtoken', 'gettokvn', 'gettopken', 'gettonen',
                          'gmettoken', 'gettroken', 'gedtoken', 'jgettoken', 'gemtoken', 'geyttoken', 'getloken',
                          'gettkken', 'gettokbn', 'getgtoken', 'getntoken', 'gettokxen', 'gettoksn', 'gettokeo',
                          'gettoklen', 'gecttoken', 'gettomen', 'gettotken', 'uettoken', 'gettokun', 'gettoien',
                          'gettokeu', 'gettokyen', 'getwoken', 'gkttoken', 'gettzoken', 'gcettoken', 'ygettoken',
                          'gettoten', 'mgettoken', 'gettvken', 'gettsken', 'gettokxn', 'gettokaen', 'getjoken',
                          'wettoken', 'gettorken', 'geutoken', 'gettokec', 'giettoken', 'gettokcn', 'gettokern',
                          'gettokeg', 'gettokenb', 'gettokegn', 'gektoken', 'gettoxen', 'gettokez', 'gettokek',
                          'g4ttoken', 'g3ttoken', 'g2ttoken', 'g$ttoken', 'g#ttoken', 'g@ttoken', 'ge4token',
                          'ge5token', 'ge6token', 'ge$token', 'ge%token', 'ge^token', 'get4oken', 'get5oken',
                          'get6oken', 'get$oken', 'get%oken', 'get^oken', 'gett8ken', 'gett9ken', 'gett0ken',
                          'gett;ken', 'gett*ken', 'gett(ken', 'gett)ken', 'getto.en', 'getto,en', 'getto>en',
                          'getto<en', 'gettok4n', 'gettok3n', 'gettok2n', 'gettok$n', 'gettok#n', 'gettok@n',
                          'gettoke,', 'gettoke<', 'getlogni', 'getlogdn', 'getlgoin', 'getloghn', 'ogetlogin',
                          'gestlogin', 'geslogin', 'gettlogin', 'getlogdin', 'gtlogin', 'gelogin', 'etlogin', 'getlgin',
                          'getlogig', 'getlogn', 'getloin', 'gerlogin', 'getloign', 'getolgin', 'cetlogin', 'getlomgin',
                          'getlogien', 'getloginw', 'getlooin', 'getlvogin', 'gtelogin', 'geqlogin', 'getlogie',
                          'getlogijn', 'getlogini', 'getlogwn', 'geltogin', 'guetlogin', 'egtlogin', 'wetlogin',
                          'sgetlogin', 'getlohgin', 'gellogin', 'getlogkin', 'getlogim', 'getogin', 'getlgogin',
                          'gnetlogin', 'gejtlogin', 'getloogin', 'getlsogin', 'gotlogin', 'getlogpn', 'getlogi',
                          'getlpgin', 'gexlogin', 'gdtlogin', 'getlogine', 'netlogin', 'getlogid', 'getlogip',
                          'getloginp', 'getlogik', 'getlopin', 'lgetlogin', 'getlonin', 'getlognn', 'getlogzin',
                          'getlogiwn', 'getloginf', 'gvetlogin', 'getlovin', 'getwlogin', 'getloginn', 'jgetlogin',
                          'setlogin', 'getloegin', 'getflogin', 'getloein', 'geclogin', 'gitlogin', 'getloginm',
                          'getloginl', 'getcogin', 'getlokin', 'getlmogin', 'geklogin', 'gemlogin', 'getlogind',
                          'getlojin', 'vgetlogin', 'gewtlogin', 'getllogin', 'hgetlogin', 'getloginy', 'getqogin',
                          'getiogin', 'getloghin', 'getlogpin', 'getlfgin', 'getlogio', 'getlogix', 'gktlogin',
                          'getlogbn', 'getlogij', 'getxlogin', 'getloggin', 'geglogin', 'ggetlogin', 'getologin',
                          'getilogin', 'geetlogin', 'bgetlogin', 'getlogixn', 'yetlogin', 'getlouin', 'getlogisn',
                          'getloginx', 'getalogin', 'getlomin', 'getlogitn', 'getlozin', 'gctlogin', 'getlodgin',
                          'getlogsn', 'gethogin', 'getlobin', 'getloggn', 'hetlogin', 'getlogimn', 'geteogin',
                          'getlggin', 'getlqgin', 'getlkogin', 'gutlogin', 'getlogon', 'getfogin', 'getlogmn',
                          'getlodin', 'jetlogin', 'getrlogin', 'goetlogin', 'getlotin', 'gethlogin', 'getlwgin',
                          'gaetlogin', 'getbogin', 'getlorgin', 'kgetlogin', 'vetlogin', 'getlogins', 'getlhgin',
                          'getaogin', 'gftlogin', 'getglogin', 'pgetlogin', 'getlogvin', 'getlogink', 'getdogin',
                          'gpetlogin', 'getlorin', 'getlogiln', 'getlowgin', 'gwetlogin', 'gytlogin', 'getlogfin',
                          'getldgin', 'uetlogin', 'ghtlogin', 'aetlogin', 'getlcgin', 'getlognin', 'ngetlogin',
                          'getlogian', 'getlogzn', 'getzlogin', 'getlogicn', 'getlegin', 'getlogiq', 'gentlogin',
                          'getlopgin', 'getloginj', 'getlolin', 'getlkgin', 'getlogiy', 'getlogrn', 'getlohin',
                          'getlogan', 'getlzgin', 'getoogin', 'getlogiqn', 'getelogin', 'gwtlogin', 'getloqin',
                          'getlsgin', 'gntlogin', 'getlogiun', 'gyetlogin', 'getljgin', 'getulogin', 'getvlogin',
                          'wgetlogin', 'getlogir', 'retlogin', 'getlogiw', 'getlogihn', 'fetlogin', 'getlcogin',
                          'getlofin', 'gextlogin', 'getkogin', 'ugetlogin', 'getlbogin', 'getlogein', 'getlogirn',
                          'genlogin', 'getlongin', 'getlngin', 'getlogiz', 'gxtlogin', 'getlogain', 'getlqogin',
                          'getrogin', 'igetlogin', 'getlogiin', 'getgogin', 'getlosin', 'getlogina', 'getlogino',
                          'getloginq', 'gertlogin', 'getlogen', 'gmtlogin', 'geilogin', 'getlogikn', 'getlogib',
                          'getlosgin', 'gfetlogin', 'xetlogin', 'getlogifn', 'getlogcin', 'getlocgin', 'getlogxin',
                          'getlzogin', 'getloyin', 'gealogin', 'gbetlogin', 'gehtlogin', 'xgetlogin', 'getlobgin',
                          'gietlogin', 'betlogin', 'rgetlogin', 'ietlogin', 'getlogyin', 'getloagin', 'getlogjn',
                          'getlogfn', 'getlogtin', 'getlogvn', 'getloguin', 'gettogin', 'getlugin', 'getlogun',
                          'geltlogin', 'geylogin', 'getltgin', 'getldogin', 'dgetlogin', 'getlogipn', 'getzogin',
                          'getloginh', 'geologin', 'getlxogin', 'getloginz', 'getllgin', 'geulogin', 'geytlogin',
                          'getlogizn', 'getlokgin', 'getlogidn', 'getloginc', 'getlhogin', 'getlogil', 'getloqgin',
                          'gewlogin', 'getlogcn', 'gatlogin', 'gletlogin', 'getblogin', 'getlogic', 'geztlogin',
                          'gsetlogin', 'getlocin', 'getlogoin', 'getlogiv', 'letlogin', 'getlogii', 'getlogivn',
                          'getlrgin', 'getlotgin', 'getlmgin', 'getloginb', 'geblogin', 'getlogmin', 'petlogin',
                          'gcetlogin', 'getnlogin', 'gttlogin', 'getlxgin', 'geftlogin', 'gtetlogin', 'getslogin',
                          'geptlogin', 'geutlogin', 'getqlogin', 'gjetlogin', 'getloging', 'getlolgin', 'getlogbin',
                          'getlowin', 'gbtlogin', 'getlbgin', 'getlogion', 'getlogsin', 'getlpogin', 'gejlogin',
                          'geqtlogin', 'getlogiyn', 'getljogin', 'zetlogin', 'getjlogin', 'getloginr', 'gectlogin',
                          'fgetlogin', 'getlogyn', 'getlojgin', 'gdetlogin', 'getloigin', 'gedtlogin', 'getmlogin',
                          'getlogiu', 'gevtlogin', 'getlogrin', 'getlfogin', 'gltlogin', 'getlwogin', 'gjtlogin',
                          'getltogin', 'gemtlogin', 'geotlogin', 'getplogin', 'gstlogin', 'tgetlogin', 'gqtlogin',
                          'getpogin', 'getligin', 'getdlogin', 'getloygin', 'ketlogin', 'getloiin', 'getklogin',
                          'getleogin', 'getlogis', 'getlogign', 'tetlogin', 'getloglin', 'getlogqn', 'getlogif',
                          'getlogxn', 'gevlogin', 'qetlogin', 'getloxgin', 'metlogin', 'ghetlogin', 'getlogibn',
                          'getlogjin', 'agetlogin', 'getlovgin', 'gegtlogin', 'getloxin', 'getylogin', 'qgetlogin',
                          'getvogin', 'getloginu', 'getnogin', 'getuogin', 'gedlogin', 'getlogia', 'getlogln',
                          'gretlogin', 'gebtlogin', 'getloain', 'getlogint', 'geplogin', 'getxogin', 'gzetlogin',
                          'getlagin', 'gptlogin', 'getluogin', 'getyogin', 'ygetlogin', 'getmogin', 'cgetlogin',
                          'getlyogin', 'getclogin', 'gvtlogin', 'getlozgin', 'zgetlogin', 'getlygin', 'gezlogin',
                          'gqetlogin', 'getlogkn', 'gketlogin', 'detlogin', 'getliogin', 'oetlogin', 'getlogit',
                          'ggtlogin', 'getlofgin', 'getloginv', 'getlogwin', 'getlnogin', 'getlogtn', 'getlogih',
                          'gztlogin', 'geflogin', 'geelogin', 'eetlogin', 'getlogqin', 'geitlogin', 'gmetlogin',
                          'gxetlogin', 'geatlogin', 'grtlogin', 'getwogin', 'mgetlogin', 'getsogin', 'getjogin',
                          'getlougin', 'getlaogin', 'getlrogin', 'gehlogin', 'getlvgin', 'egetlogin', 'gektlogin',
                          'g4tlogin', 'g3tlogin', 'g2tlogin', 'g$tlogin', 'g#tlogin', 'g@tlogin', 'ge4login',
                          'ge5login', 'ge6login', 'ge$login', 'ge%login', 'ge^login', 'get;ogin', 'get/ogin',
                          'get.ogin', 'get,ogin', 'get?ogin', 'get>ogin', 'get<ogin', 'getl8gin', 'getl9gin',
                          'getl0gin', 'getl;gin', 'getl*gin', 'getl(gin', 'getl)gin', 'getlog7n', 'getlog8n',
                          'getlog9n', 'getlog&n', 'getlog*n', 'getlog(n', 'getlogi,', 'getlogi<', 'exchacge', 'xchange',
                          'exchanhe', 'eaxchange', 'exchagne', 'epxchange', 'excbange', 'exchahnge', 'exchane',
                          'exchnage', 'exchansge', 'excbhange', 'exchangae', 'exchnge', 'exchangex', 'excfhange',
                          'xechange', 'eyxchange', 'exchangt', 'exchabnge', 'echange', 'exchaunge', 'exchang',
                          'ecxhange', 'exchangp', 'exchage', 'lxchange', 'exhcange', 'exchantge', 'excmhange',
                          'exchangze', 'ecxchange', 'exchangte', 'exuhange', 'excvange', 'sxchange', 'exchfnge',
                          'exmhange', 'excihange', 'excahnge', 'eechange', 'exchkange', 'exchvnge', 'exchxange',
                          'eichange', 'exchanege', 'excxange', 'exchanxge', 'exhange', 'exchandge', 'excaange',
                          'exchangk', 'exchanqge', 'exchmnge', 'exchzange', 'exchagnge', 'exvhange', 'vxchange',
                          'exhchange', 'bxchange', 'elchange', 'excange', 'exchaknge', 'xxchange', 'exchaqnge',
                          'exchanwe', 'exchinge', 'exchangye', 'excgange', 'vexchange', 'exchanse', 'iexchange',
                          'excchange', 'exchadge', 'exchsange', 'ekxchange', 'exchanoe', 'exchanze', 'exchangoe',
                          'exchangfe', 'exchanghe', 'exchaneg', 'exchangr', 'excjange', 'exjchange', 'ejxchange',
                          'dxchange', 'exchanue', 'exchangce', 'exchpnge', 'qxchange', 'pxchange', 'rxchange',
                          'exchanne', 'sexchange', 'excmange', 'exahange', 'exchanged', 'exchavge', 'exchcange',
                          'exchangxe', 'exchabge', 'extchange', 'exchavnge', 'fxchange', 'exechange', 'exkhange',
                          'exchiange', 'exchangde', 'exihange', 'exchangc', 'exchangle', 'exchanage', 'exchanpge',
                          'exclange', 'pexchange', 'exchangbe', 'exchayge', 'eexchange', 'rexchange', 'exchance',
                          'excrange', 'exckhange', 'eychange', 'qexchange', 'excuange', 'kxchange', 'exchangs',
                          'exchknge', 'expchange', 'exchangel', 'exychange', 'exchxnge', 'exchapge', 'evchange',
                          'exchangez', 'exchangei', 'exchangeo', 'exchangev', 'oexchange', 'exchangeu', 'exlchange',
                          'exchangy', 'exchanye', 'exchaige', 'exchaage', 'exchalnge', 'emchange', 'exctange',
                          'exchangb', 'exchangv', 'exchangge', 'edchange', 'exchangee', 'exchyange', 'exlhange',
                          'exchznge', 'exchanbge', 'exichange', 'gexchange', 'exchdnge', 'exchanget', 'esxchange',
                          'exnhange', 'exchoange', 'exchanyge', 'exchangie', 'exchangue', 'zxchange', 'excahange',
                          'exchdange', 'exchangen', 'exchangx', 'enchange', 'exwchange', 'eixchange', 'exchagge',
                          'exchanie', 'exchangg', 'excehange', 'exchangre', 'hxchange', 'exchafge', 'exchgnge',
                          'exthange', 'exchante', 'exchanrge', 'exchaege', 'wexchange', 'exczange', 'exchunge',
                          'yexchange', 'exchlange', 'exchaange', 'exchankge', 'exchajge', 'efxchange', 'excpange',
                          'excnhange', 'evxchange', 'euchange', 'exchapnge', 'excyange', 'exqhange', 'exchasnge',
                          'exchangea', 'exchanuge', 'exyhange', 'exchahge', 'exvchange', 'excnange', 'ezxchange',
                          'hexchange', 'exohange', 'exchangve', 'exchnnge', 'jxchange', 'exchjnge', 'efchange',
                          'enxchange', 'gxchange', 'exchtnge', 'exchatge', 'exnchange', 'exchanzge', 'exchgange',
                          'exchangej', 'exccange', 'exchhange', 'exchakge', 'exchanxe', 'exchvange', 'exdchange',
                          'yxchange', 'exchangje', 'excfange', 'exchangne', 'exqchange', 'jexchange', 'bexchange',
                          'exchangme', 'exrhange', 'ebxchange', 'exchangpe', 'exchtange', 'exchangu', 'exchauge',
                          'exchqange', 'egchange', 'exchaonge', 'exchannge', 'exchanpe', 'excphange', 'exmchange',
                          'epchange', 'exchangek', 'exchanle', 'exchanges', 'exchangn', 'exciange', 'exehange',
                          'exdhange', 'excthange', 'erxchange', 'exchpange', 'exxhange', 'exfchange', 'exzhange',
                          'exchbnge', 'exchanre', 'exchlnge', 'excrhange', 'exchanoge', 'exchawge', 'exchanfge',
                          'excwhange', 'exschange', 'exchaenge', 'eqxchange', 'exfhange', 'exchangwe', 'xexchange',
                          'exchenge', 'exchangf', 'ekchange', 'exchamge', 'exrchange', 'cxchange', 'exchangj',
                          'excoange', 'exchanqe', 'euxchange', 'ehxchange', 'ewchange', 'exckange', 'exchangqe',
                          'exchanvge', 'fexchange', 'exchynge', 'exchaoge', 'excuhange', 'exgchange', 'exxchange',
                          'exchanwge', 'exuchange', 'exachange', 'exceange', 'exchonge', 'exchangq', 'exchangeg',
                          'exchango', 'excqhange', 'exwhange', 'excyhange', 'exchqnge', 'exchuange', 'mxchange',
                          'exchanige', 'exkchange', 'elxchange', 'eoxchange', 'exchainge', 'excdhange', 'etchange',
                          'exchangse', 'exchangm', 'exchaqge', 'erchange', 'excghange', 'exzchange', 'wxchange',
                          'dexchange', 'exchsnge', 'exchanhge', 'exchalge', 'aexchange', 'exbhange', 'axchange',
                          'exchangef', 'exchanger', 'excwange', 'exchanae', 'exchangeb', 'lexchange', 'exchangh',
                          'exchangw', 'exchacnge', 'exchawnge', 'exchwange', 'oxchange', 'excharnge', 'zexchange',
                          'excdange', 'emxchange', 'uxchange', 'exchasge', 'ewxchange', 'exhhange', 'exchangi',
                          'edxchange', 'excohange', 'exchanfe', 'excvhange', 'exchanlge', 'exghange', 'exchaznge',
                          'exchangem', 'excharge', 'exchanke', 'exchatnge', 'exchanjge', 'exchanje', 'exchangl',
                          'exjhange', 'eachange', 'eschange', 'excheange', 'egxchange', 'exchangew', 'exshange',
                          'exphange', 'uexchange', 'exchhnge', 'exchangey', 'txchange', 'exchadnge', 'exchanme',
                          'exbchange', 'exchnange', 'exchamnge', 'exchaxnge', 'nxchange', 'exchrange', 'excxhange',
                          'exchanve', 'exchangz', 'etxchange', 'exchanee', 'exchancge', 'exchangep', 'excsange',
                          'exchazge', 'exchaynge', 'exchangec', 'exchafnge', 'ixchange', 'exchanga', 'excshange',
                          'ebchange', 'excjhange', 'exchangeq', 'ezchange', 'exchmange', 'exchangd', 'kexchange',
                          'ejchange', 'exchjange', 'ecchange', 'exchbange', 'exchanbe', 'exchfange', 'nexchange',
                          'exochange', 'excqange', 'exchanmge', 'texchange', 'exchwnge', 'exclhange', 'eochange',
                          'exchaxge', 'eqchange', 'mexchange', 'exchangke', 'exczhange', 'ehchange', 'exchangeh',
                          'exchcnge', 'exchrnge', 'cexchange', 'exchajnge', 'exchande', '4xchange', '3xchange',
                          '2xchange', '$xchange', '#xchange', '@xchange', 'excha,ge', 'excha<ge', 'exchang4',
                          'exchang3', 'exchang2', 'exchang$', 'exchang#', 'exchang@', '/authenticate', '/getcode',
                          '/token', '/getlogin', '/exchange', 'sigin', 'ignin', 'sinin', 'signkin', 'sginin', 'signinu',
                          'isgnin', 'signii', 'signpn', 'signi', 'signsin', 'sigrnin', 'sgnin', 'signic', 'siognin',
                          'xsignin', 'signin', 'singin', 'siginn', 'eignin', 'signwn', 'sigjin', 'signbin', 'signir',
                          'siagnin', 'siglnin', 'sigvnin', 'sigiin', 'signiz', 'signhn', 'sjgnin', 'signitn', 'sigbnin',
                          'signia', 'sqgnin', 'signgn', 'sigcnin', 'signie', 'signln', 'signzin', 'signni', 'sienin',
                          'sionin', 'zignin', 'signgin', 'signn', 'lignin', 'gsignin', 'sigdnin', 'ksignin', 'smgnin',
                          'sisnin', 'signinn', 'sijnin', 'signiy', 'sixnin', 'signib', 'signiun', 'signiq', 'signibn',
                          'siugnin', 'sivnin', 'osignin', 'swignin', 'sizgnin', 'signins', 'signign', 'signiin',
                          'signil', 'csignin', 'signen', 'sitnin', 'xignin', 'signinx', 'sigenin', 'smignin', 'signtin',
                          'sigwin', 'oignin', 'signio', 'bignin', 'signiqn', 'signini', 'sicnin', 'signinz', 'sigynin',
                          'signbn', 'aignin', 'spgnin', 'signvin', 'siegnin', 'sirgnin', 'sigmin', 'sbgnin', 'signinc',
                          'msignin', 'siygnin', 'signcin', 'signcn', 'signino', 'signkn', 'sfgnin', 'nignin', 'sdignin',
                          'signij', 'signdin', 'sisgnin', 'signfn', 'mignin', 'signsn', 'vsignin', 'sighnin', 'svgnin',
                          'signihn', 'jsignin', 'signjin', 'vignin', 'spignin', 'siggin', 'srgnin', 'sigvin', 'tignin',
                          'ssgnin', 'sqignin', 'signinf', 'siwgnin', 'sagnin', 'signizn', 'sinnin', 'signqin',
                          'suignin', 'signinl', 'signinq', 'signinh', 'sifnin', 'bsignin', 'signiyn', 'sognin',
                          'sianin', 'ysignin', 'sigtin', 'siignin', 'slgnin', 'signoin', 'signdn', 'syignin', 'sigtnin',
                          'stgnin', 'siqnin', 'swgnin', 'sigqin', 'siinin', 'signnin', 'wignin', 'sigpnin', 'siynin',
                          'shignin', 'sigbin', 'signqn', 'signint', 'siznin', 'signiny', 'sugnin', 'signinw', 'sicgnin',
                          'sigrin', 'sighin', 'signjn', 'sigkin', 'siknin', 'signirn', 'signpin', 'signig', 'signxin',
                          'dsignin', 'sigyin', 'sfignin', 'sigein', 'sxgnin', 'sijgnin', 'signiu', 'signinv', 'signis',
                          'szignin', 'signein', 'sixgnin', 'gignin', 'qignin', 'hsignin', 'sihnin', 'lsignin', 'signix',
                          'signyin', 'sipnin', 'signipn', 'signzn', 'signuin', 'signmn', 'skignin', 'sigjnin', 'hignin',
                          'signien', 'signixn', 'sidgnin', 'snignin', 'dignin', 'sibgnin', 'ssignin', 'sxignin',
                          'sigoin', 'tsignin', 'signijn', 'signifn', 'sihgnin', 'siwnin', 'siunin', 'stignin', 'sigain',
                          'signlin', 'sivgnin', 'sbignin', 'cignin', 'svignin', 'sipgnin', 'yignin', 'jignin',
                          'nsignin', 'signan', 'signvn', 'sigzin', 'rsignin', 'signiv', 'signinm', 'signrn', 'simgnin',
                          'signiln', 'signmin', 'signon', 'sigznin', 'sigmnin', 'signyn', 'scignin', 'slignin',
                          'signimn', 'simnin', 'sngnin', 'sigonin', 'sirnin', 'asignin', 'sikgnin', 'sibnin', 'signinj',
                          'signid', 'isignin', 'sitgnin', 'signnn', 'sigxin', 'segnin', 'signinb', 'silnin', 'signiwn',
                          'siqgnin', 'siganin', 'usignin', 'silgnin', 'signind', 'signit', 'qsignin', 'signih',
                          'signiw', 'signisn', 'signicn', 'signing', 'siguin', 'esignin', 'sigdin', 'fignin', 'signinr',
                          'siggnin', 'signine', 'signim', 'sigfnin', 'signip', 'sigsin', 'signif', 'signidn', 'singnin',
                          'signrin', 'sggnin', 'sigwnin', 'sigqnin', 'signivn', 'saignin', 'uignin', 'sdgnin', 'signik',
                          'signxn', 'siglin', 'seignin', 'pignin', 'sjignin', 'sygnin', 'soignin', 'signun', 'signikn',
                          'signina', 'wsignin', 'signfin', 'sigxnin', 'rignin', 'szgnin', 'signinp', 'sigfin',
                          'signhin', 'sidnin', 'srignin', 'signink', 'shgnin', 'signwin', 'zsignin', 'signain',
                          'sigsnin', 'scgnin', 'sigpin', 'sigunin', 'sigcin', 'siginin', 'signian', 'sigknin', 'kignin',
                          'sifgnin', 'skgnin', 'iignin', 'psignin', 'signion', 'signtn', 'sgignin', 'fsignin', 's7gnin',
                          's8gnin', 's9gnin', 's&gnin', 's*gnin', 's(gnin', 'sig,in', 'sig<in', 'sign7n', 'sign8n',
                          'sign9n', 'sign&n', 'sign*n', 'sign(n', 'signi,', 'signi<', 'signjup', 'sinup', 'sigunp',
                          'signupv', 'ignup', 'signups', 'sipgnup', 'vignup', 'sigxup', 'signpu', 'sgnup', 'sigkup',
                          'siganup', 'signp', 'singup', 'signus', 'signu', 'sginup', 'sitnup', 'signcp', 'signdp',
                          'swgnup', 'sqgnup', 'isgnup', 'signuzp', 'signqup', 'signupm', 'sigup', 'sienup', 'signupp',
                          'saignup', 'mignup', 'signuop', 'sigjup', 'signupz', 'signupw', 'sixgnup', 'sigfnup',
                          'sisnup', 'signupy', 'sigcup', 'szignup', 'sigwnup', 'siagnup', 'signkp', 'sigrnup',
                          'sikgnup', 'sbgnup', 'jignup', 'signuqp', 'signucp', 'sgignup', 'signuap', 'sidnup', 'zignup',
                          'signufp', 'sigoup', 'signpup', 'sigpnup', 'eignup', 'sagnup', 'xsignup', 'lignup', 'signuk',
                          'signuv', 'signuq', 'sianup', 'sixnup', 'usignup', 'rsignup', 'wsignup', 'siugnup', 'scgnup',
                          'sigtup', 'signhp', 'signfp', 'signupk', 'sigyup', 'signrup', 'sirgnup', 'bsignup', 'sionup',
                          'shgnup', 'sigynup', 'signup', 'sigmup', 'signuxp', 'signupt', 'sigqnup', 'siognup', 'sigdup',
                          'gignup', 'siggup', 'signuup', 'signugp', 'sygnup', 'sifnup', 'sdgnup', 'signupx', 'sugnup',
                          'rignup', 'signupu', 'esignup', 'signukp', 'signupe', 'ssignup', 'sigwup', 'sigunup',
                          'signubp', 'siqnup', 'signux', 'pignup', 'slignup', 'siinup', 'srgnup', 'signujp', 'signudp',
                          'sdignup', 'sigsnup', 'swignup', 'cignup', 'simgnup', 'signud', 'sihnup', 'signupa', 'sibnup',
                          'signvup', 'iignup', 'signupd', 'sigvnup', 'slgnup', 'signsup', 'sbignup', 'sihgnup',
                          'spignup', 'signuhp', 'signuep', 'bignup', 'signupj', 'sigaup', 'signupf', 'signjp', 'sngnup',
                          'qignup', 'wignup', 'simnup', 'nignup', 'signgup', 'sinnup', 'aignup', 'siignup', 'signul',
                          'signxup', 'signum', 'signaup', 'signrp', 'seignup', 'svignup', 'signzup', 'signfup',
                          'siguup', 'signap', 'signnp', 'sigiup', 'csignup', 'sighup', 'sivgnup', 'siunup', 'signupc',
                          'sigjnup', 'sirnup', 'signep', 'gsignup', 'sjignup', 'signutp', 'sigenup', 'sipnup', 'signop',
                          'sigknup', 'sigcnup', 'siynup', 'signgp', 'sigqup', 'signxp', 'signbup', 'smignup', 'signub',
                          'signuh', 'smgnup', 'signmp', 'signyup', 'signnup', 'sijgnup', 'xignup', 'signupi', 'dsignup',
                          'sognup', 'siglup', 'signsp', 'psignup', 'syignup', 'stgnup', 'soignup', 'signuy', 'signunp',
                          'skgnup', 'sicgnup', 'signcup', 'signupo', 'signua', 'siggnup', 'segnup', 'sigfup', 'sigvup',
                          'sitgnup', 'signpp', 'signhup', 'signuwp', 'scignup', 'hignup', 'sigeup', 'siginup', 'sigsup',
                          'sicnup', 'sqignup', 'signurp', 'siznup', 'siknup', 'srignup', 'siqgnup', 'sigrup', 'sighnup',
                          'sizgnup', 'signuip', 'kignup', 'ssgnup', 'msignup', 'svgnup', 'szgnup', 'oignup', 'yignup',
                          'signuc', 'signiup', 'silnup', 'signuyp', 'signqp', 'zsignup', 'shignup', 'sidgnup', 'signlp',
                          'signlup', 'signupr', 'hsignup', 'tsignup', 'sigpup', 'signuf', 'sigbnup', 'signvp',
                          'sxignup', 'signdup', 'lsignup', 'signuz', 'signtp', 'signwp', 'signui', 'sfignup', 'skignup',
                          'stignup', 'fsignup', 'signbp', 'siygnup', 'osignup', 'signusp', 'signupg', 'signwup',
                          'suignup', 'sigxnup', 'sijnup', 'signue', 'sigtnup', 'signzp', 'uignup', 'sigzup', 'singnup',
                          'signuj', 'signupq', 'sibgnup', 'nsignup', 'signuo', 'ksignup', 'sigonup', 'siglnup',
                          'signulp', 'signug', 'sigmnup', 'signuvp', 'siegnup', 'sxgnup', 'jsignup', 'sigdnup',
                          'signump', 'tignup', 'signuph', 'fignup', 'sigbup', 'signyp', 'signeup', 'dignup', 'signupl',
                          'signmup', 'sggnup', 'silgnup', 'isignup', 'signupb', 'sjgnup', 'signur', 'sivnup', 'snignup',
                          'signuw', 'asignup', 'sfgnup', 'signupn', 'siwgnup', 'siwnup', 'vsignup', 'ysignup', 'signuu',
                          'sifgnup', 'signtup', 'spgnup', 'qsignup', 'sigznup', 'sisgnup', 'signkup', 's7gnup',
                          's8gnup', 's9gnup', 's&gnup', 's*gnup', 's(gnup', 'sig,up', 'sig<up', 'sign6p', 'sign7p',
                          'sign8p', 'sign^p', 'sign&p', 'sign*p', 'signu9', 'signu0', 'signu-', 'signu[', 'signu]',
                          'signu;', 'signu(', 'signu)', 'signu_', 'signu=', 'signu+', 'signu{', 'signu}', 'signu:',
                          '/signin', '/signup'],
                 extras={'emoji': "keycard", 'args': {
                     'generic.meta.args.authcode': ['auth.slash.token', True]},
                         "dev": False, "description_keys": ['auth.meta.description1', 'auth.meta.description2',
                                                            ['auth.meta.description3',
                                                             'https://www.epicgames.com/id/login?redirectUrl=https%3A%2F%2Fwww.epicgames.com%2Fid%2Fapi%2Fredirect%3FclientId%3Dec684b8c687f479fadea3cb2ad83f5c6%26responseType%3Dcode'],
                                                            'auth.meta.description4',
                                                            ['auth.meta.description5', '<@mention_me> auth'],
                                                            'auth.meta.description6', 'auth.meta.description7',
                                                            'auth.meta.description8',
                                                            ['auth.meta.description9',
                                                             '<@mention_me> auth a51c1f4d35b1457c8e34a1f6026faa35'],
                                                            ['auth.meta.description10', '💡'],
                                                            ['auth.meta.description11', '<@mention_me> device'],
                                                            'auth.meta.description12'],
                         "name_key": "auth.slash.name"},
                 brief="auth.slash.description",
                 description='{0}\n{1}\n\u200b\n⦾ {2}\n⦾ {3}\n⦾ {4}\n⦾ {5}\n⦾ {6}\n{7}\n\n```json\n{'
                             '"redirectUrl":"https://accounts.epicgames.com/fnauth?code'
                             '=a51c1f4d35b1457c8e34a1f6026faa35","sid":null})```\n{8}\n{9}\n⦾ {10}\n⦾ {11}')
    async def auth(self, ctx, token=''):
        """
        This function is the entry point for the auth command when called traditionally

        Args:
            ctx: The context of the command
            token: The authcode to use for authentication
        """
        await self.auth_command(ctx, token)

    @ext.command(name='kill',
                 aliases=['koll', 'ki9ll', 'imakillyou', 'k8ll', 'kkll', 'mkill', 'kuill', 'end', 'oill', 'kjill',
                          'k8ill', 'k9ill', 'bai', 'keel-over-and-dieill', 'jill', 'kiol', 'klill', 'kil', 'ikll',
                          'kikll', 'kipl', 'kilk', 'okill', 'klll', 'kilkl', 'kilol', 'kipll', 'ikill', 'lkill',
                          'kilpl', 'mill', 'bye', 'kjll', 'koill', 'baibai', 'killk', 'kilo', 'k9ll', 'kkill', 'killl',
                          'killo', 'kll', 'killp', 'kikl', 'kioll', 'iill', 'kull', 'jkill', 'kmill', 'klil', '🔪',
                          'kiull', 'kiill', 'lill', 'kijll', 'kilp', 'ki8ll', 'logout', 'logoff', '/logout', '/logoff',
                          '/kill', 'nd', 'ed', 'en', 'eend', 'ennd', 'endd', 'ned', 'edn', 'wnd', '3nd', '4nd', 'rnd',
                          'fnd', 'dnd', 'snd', 'ebd', 'ehd', 'ejd', 'emd', 'ens', 'ene', 'enr', 'enf', 'enc', 'enx',
                          'wend', 'ewnd', '3end', 'e3nd', '4end', 'e4nd', 'rend', 'ernd', 'fend', 'efnd', 'dend',
                          'ednd', 'send', 'esnd', 'ebnd', 'enbd', 'ehnd', 'enhd', 'ejnd', 'enjd', 'emnd', 'enmd',
                          'ensd', 'ends', 'ened', 'ende', 'enrd', 'endr', 'enfd', 'endf', 'encd', 'endc', 'enxd',
                          'endx', 'ogout', 'lgout', 'loout', 'logut', 'logot', 'logou', 'llogout', 'loogout', 'loggout',
                          'logoout', 'logouut', 'logoutt', 'olgout', 'lgoout', 'loogut', 'loguot', 'logotu', 'kogout',
                          'oogout', 'pogout', 'ligout', 'l9gout', 'l0gout', 'lpgout', 'llgout', 'lkgout', 'lofout',
                          'lotout', 'loyout', 'lohout', 'lobout', 'lovout', 'logiut', 'log9ut', 'log0ut', 'logput',
                          'loglut', 'logkut', 'logoyt', 'logo7t', 'logo8t', 'logoit', 'logokt', 'logojt', 'logoht',
                          'logour', 'logou5', 'logou6', 'logouy', 'logouh', 'logoug', 'logouf', 'klogout', 'lkogout',
                          'ologout', 'plogout', 'lpogout', 'liogout', 'loigout', 'l9ogout', 'lo9gout', 'l0ogout',
                          'lo0gout', 'lopgout', 'lolgout', 'lokgout', 'lofgout', 'logfout', 'lotgout', 'logtout',
                          'loygout', 'logyout', 'lohgout', 'loghout', 'lobgout', 'logbout', 'lovgout', 'logvout',
                          'logiout', 'logoiut', 'log9out', 'logo9ut', 'log0out', 'logo0ut', 'logpout', 'logoput',
                          'loglout', 'logolut', 'logkout', 'logokut', 'logoyut', 'logouyt', 'logo7ut', 'logou7t',
                          'logo8ut', 'logou8t', 'logouit', 'logoukt', 'logojut', 'logoujt', 'logohut', 'logouht',
                          'logourt', 'logoutr', 'logou5t', 'logout5', 'logou6t', 'logout6', 'logouty', 'logouth',
                          'logougt', 'logoutg', 'logouft', 'logoutf', '.logout', '/end', 'welp', 'kys', 'kms',
                          'doodmaak', 'قتل', 'হত্যা', 'matar', 'zabít', 'dræb', 'σκοτώνω', 'tappa', 'کشتن', 'tappaa',
                          'મારવા', 'kashe', 'לַהֲרוֹג', 'मारना', 'megöl', '殺す', 'nužudyti', 'nogalināt', 'मारणे',
                          'bunuh', 'ਮਾਰਨਾ', 'ucide', 'zabiť', 'убити', 'kuua', 'கொல்ல', 'చంపేస్తాయి', 'öldürmek',
                          'مار ڈالو', '杀', '殺', 'مارڈالو', 'ill', 'kwll', 'kilj', 'kdll', 'fill', 'ykill', 'kilg',
                          'kilb', 'fkill', 'killy', 'kilsl', 'kfll', 'krill', 'killc', 'kilhl', 'kild', 'tkill', 'kile',
                          'kilrl', 'kpll', 'xill', 'kills', 'will', 'knll', 'sill', 'kizl', 'kgll', 'kbll', 'kilgl',
                          'kvill', 'kilt', 'ktill', 'kicll', 'killa', 'kily', 'kihl', 'kili', 'kilm', 'kiyl', 'kimll',
                          'kijl', 'ksll', 'hkill', 'vill', 'kxll', 'kgill', 'kivl', 'kixll', 'killv', 'pill', 'killd',
                          'killn', 'ukill', 'ekill', 'kixl', 'dkill', 'kifl', 'till', 'killi', 'kqill', 'killu', 'kilu',
                          'gill', 'kigll', 'aill', 'bill', 'kibll', 'kiqll', 'killr', 'killg', 'kildl', 'krll', 'yill',
                          'kiql', 'qkill', 'dill', 'kilfl', 'kitl', 'kisll', 'kigl', 'kinll', 'kilz', 'kilml', 'kizll',
                          'bkill', 'knill', 'killq', 'kxill', 'hill', 'keill', 'kiwl', 'kzll', 'kilzl', 'eill', 'kilf',
                          'kiljl', 'kilnl', 'ktll', 'kcll', 'khll', 'kyill', 'zill', 'kdill', 'kila', 'kilal', 'kcill',
                          'ksill', 'nill', 'ckill', 'kilil', 'kilcl', 'kiell', 'kiml', 'akill', 'kilv', 'kyll', 'kpill',
                          'killb', 'kitll', 'killw', 'kilw', 'kiwll', 'kqll', 'kifll', 'killm', 'kvll', 'killf', 'kiel',
                          'kaill', 'kial', 'killx', 'kmll', 'kell', 'qill', 'kzill', 'kirl', 'kilh', 'killt', 'kiyll',
                          'pkill', 'kilul', 'kirll', 'kilql', 'kilxl', 'kiltl', 'kbill', 'kibl', 'kwill', 'skill',
                          'vkill', 'kiln', 'kilc', 'kinl', 'killj', 'wkill', 'kiul', 'kilyl', 'kiil', 'kisl', 'uill',
                          'kall', 'kilx', 'kicl', 'kilbl', 'kils', 'rkill', 'kilq', 'gkill', 'killz', 'xkill', 'kivll',
                          'kilwl', 'kilvl', 'kidll', 'kidl', 'nkill', 'kilr', 'kille', 'khill', 'zkill', 'kilel',
                          'rill', 'kihll', 'kiall', 'kfill', 'killh', 'cill', '.ill', ',ill', '>ill', '<ill', 'k7ll',
                          'k&ll', 'k*ll', 'k(ll', 'ki;l', 'ki/l', 'ki.l', 'ki,l', 'ki?l', 'ki>l', 'ki<l', 'kil;',
                          'kil/', 'kil.', 'kil,', 'kil?', 'kil>', 'kil<', 'enl', 'aend', 'ond', 'epd', 'efd', 'nend',
                          'eand', 'eny', 'eyd', 'ead', 'enn', 'ekd', 'enh', 'mnd', 'ewd', 'ecd', 'endb', 'nnd', 'enpd',
                          'jend', 'enj', 'kend', 'eqd', 'eknd', 'enld', 'enq', 'elnd', 'endn', 'endy', 'xnd', 'tend',
                          'eng', 'enm', 'edd', 'gend', 'eond', 'endw', 'enud', 'evd', 'lnd', 'enp', 'ena', 'eni', 'eud',
                          'endu', 'endm', 'endt', 'vnd', 'endp', 'zend', 'etd', 'eod', 'qnd', 'jnd', 'ezd',
                          'lend', 'ent', 'enkd', 'endg', 'envd', 'eqnd', 'and', 'knd', 'hnd', 'eid', 'eld', 'endk',
                          'enyd', 'und', 'etnd', 'enod', 'qend', 'endl', 'enb', 'exd', 'engd', 'endq', 'endj', 'enwd',
                          'entd', 'pend', 'ecnd', 'eynd', 'endi', 'eznd', 'uend', 'oend', 'bnd', 'epnd',
                          'enk', 'tnd', 'endz', 'eno', 'ynd', 'enu', 'esd', 'eund', 'exnd', 'enzd', 'iend',
                          'znd', 'enda', 'enid', 'xend', 'egd', 'endo', 'gnd', 'vend', 'yend', 'egnd', 'endh',
                          'cend', 'hend', 'bend', 'enqd', 'mend', 'evnd', 'erd', 'enz', 'pnd', 'endv', 'eind', 'enad',
                          '2nd', '$nd', '#nd', '@nd', 'e,d', 'e<d', 'lfogout', 'logoutp', 'logoutw', 'qogout', 'yogout',
                          'logouj', 'logouc', 'logoct', 'wogout', 'lomgout', 'logouto', 'lozgout', 'logoub', 'logowut',
                          'logqut', 'logoeut', 'lbgout', 'locgout', 'lokout', 'logoult', 'logouk', 'ltgout', 'logjout',
                          'logouts', 'logoutu', 'logont', 'lonout', 'logoutd', 'eogout', 'logzout', 'loqout', 'lmogout',
                          'ilogout', 'lsogout', 'logoutm', 'logvut', 'logous', 'iogout', 'togout', 'logrout', 'lyogout',
                          'logoet', 'loiout', 'logonut', 'logouo', 'logfut', 'logdout', 'logoqt', 'mlogout', 'logdut',
                          'logorut', 'logost', 'lmgout', 'logozt', 'logouti', 'lgogout', 'lhogout', 'ltogout',
                          'logoutb', 'logomt', 'laogout', 'wlogout', 'logoqut', 'logoutl', 'logouq', 'lagout',
                          'lzogout', 'logolt', 'lzgout', 'lorgout', 'logoum', 'logoun', 'logxout', 'logjut', 'lbogout',
                          'loxgout', 'logogt', 'logoutj', 'logouot', 'ldogout', 'logouu', 'logoue', 'logzut', 'lsgout',
                          'ljogout', 'blogout', 'logeut', 'logoot', 'logtut', 'lcogout', 'ljgout', 'hogout', 'lougout',
                          'loaout', 'loxout', 'logoutn', 'lqgout', 'longout', 'logoat', 'logwut', 'logouta', 'logouvt',
                          'lojout', 'lnogout', 'louout', 'logmout', 'loagout', 'logoust', 'rlogout', 'hlogout',
                          'lojgout', 'logaout', 'ylogout', 'nogout', 'logoumt', 'logrut', 'lognout', 'alogout',
                          'loggut', 'xlogout', 'lxgout', 'logoxut', 'leogout', 'logouqt', 'logodt', 'logxut', 'logoux',
                          'losgout', 'dogout', 'logouw', 'zogout', 'logovt', 'logoutx', 'logocut', 'mogout', 'logouxt',
                          'elogout', 'lowout', 'lomout', 'lwgout', 'logoutq', 'bogout', 'logott', 'logotut', 'uogout',
                          'lngout', 'logouz', 'logoup', 'logouet', 'dlogout', 'nlogout', 'logount', 'qlogout',
                          'logoute', 'logoutv', 'cogout', 'logeout', 'logoui', 'lhgout', 'lodgout', 'logozut', 'aogout',
                          'lopout', 'lygout', 'tlogout', 'loguut', 'logodut', 'logwout', 'lvogout', 'ulogout', 'logmut',
                          'clogout', 'lodout', 'logouv', 'legout', 'glogout', 'logoxt', 'logoft', 'loeout', 'lvgout',
                          'loguout', 'logort', 'vogout', 'lognut', 'logsut', 'logoaut', 'logoutk', 'lorout', 'logcout',
                          'zlogout', 'lolout', 'lqogout', 'logogut', 'logobt', 'logoud', 'loegout', 'logoul', 'logcut',
                          'xogout', 'lwogout', 'logoubt', 'logouwt', 'locout', 'logobut', 'loghut', 'jogout', 'slogout',
                          'lrgout', 'logaut', 'lcgout', 'logoua', 'flogout', 'lowgout', 'looout', 'gogout', 'lozout',
                          'logoutz', 'losout', 'fogout', 'vlogout', 'logosut', 'logoudt', 'logbut', 'logovut',
                          'luogout', 'logopt', 'lrogout', 'rogout', 'jlogout', 'logowt', 'logqout', 'logyut', 'sogout',
                          'logoutc', 'logouat', 'logoupt', 'lfgout', 'logsout', 'lugout', 'logouct', 'lggout',
                          'logofut', 'loqgout', 'ldgout', 'logouzt', 'logomut', 'lxogout', ';ogout', '/ogout', '.ogout',
                          ',ogout', '?ogout', '>ogout', '<ogout', 'l8gout', 'l;gout', 'l*gout', 'l(gout', 'l)gout',
                          'log8ut', 'log;ut', 'log*ut', 'log(ut', 'log)ut', 'logo6t', 'logo^t', 'logo&t', 'logo*t',
                          'logou4', 'logou$', 'logou%', 'logou^', 'signou', 'sinout', 'signouqt', 'sigout', 'shignout',
                          'sgnout',
                          'singout', 'sienout', 'signhout', 'jignout', 'sigmout', 'signoutc', 'signort', 'ignout',
                          'isgnout', 'signfut', 'sigxout', 'signouti', 'sigonut', 'signut', 'sginout', 'signojut',
                          'signoutk', 'signot', 'bignout', 'cignout', 'fignout', 'signqout', 'eignout', 'signorut',
                          'signouz', 'signofut', 'signourt', 'stignout', 'sihnout', 'signotu', 'sqignout', 'siggnout',
                          'lsignout', 'sgignout', 'wignout', 'ssignout', 'oignout', 'saignout', 'signout', 'signowt',
                          'signtut', 'sibnout', 'siagnout', 'smgnout', 'sitnout', 'stgnout', 'msignout', 'signuot',
                          'silnout', 'lignout', 'signput', 'signokut', 'sijgnout', 'signvout', 'signcut', 'skgnout',
                          'sfgnout', 'signouq', 'signlut', 'siwnout', 'signmout', 'sivnout', 'suignout', 'qignout',
                          'nsignout', 'sigynout', 'signoup', 'sxgnout', 'signouut', 'mignout', 'nignout', 'sigbout',
                          'signopt', 'wsignout', 'sbgnout', 'sipgnout', 'sigsout', 'sognout', 'signouyt', 'zsignout',
                          'sjignout', 'signoum', 'signoujt', 'vignout', 'spgnout', 'rsignout', 'signouit', 'signouh',
                          'sicgnout', 'sngnout', 'tignout', 'siguout', 'gignout', 'sizgnout', 'signoyt', 'sisgnout',
                          'signouet', 'srignout', 'fsignout', 'sigfout', 'siglout', 'snignout', 'sigpnout', 'signoutx',
                          'signoutt', 'signoutq', 'signoaut', 'dsignout', 'sigvout', 'signoat', 'sigqout', 'tsignout',
                          'szignout', 'sibgnout', 'sigdnout', 'signoout', 'signouc', 'signsut', 'sirnout', 'siignout',
                          'siynout', 'signobut', 'siunout', 'sigpout', 'sigoout', 'sigenout', 'esignout', 'sigxnout',
                          'signnut', 'sigyout', 'signoqut', 'sidnout', 'sigmnout', 'sygnout', 'siknout', 'signouth',
                          'signoput', 'siznout', 'signaut', 'isignout', 'sifgnout', 'sjgnout', 'sqgnout', 'signiut',
                          'signoutw', 'bsignout', 'signouj', 'signouy', 'signoue', 'gsignout', 'signoukt', 'signoupt',
                          'simgnout', 'sighout', 'signoutl', 'seignout', 'signuout', 'signouvt', 'signwout', 'signeout',
                          'sigvnout', 'signqut', 'ssgnout', 'silgnout', 'sitgnout', 'qsignout', 'signoutu', 'signoutz',
                          'signovt', 'signodt', 'signoutv', 'signrut', 'sighnout', 'signouzt', 'hignout', 'sigwout',
                          'signoutg', 'sipnout', 'signoet', 'sigaout', 'signrout', 'sikgnout', 'signoutp', 'signouf',
                          'slignout', 'signoeut', 'usignout', 'vsignout', 'siqgnout', 'signuut', 'sigcnout', 'sfignout',
                          'szgnout', 'sigwnout', 'signoht', 'signsout', 'signozt', 'signouv', 'siygnout', 'srgnout',
                          'signomt', 'siginout', 'sbignout', 'signovut', 'signoxt', 'signowut', 'siggout', 'signoust',
                          'signouat', 'sigznout', 'signfout', 'signkout', 'signouk', 'signougt', 'signogt', 'signoit',
                          'signohut', 'sianout', 'signouty', 'sionout', 'sigbnout', 'signous', 'signoutd', 'iignout',
                          'sigzout', 'kignout', 'signodut', 'sigqnout', 'siganout', 'signgut', 'swgnout', 'signouxt',
                          'signoutb', 'signoutj', 'zignout', 'sugnout', 'yignout', 'signoct', 'rignout', 'sigcout',
                          'scgnout', 'signour', 'uignout', 'siinout', 'siglnout', 'signvut', 'signeut', 'svgnout',
                          'signokt', 'sagnout', 'signost', 'ksignout', 'signouot', 'signcout', 'signoot', 'signbut',
                          'signoutn', 'signoug', 'sigtout', 'signojt', 'sigfnout', 'signoun', 'sdignout', 'smignout',
                          'signoub', 'signouw', 'soignout', 'dignout', 'signjout', 'signtout', 'signouo', 'siugnout',
                          'signolt', 'asignout', 'signoult', 'sirgnout', 'signoua', 'signyout', 'signoxut', 'sixnout',
                          'signoumt', 'signoutr', 'sigonout', 'signouct', 'signosut', 'signouwt', 'swignout', 'sggnout',
                          'signobt', 'scignout', 'signott', 'osignout', 'signzout', 'sigrnout', 'sixgnout', 'signoqt',
                          'signoui', 'signoudt', 'slgnout', 'signoyut', 'signouts', 'siwgnout', 'aignout', 'sigrout',
                          'sisnout', 'svignout', 'signouta', 'sigiout', 'signoubt', 'psignout', 'pignout', 'sigdout',
                          'signdut', 'sigeout', 'signoutf', 'ysignout', 'signaout', 'shgnout', 'simnout', 'signouu',
                          'signjut', 'signdout', 'sigknout', 'sidgnout', 'signhut', 'siqnout', 'signomut', 'signoiut',
                          'signouht', 'xignout', 'sigjnout', 'signount', 'signwut', 'signocut', 'signoutm', 'signgout',
                          'sifnout', 'siegnout', 'sicnout', 'siognout', 'sdgnout', 'signyut', 'singnout', 'signzut',
                          'sivgnout', 'sijnout', 'signbout', 'sigkout', 'signoute', 'spignout', 'sigsnout', 'signoft',
                          'signonut', 'signoud', 'sinnout', 'skignout', 'sigtnout', 'signouft', 'signiout', 'jsignout',
                          'csignout', 'xsignout', 'signmut', 'signont', 'signogut', 'signnout', 'sxignout', 'sihgnout',
                          'segnout', 'signolut', 'signkut', 'signouto', 'sigjout', 'signoux', 'signlout', 'signxout',
                          'hsignout', 'signxut', 'signpout', 'syignout', 'sigunout', 'signotut', 'signoul', 'signozut',
                          's7gnout', 's8gnout', 's9gnout', 's&gnout', 's*gnout', 's(gnout', 'sig,out', 'sig<out',
                          'sign8ut', 'sign9ut', 'sign0ut', 'sign;ut', 'sign*ut', 'sign(ut', 'sign)ut', 'signo6t',
                          'signo7t', 'signo8t', 'signo^t', 'signo&t', 'signo*t', 'signou4', 'signou5', 'signou6',
                          'signou$', 'signou%', 'signou^', 'rmeove', 'recove', 'remov', 'remoev', 'pemove', 'jemove',
                          'removek', 'semove', 'remve', 'removeq', 'rnemove', 'emove', 'removue', 'reeove', 'remvve',
                          'remove', 'remoe', 'remoxve', 'rmove', 'reove', 'removhe', 'remvoe', 'removy', 'cremove',
                          'removt', 'remmove', 'removxe', 'removeo', 'reomve', 'rembve', 'remoxe', 'memove', 'rejove',
                          'remova', 'ruemove', 'resmove', 'ermove', 'reoove', 'remrve', 'remvove', 'remodve', 'zremove',
                          'femove', 'vremove', 'aemove', 'qemove', 'refmove', 'remorve', 'revmove', 'removx', 'rhemove',
                          'removej', 'removex', 'uremove', 'remope', 'rewmove', 'remyove', 'resove', 'remojve',
                          'iemove', 'remote', 'remonve', 'remmve', 'rkmove', 'remnve', 'remhove', 'removye', 'removep',
                          'jremove', 'wremove', 'removs', 'remowe', 'removei', 'reimove', 'removae', 'remoee', 'rumove',
                          'removke', 'remoze', 'rrmove', 'removc', 'remdove', 'reomove', 'roemove', 'remsve', 'rqmove',
                          'removee', 'remrove', 'remoave', 'renmove', 'xemove', 'rmemove', 'removoe', 'remaove',
                          'removz', 'lemove', 'rempove', 'removet', 'remoove', 'wemove', 'remone', 'removge', 'reymove',
                          'reemove', 'removw', 'rmmove', 'rezmove', 'rcemove', 'remogve', 'remjve', 'removu', 'yemove',
                          'remover', 'remotve', 'remqove', 'nremove', 'gemove', 'remoce', 'remofve', 'remuove',
                          'rdemove', 'remopve', 'rermove', 'premove', 'rwmove', 'reamove', 'removem', 'rtmove',
                          'relmove', 'remocve', 'rpmove', 'removr', 'reumove', 'remgove', 'remoge', 'rzemove', 'rzmove',
                          'reqove', 'removne', 'rwemove', 'redove', 'remxve', 'remokve', 'rjemove', 'rejmove',
                          'redmove', 'rfmove', 'remoye', 'rerove', 'kemove', 'removv', 'remlve', 'removel', 'remofe',
                          'temove', 'remdve', 'rdmove', 'retmove', 'yremove', 'ramove', 'rembove', 'renove', 'remobve',
                          'remozve', 'rbemove', 'remtove', 'sremove', 'rexmove', 'rqemove', 'rlmove', 'removqe',
                          'uemove', 'kremove', 'removie', 'hemove', 'bemove', 'removl', 'remouve', 'removes', 'remoqe',
                          'rewove', 'rebmove', 'repove', 'reaove', 'nemove', 'revove', 'rhmove', 'remome', 'reyove',
                          'rymove', 'remoie', 'cemove', 'remohve', 'recmove', 'remnove', 'remolve', 'removce',
                          'removve', 'remoke', 'remzove', 'remive', 'rremove', 'removpe', 'remxove', 'removre',
                          'rsemove', 'remore', 'remeove', 'aremove', 'remeve', 'vemove', 'rpemove', 'reuove', 'rebove',
                          'removo', 'remoae', 'regove', 'removef', 'remoje', 'lremove', 'remgve', 'oemove', 'rezove',
                          'relove', 'remjove', 'removbe', 'repmove', 'rnmove', 'removd', 'remoeve', 'removev', 'remhve',
                          'rlemove', 'reqmove', 'fremove', 'retove', 'rehmove', 'removle', 'removf', 'remlove',
                          'rbmove', 'rcmove', 'remcove', 'gremove', 'remoive', 'remose', 'demove', 'tremove', 'xremove',
                          'zemove', 'removed', 'remoyve', 'removje', 'remqve', 'ryemove', 'remomve', 'removj', 'refove',
                          'remfve', 'eremove', 'removeh', 'removn', 'removea', 'rvemove', 'remzve', 'removp', 'remsove',
                          'remave', 'removh', 'remyve', 'rekmove', 'rjmove', 'hremove', 'removze', 'removen', 'remcve',
                          'riemove', 'removeu', 'rexove', 'rxemove', 'removec', 'remohe', 'removeb', 'removq', 'eemove',
                          'remode', 'regmove', 'remwove', 'removi', 'removk', 'qremove', 'removez', 'removwe', 'removm',
                          'rgmove', 'removde', 'raemove', 'romove', 'rtemove', 'remkove', 'reiove', 'remwve', 'remowve',
                          'removse', 'rfemove', 'bremove', 'rekove', 'rimove', 'remole', 'dremove', 'removeg',
                          'remiove', 'removte', 'removg', 'mremove', 'remtve', 'remobe', 'remfove', 'remosve',
                          'remoqve', 'rxmove', 'remuve', 'rvmove', 'remkve', 'removfe', 'rempve', 'iremove', 'remooe',
                          'removb', 'remoue', 'rgemove', 'rkemove', 'removew', 'rsmove', 'removey', 'removme', 'rehove',
                          'oremove', '3emove', '4emove', '5emove', '#emove', '$emove', '%emove', 'r4move', 'r3move',
                          'r2move', 'r$move', 'r#move', 'r@move', 're,ove', 're<ove', 'rem8ve', 'rem9ve', 'rem0ve',
                          'rem;ve', 'rem*ve', 'rem(ve', 'rem)ve', 'remov4', 'remov3', 'remov2', 'remov$', 'remov#',
                          'remov@', '/skull', '/signout', '/remove'],
                 extras={'emoji': "detonate", "args": {}, "dev": False,
                         "description_keys": ['auth.kill.meta.description1', 'auth.kill.meta.description2'],
                         "name_key": "auth.kill.slash.name"},
                 brief="auth.kill.slash.description",
                 description="{0}\n{1}")
    async def kill(self, ctx):
        """
        This function is the entry point for the kill command when called traditionally

        Args:
            ctx: The context of the command
        """
        await self.kill_command(ctx)

    @slash_command(name='auth', name_localizations=stw.I18n.construct_slash_dict("auth.slash.name"),
                   description='Login with your Epic Games authcode and start an authentication session',
                   description_localizations=stw.I18n.construct_slash_dict("auth.slash.description"),
                   guild_ids=stw.guild_ids)
    async def slashauth(self, ctx: discord.ApplicationContext,
                        token: Option(
                            description="Your Epic Games authcode. Leave this blank to get one",
                            description_localizations=stw.I18n.construct_slash_dict(
                                "auth.slash.token"),
                            name_localizations=stw.I18n.construct_slash_dict("generic.meta.args.token"),
                            min_length=32, default="") = ""):
        """
        This function is the entry point for the auth command when called via slash commands
        Args:
            ctx: The context of the command
            token: The authcode to use for authentication
        """
        await self.auth_command(ctx, token)

    @slash_command(name='kill', name_localizations=stw.I18n.construct_slash_dict("auth.kill.slash.name"),
                   description='End your active authentication session',
                   description_localizations=stw.I18n.construct_slash_dict("auth.kill.slash.description"),
                   guild_ids=stw.guild_ids)
    async def slashkill(self, ctx):
        """
        This function is the entry point for the kill command when called via slash commands

        Args:
            ctx: The context of the command
        """
        await self.kill_command(ctx)


def setup(client):
    """
    This function is called when the cog is loaded via load_extension

    Args:
        client: The bot client
    """
    client.add_cog(Auth(client))
