"""
STW Daily Discord bot Copyright 2023 by the STW Daily team.
Please do not skid our hard work.
https://github.com/dippyshere/stw-daily

This file is the cog for the how2 command. Displays the how to use embed + gif
"""

import discord
import discord.ext.commands as ext
from discord.commands import (  # Importing the decorator that makes slash commands.
    slash_command,
)

import stwutil as stw


# view for the invite command.
class HowToUseView(discord.ui.View):
    """
    discord UI View for the how to use command.
    """

    def __init__(self, client, author, ctx, desired_lang):
        super().__init__(timeout=None)
        self.client = client
        self.ctx = ctx
        self.author = author
        self.desired_lang = desired_lang

        self.add_item(discord.ui.Button(label=stw.I18n.get("how2.view.getcode", desired_lang),
                                        style=discord.ButtonStyle.link,
                                        url=self.client.config["login_links"]["login_fortnite_pc"],
                                        emoji=self.client.config["emojis"]["link_icon"]))
        self.add_item(discord.ui.Button(label=stw.I18n.get("how2.view.button.morehelp", desired_lang),
                                        style=discord.ButtonStyle.link,
                                        url="https://github.com/dippyshere/stw-daily/wiki",
                                        emoji=self.client.config["emojis"]["info"]))


class HowTo(ext.Cog):
    """
    The how to command.
    """

    def __init__(self, client):
        self.client = client
        self.emojis = client.config["emojis"]

    async def how_to_command(self, ctx):
        """
        The main function for the how to use command.

        Args:
            ctx: The context of the command.

        Returns:
            None
        """

        desired_lang = await stw.I18n.get_desired_lang(self.client, ctx)

        embed_colour = self.client.colours["generic_blue"]

        token_arg = stw.I18n.get("generic.meta.args.token", desired_lang)

        embed = discord.Embed(
            title=await stw.add_emoji_title(self.client, stw.I18n.get("how2.embed.title", desired_lang), "info"),
            description=f'\u200b\n{stw.I18n.get("how2.embed.description1", desired_lang, "https://github.com/dippyshere/stw-daily/wiki", "https://github.com/dippyshere/stw-daily/wiki")}\n'
                        f'\n{stw.I18n.get("how2.embed.description2", desired_lang)}\n'
                        f'{stw.I18n.get("how2.embed.description3", desired_lang, self.client.config["login_links"]["login_fortnite_pc"])}\n'
                        f'\n{stw.I18n.get("how2.embed.description4", desired_lang)}\n'
                        f'{stw.I18n.get("how2.embed.description5", desired_lang)}\n'
                        f'{stw.I18n.get("how2.embed.description6", desired_lang, "  •", f"</research:1080395214461620260> `{token_arg}`")}\n'
                        f'{stw.I18n.get("how2.embed.description6", desired_lang, "  •", f"<@757776996418715651> res `{token_arg}`")}\n'
                        f'\n{stw.I18n.get("how2.embed.description7", desired_lang)}\n'
                        f'*<@757776996418715651> `res a51c1f4d35b1457c8e34a1f6026faa35`*'
                        f'\n\u200b',
            color=embed_colour)

        embed = await stw.set_thumbnail(self.client, embed, "help")
        # embed = await stw.add_requested_footer(ctx, embed)
        embed = await stw.set_embed_image(embed, "https://cdn.discordapp.com/attachments/757768060810559541"
                                                 "/1050461779991474266/stw_daily_noob_tutorial_render_2_hd.gif")

        # # get channel from id
        # channel = self.client.get_channel(758561253156847629)
        # # get message from id
        # message = await channel.fetch_message(813715483928559656)
        # # edit message
        # await message.edit(embed=embed, view=HowToUseView(self.client, ctx.author, ctx))
        # # get channel from id
        # channel = self.client.get_channel(757768833946877992)
        # # get message from id
        # message = await channel.fetch_message(1050835103179341960)
        # # edit message
        # await message.edit(embed=embed, view=HowToUseView(self.client, ctx.author, ctx))
        # await ctx.channel.send(
        #     f"{ctx.author.mention} I've updated the how to use embed in <#758561253156847629> and <#757768833946877992>.")

        invite_view = HowToUseView(self.client, ctx.author, ctx, desired_lang)
        await stw.slash_send_embed(ctx, self.client, embed, invite_view)
        return

    @ext.command(name='how2',
                 aliases=['howto', 'howtouse', 'how2use', 'how2usebot', 'how2usestwdaily', 'howtousestwdaily',
                          'instruction', 'inst', '/how2', '/howto', '/howtouse', '/how2use', '/how2usebot',
                          '/instruction', '/inst', 'morehelp', 'plshelp', 'tutorial', '/tutorial', 'how', 'owto',
                          'hwto', 'hoto', 'howo', 'howt', 'hhowto', 'hoowto', 'howwto', 'howtto', 'howtoo', 'ohwto',
                          'hwoto', 'hotwo', 'howot', 'gowto', 'yowto', 'uowto', 'jowto', 'nowto', 'bowto', 'hiwto',
                          'h9wto', 'h0wto', 'hpwto', 'hlwto', 'hkwto', 'hoqto', 'ho2to', 'ho3to', 'hoeto', 'hodto',
                          'hosto', 'hoato', 'howro', 'how5o', 'how6o', 'howyo', 'howho', 'howgo', 'howfo', 'howti',
                          'howt9', 'howt0', 'howtp', 'howtl', 'howtk', 'ghowto', 'hgowto', 'yhowto', 'hyowto', 'uhowto',
                          'huowto', 'jhowto', 'hjowto', 'nhowto', 'hnowto', 'bhowto', 'hbowto', 'hiowto', 'hoiwto',
                          'h9owto', 'ho9wto', 'h0owto', 'ho0wto', 'hpowto', 'hopwto', 'hlowto', 'holwto', 'hkowto',
                          'hokwto', 'hoqwto', 'howqto', 'ho2wto', 'how2to', 'ho3wto', 'how3to', 'hoewto', 'howeto',
                          'hodwto', 'howdto', 'hoswto', 'howsto', 'hoawto', 'howato', 'howrto', 'howtro', 'how5to',
                          'howt5o', 'how6to', 'howt6o', 'howyto', 'howtyo', 'howhto', 'howtho', 'howgto', 'howtgo',
                          'howfto', 'howtfo', 'howtio', 'howtoi', 'howt9o', 'howto9', 'howt0o', 'howto0', 'howtpo',
                          'howtop', 'howtlo', 'howtol', 'howtko', 'howtok', 'owtouse', 'hwtouse', 'hotouse', 'howouse',
                          'howtuse', 'howtose', 'howtoue', 'howtous', 'hhowtouse', 'hoowtouse', 'howwtouse',
                          'howttouse', 'howtoouse', 'howtouuse', 'howtousse', 'howtousee', 'ohwtouse', 'hwotouse',
                          'hotwouse', 'howotuse', 'howtuose', 'howtosue', 'howtoues', 'gowtouse', 'yowtouse',
                          'uowtouse', 'jowtouse', 'nowtouse', 'bowtouse', 'hiwtouse', 'h9wtouse', 'h0wtouse',
                          'hpwtouse', 'hlwtouse', 'hkwtouse', 'hoqtouse', 'ho2touse', 'ho3touse', 'hoetouse',
                          'hodtouse', 'hostouse', 'hoatouse', 'howrouse', 'how5ouse', 'how6ouse', 'howyouse',
                          'howhouse', 'howgouse', 'howfouse', 'howtiuse', 'howt9use', 'howt0use', 'howtpuse',
                          'howtluse', 'howtkuse', 'howtoyse', 'howto7se', 'howto8se', 'howtoise', 'howtokse',
                          'howtojse', 'howtohse', 'howtouae', 'howtouwe', 'howtouee', 'howtoude', 'howtouxe',
                          'howtouze', 'howtousw', 'howtous3', 'howtous4', 'howtousr', 'howtousf', 'howtousd',
                          'howtouss', 'ghowtouse', 'hgowtouse', 'yhowtouse', 'hyowtouse', 'uhowtouse', 'huowtouse',
                          'jhowtouse', 'hjowtouse', 'nhowtouse', 'hnowtouse', 'bhowtouse', 'hbowtouse', 'hiowtouse',
                          'hoiwtouse', 'h9owtouse', 'ho9wtouse', 'h0owtouse', 'ho0wtouse', 'hpowtouse', 'hopwtouse',
                          'hlowtouse', 'holwtouse', 'hkowtouse', 'hokwtouse', 'hoqwtouse', 'howqtouse', 'ho2wtouse',
                          'how2touse', 'ho3wtouse', 'how3touse', 'hoewtouse', 'howetouse', 'hodwtouse', 'howdtouse',
                          'hoswtouse', 'howstouse', 'hoawtouse', 'howatouse', 'howrtouse', 'howtrouse', 'how5touse',
                          'howt5ouse', 'how6touse', 'howt6ouse', 'howytouse', 'howtyouse', 'howhtouse', 'howthouse',
                          'howgtouse', 'howtgouse', 'howftouse', 'howtfouse', 'howtiouse', 'howtoiuse', 'howt9ouse',
                          'howto9use', 'howt0ouse', 'howto0use', 'howtpouse', 'howtopuse', 'howtlouse', 'howtoluse',
                          'howtkouse', 'howtokuse', 'howtoyuse', 'howtouyse', 'howto7use', 'howtou7se', 'howto8use',
                          'howtou8se', 'howtouise', 'howtoukse', 'howtojuse', 'howtoujse', 'howtohuse', 'howtouhse',
                          'howtouase', 'howtousae', 'howtouwse', 'howtouswe', 'howtouese', 'howtoudse', 'howtousde',
                          'howtouxse', 'howtousxe', 'howtouzse', 'howtousze', 'howtousew', 'howtous3e', 'howtouse3',
                          'howtous4e', 'howtouse4', 'howtousre', 'howtouser', 'howtousfe', 'howtousef', 'howtoused',
                          'howtouses', 'ow2', 'hw2', 'ho2', 'hhow2', 'hoow2', 'howw2', 'how22', 'ohw2', 'hwo2', 'ho2w',
                          'gow2', 'yow2', 'uow2', 'jow2', 'now2', 'bow2', 'hiw2', 'h9w2', 'h0w2', 'hpw2', 'hlw2',
                          'hkw2', 'hoq2', 'ho22', 'ho32', 'hoe2', 'hod2', 'hos2', 'hoa2', 'ghow2', 'hgow2', 'yhow2',
                          'hyow2', 'uhow2', 'huow2', 'jhow2', 'hjow2', 'nhow2', 'hnow2', 'bhow2', 'hbow2', 'hiow2',
                          'hoiw2', 'h9ow2', 'ho9w2', 'h0ow2', 'ho0w2', 'hpow2', 'hopw2', 'hlow2', 'holw2', 'hkow2',
                          'hokw2', 'hoqw2', 'howq2', 'ho2w2', 'ho3w2', 'how32', 'hoew2', 'howe2', 'hodw2', 'howd2',
                          'hosw2', 'hows2', 'hoaw2', 'howa2', 'ow2use', 'hw2use', 'ho2use', 'howuse', 'how2se',
                          'how2ue', 'how2us', 'hhow2use', 'hoow2use', 'howw2use', 'how22use', 'how2uuse', 'how2usse',
                          'how2usee', 'ohw2use', 'hwo2use', 'ho2wuse', 'howu2se', 'how2sue', 'how2ues', 'gow2use',
                          'yow2use', 'uow2use', 'jow2use', 'now2use', 'bow2use', 'hiw2use', 'h9w2use', 'h0w2use',
                          'hpw2use', 'hlw2use', 'hkw2use', 'hoq2use', 'ho22use', 'ho32use', 'hoe2use', 'hod2use',
                          'hos2use', 'hoa2use', 'how2yse', 'how27se', 'how28se', 'how2ise', 'how2kse', 'how2jse',
                          'how2hse', 'how2uae', 'how2uwe', 'how2uee', 'how2ude', 'how2uxe', 'how2uze', 'how2usw',
                          'how2us3', 'how2us4', 'how2usr', 'how2usf', 'how2usd', 'how2uss', 'ghow2use', 'hgow2use',
                          'yhow2use', 'hyow2use', 'uhow2use', 'huow2use', 'jhow2use', 'hjow2use', 'nhow2use',
                          'hnow2use', 'bhow2use', 'hbow2use', 'hiow2use', 'hoiw2use', 'h9ow2use', 'ho9w2use',
                          'h0ow2use', 'ho0w2use', 'hpow2use', 'hopw2use', 'hlow2use', 'holw2use', 'hkow2use',
                          'hokw2use', 'hoqw2use', 'howq2use', 'ho2w2use', 'ho3w2use', 'how32use', 'hoew2use',
                          'howe2use', 'hodw2use', 'howd2use', 'hosw2use', 'hows2use', 'hoaw2use', 'howa2use',
                          'how2yuse', 'how2uyse', 'how27use', 'how2u7se', 'how28use', 'how2u8se', 'how2iuse',
                          'how2uise', 'how2kuse', 'how2ukse', 'how2juse', 'how2ujse', 'how2huse', 'how2uhse',
                          'how2uase', 'how2usae', 'how2uwse', 'how2uswe', 'how2uese', 'how2udse', 'how2usde',
                          'how2uxse', 'how2usxe', 'how2uzse', 'how2usze', 'how2usew', 'how2us3e', 'how2use3',
                          'how2us4e', 'how2use4', 'how2usre', 'how2user', 'how2usfe', 'how2usef', 'how2used',
                          'how2uses', 'owtousebot', 'hwtousebot', 'hotousebot', 'howousebot', 'howtusebot',
                          'howtosebot', 'howtouebot', 'howtousbot', 'howtouseot', 'howtousebt', 'howtousebo',
                          'hhowtousebot', 'hoowtousebot', 'howwtousebot', 'howttousebot', 'howtoousebot',
                          'howtouusebot', 'howtoussebot', 'howtouseebot', 'howtousebbot', 'howtouseboot',
                          'howtousebott', 'ohwtousebot', 'hwotousebot', 'hotwousebot', 'howotusebot', 'howtuosebot',
                          'howtosuebot', 'howtouesbot', 'howtousbeot', 'howtouseobt', 'howtousebto', 'gowtousebot',
                          'yowtousebot', 'uowtousebot', 'jowtousebot', 'nowtousebot', 'bowtousebot', 'hiwtousebot',
                          'h9wtousebot', 'h0wtousebot', 'hpwtousebot', 'hlwtousebot', 'hkwtousebot', 'hoqtousebot',
                          'ho2tousebot', 'ho3tousebot', 'hoetousebot', 'hodtousebot', 'hostousebot', 'hoatousebot',
                          'howrousebot', 'how5ousebot', 'how6ousebot', 'howyousebot', 'howhousebot', 'howgousebot',
                          'howfousebot', 'howtiusebot', 'howt9usebot', 'howt0usebot', 'howtpusebot', 'howtlusebot',
                          'howtkusebot', 'howtoysebot', 'howto7sebot', 'howto8sebot', 'howtoisebot', 'howtoksebot',
                          'howtojsebot', 'howtohsebot', 'howtouaebot', 'howtouwebot', 'howtoueebot', 'howtoudebot',
                          'howtouxebot', 'howtouzebot', 'howtouswbot', 'howtous3bot', 'howtous4bot', 'howtousrbot',
                          'howtousfbot', 'howtousdbot', 'howtoussbot', 'howtousevot', 'howtousegot', 'howtousehot',
                          'howtousenot', 'howtousebit', 'howtouseb9t', 'howtouseb0t', 'howtousebpt', 'howtouseblt',
                          'howtousebkt', 'howtousebor', 'howtousebo5', 'howtousebo6', 'howtouseboy', 'howtouseboh',
                          'howtousebog', 'howtousebof', 'ghowtousebot', 'hgowtousebot', 'yhowtousebot', 'hyowtousebot',
                          'uhowtousebot', 'huowtousebot', 'jhowtousebot', 'hjowtousebot', 'nhowtousebot',
                          'hnowtousebot', 'bhowtousebot', 'hbowtousebot', 'hiowtousebot', 'hoiwtousebot',
                          'h9owtousebot', 'ho9wtousebot', 'h0owtousebot', 'ho0wtousebot', 'hpowtousebot',
                          'hopwtousebot', 'hlowtousebot', 'holwtousebot', 'hkowtousebot', 'hokwtousebot',
                          'hoqwtousebot', 'howqtousebot', 'ho2wtousebot', 'how2tousebot', 'ho3wtousebot',
                          'how3tousebot', 'hoewtousebot', 'howetousebot', 'hodwtousebot', 'howdtousebot',
                          'hoswtousebot', 'howstousebot', 'hoawtousebot', 'howatousebot', 'howrtousebot',
                          'howtrousebot', 'how5tousebot', 'howt5ousebot', 'how6tousebot', 'howt6ousebot',
                          'howytousebot', 'howtyousebot', 'howhtousebot', 'howthousebot', 'howgtousebot',
                          'howtgousebot', 'howftousebot', 'howtfousebot', 'howtiousebot', 'howtoiusebot',
                          'howt9ousebot', 'howto9usebot', 'howt0ousebot', 'howto0usebot', 'howtpousebot',
                          'howtopusebot', 'howtlousebot', 'howtolusebot', 'howtkousebot', 'howtokusebot',
                          'howtoyusebot', 'howtouysebot', 'howto7usebot', 'howtou7sebot', 'howto8usebot',
                          'howtou8sebot', 'howtouisebot', 'howtouksebot', 'howtojusebot', 'howtoujsebot',
                          'howtohusebot', 'howtouhsebot', 'howtouasebot', 'howtousaebot', 'howtouwsebot',
                          'howtouswebot', 'howtouesebot', 'howtoudsebot', 'howtousdebot', 'howtouxsebot',
                          'howtousxebot', 'howtouzsebot', 'howtouszebot', 'howtousewbot', 'howtous3ebot',
                          'howtouse3bot', 'howtous4ebot', 'howtouse4bot', 'howtousrebot', 'howtouserbot',
                          'howtousfebot', 'howtousefbot', 'howtousedbot', 'howtousesbot', 'howtousevbot',
                          'howtousebvot', 'howtousegbot', 'howtousebgot', 'howtousehbot', 'howtousebhot',
                          'howtousenbot', 'howtousebnot', 'howtousebiot', 'howtouseboit', 'howtouseb9ot',
                          'howtousebo9t', 'howtouseb0ot', 'howtousebo0t', 'howtousebpot', 'howtousebopt',
                          'howtouseblot', 'howtousebolt', 'howtousebkot', 'howtousebokt', 'howtousebort',
                          'howtousebotr', 'howtousebo5t', 'howtousebot5', 'howtousebo6t', 'howtousebot6',
                          'howtouseboyt', 'howtouseboty', 'howtouseboht', 'howtouseboth', 'howtousebogt',
                          'howtousebotg', 'howtouseboft', 'howtousebotf', 'ow2usebot', 'hw2usebot', 'ho2usebot',
                          'howusebot', 'how2sebot', 'how2uebot', 'how2usbot', 'how2useot', 'how2usebt', 'how2usebo',
                          'hhow2usebot', 'hoow2usebot', 'howw2usebot', 'how22usebot', 'how2uusebot', 'how2ussebot',
                          'how2useebot', 'how2usebbot', 'how2useboot', 'how2usebott', 'ohw2usebot', 'hwo2usebot',
                          'ho2wusebot', 'howu2sebot', 'how2suebot', 'how2uesbot', 'how2usbeot', 'how2useobt',
                          'how2usebto', 'gow2usebot', 'yow2usebot', 'uow2usebot', 'jow2usebot', 'now2usebot',
                          'bow2usebot', 'hiw2usebot', 'h9w2usebot', 'h0w2usebot', 'hpw2usebot', 'hlw2usebot',
                          'hkw2usebot', 'hoq2usebot', 'ho22usebot', 'ho32usebot', 'hoe2usebot', 'hod2usebot',
                          'hos2usebot', 'hoa2usebot', 'how2ysebot', 'how27sebot', 'how28sebot', 'how2isebot',
                          'how2ksebot', 'how2jsebot', 'how2hsebot', 'how2uaebot', 'how2uwebot', 'how2ueebot',
                          'how2udebot', 'how2uxebot', 'how2uzebot', 'how2uswbot', 'how2us3bot', 'how2us4bot',
                          'how2usrbot', 'how2usfbot', 'how2usdbot', 'how2ussbot', 'how2usevot', 'how2usegot',
                          'how2usehot', 'how2usenot', 'how2usebit', 'how2useb9t', 'how2useb0t', 'how2usebpt',
                          'how2useblt', 'how2usebkt', 'how2usebor', 'how2usebo5', 'how2usebo6', 'how2useboy',
                          'how2useboh', 'how2usebog', 'how2usebof', 'ghow2usebot', 'hgow2usebot', 'yhow2usebot',
                          'hyow2usebot', 'uhow2usebot', 'huow2usebot', 'jhow2usebot', 'hjow2usebot', 'nhow2usebot',
                          'hnow2usebot', 'bhow2usebot', 'hbow2usebot', 'hiow2usebot', 'hoiw2usebot', 'h9ow2usebot',
                          'ho9w2usebot', 'h0ow2usebot', 'ho0w2usebot', 'hpow2usebot', 'hopw2usebot', 'hlow2usebot',
                          'holw2usebot', 'hkow2usebot', 'hokw2usebot', 'hoqw2usebot', 'howq2usebot', 'ho2w2usebot',
                          'ho3w2usebot', 'how32usebot', 'hoew2usebot', 'howe2usebot', 'hodw2usebot', 'howd2usebot',
                          'hosw2usebot', 'hows2usebot', 'hoaw2usebot', 'howa2usebot', 'how2yusebot', 'how2uysebot',
                          'how27usebot', 'how2u7sebot', 'how28usebot', 'how2u8sebot', 'how2iusebot', 'how2uisebot',
                          'how2kusebot', 'how2uksebot', 'how2jusebot', 'how2ujsebot', 'how2husebot', 'how2uhsebot',
                          'how2uasebot', 'how2usaebot', 'how2uwsebot', 'how2uswebot', 'how2uesebot', 'how2udsebot',
                          'how2usdebot', 'how2uxsebot', 'how2usxebot', 'how2uzsebot', 'how2uszebot', 'how2usewbot',
                          'how2us3ebot', 'how2use3bot', 'how2us4ebot', 'how2use4bot', 'how2usrebot', 'how2userbot',
                          'how2usfebot', 'how2usefbot', 'how2usedbot', 'how2usesbot', 'how2usevbot', 'how2usebvot',
                          'how2usegbot', 'how2usebgot', 'how2usehbot', 'how2usebhot', 'how2usenbot', 'how2usebnot',
                          'how2usebiot', 'how2useboit', 'how2useb9ot', 'how2usebo9t', 'how2useb0ot', 'how2usebo0t',
                          'how2usebpot', 'how2usebopt', 'how2useblot', 'how2usebolt', 'how2usebkot', 'how2usebokt',
                          'how2usebort', 'how2usebotr', 'how2usebo5t', 'how2usebot5', 'how2usebo6t', 'how2usebot6',
                          'how2useboyt', 'how2useboty', 'how2useboht', 'how2useboth', 'how2usebogt', 'how2usebotg',
                          'how2useboft', 'how2usebotf', 'owtousestwdaily', 'hwtousestwdaily', 'hotousestwdaily',
                          'howousestwdaily', 'howtusestwdaily', 'howtosestwdaily', 'howtouestwdaily', 'howtousstwdaily',
                          'howtousetwdaily', 'howtouseswdaily', 'howtousestdaily', 'howtousestwaily', 'howtousestwdily',
                          'howtousestwdaly', 'howtousestwdaiy', 'howtousestwdail', 'hhowtousestwdaily',
                          'hoowtousestwdaily', 'howwtousestwdaily', 'howttousestwdaily', 'howtoousestwdaily',
                          'howtouusestwdaily', 'howtoussestwdaily', 'howtouseestwdaily', 'howtousesstwdaily',
                          'howtousesttwdaily', 'howtousestwwdaily', 'howtousestwddaily', 'howtousestwdaaily',
                          'howtousestwdaiily', 'howtousestwdailly', 'howtousestwdailyy', 'ohwtousestwdaily',
                          'hwotousestwdaily', 'hotwousestwdaily', 'howotusestwdaily', 'howtuosestwdaily',
                          'howtosuestwdaily', 'howtouesstwdaily', 'howtoussetwdaily', 'howtousetswdaily',
                          'howtouseswtdaily', 'howtousestdwaily', 'howtousestwadily', 'howtousestwdialy',
                          'howtousestwdaliy', 'howtousestwdaiyl', 'gowtousestwdaily', 'yowtousestwdaily',
                          'uowtousestwdaily', 'jowtousestwdaily', 'nowtousestwdaily', 'bowtousestwdaily',
                          'hiwtousestwdaily', 'h9wtousestwdaily', 'h0wtousestwdaily', 'hpwtousestwdaily',
                          'hlwtousestwdaily', 'hkwtousestwdaily', 'hoqtousestwdaily', 'ho2tousestwdaily',
                          'ho3tousestwdaily', 'hoetousestwdaily', 'hodtousestwdaily', 'hostousestwdaily',
                          'hoatousestwdaily', 'howrousestwdaily', 'how5ousestwdaily', 'how6ousestwdaily',
                          'howyousestwdaily', 'howhousestwdaily', 'howgousestwdaily', 'howfousestwdaily',
                          'howtiusestwdaily', 'howt9usestwdaily', 'howt0usestwdaily', 'howtpusestwdaily',
                          'howtlusestwdaily', 'howtkusestwdaily', 'howtoysestwdaily', 'howto7sestwdaily',
                          'howto8sestwdaily', 'howtoisestwdaily', 'howtoksestwdaily', 'howtojsestwdaily',
                          'howtohsestwdaily', 'howtouaestwdaily', 'howtouwestwdaily', 'howtoueestwdaily',
                          'howtoudestwdaily', 'howtouxestwdaily', 'howtouzestwdaily', 'howtouswstwdaily',
                          'howtous3stwdaily', 'howtous4stwdaily', 'howtousrstwdaily', 'howtousfstwdaily',
                          'howtousdstwdaily', 'howtoussstwdaily', 'howtouseatwdaily', 'howtousewtwdaily',
                          'howtouseetwdaily', 'howtousedtwdaily', 'howtousextwdaily', 'howtouseztwdaily',
                          'howtousesrwdaily', 'howtouses5wdaily', 'howtouses6wdaily', 'howtousesywdaily',
                          'howtouseshwdaily', 'howtousesgwdaily', 'howtousesfwdaily', 'howtousestqdaily',
                          'howtousest2daily', 'howtousest3daily', 'howtousestedaily', 'howtousestddaily',
                          'howtousestsdaily', 'howtousestadaily', 'howtousestwsaily', 'howtousestweaily',
                          'howtousestwraily', 'howtousestwfaily', 'howtousestwcaily', 'howtousestwxaily',
                          'howtousestwdqily', 'howtousestwdwily', 'howtousestwdsily', 'howtousestwdxily',
                          'howtousestwdzily', 'howtousestwdauly', 'howtousestwda8ly', 'howtousestwda9ly',
                          'howtousestwdaoly', 'howtousestwdally', 'howtousestwdakly', 'howtousestwdajly',
                          'howtousestwdaiky', 'howtousestwdaioy', 'howtousestwdaipy', 'howtousestwdailt',
                          'howtousestwdail6', 'howtousestwdail7', 'howtousestwdailu', 'howtousestwdailj',
                          'howtousestwdailh', 'howtousestwdailg', 'ghowtousestwdaily', 'hgowtousestwdaily',
                          'yhowtousestwdaily', 'hyowtousestwdaily', 'uhowtousestwdaily', 'huowtousestwdaily',
                          'jhowtousestwdaily', 'hjowtousestwdaily', 'nhowtousestwdaily', 'hnowtousestwdaily',
                          'bhowtousestwdaily', 'hbowtousestwdaily', 'hiowtousestwdaily', 'hoiwtousestwdaily',
                          'h9owtousestwdaily', 'ho9wtousestwdaily', 'h0owtousestwdaily', 'ho0wtousestwdaily',
                          'hpowtousestwdaily', 'hopwtousestwdaily', 'hlowtousestwdaily', 'holwtousestwdaily',
                          'hkowtousestwdaily', 'hokwtousestwdaily', 'hoqwtousestwdaily', 'howqtousestwdaily',
                          'ho2wtousestwdaily', 'how2tousestwdaily', 'ho3wtousestwdaily', 'how3tousestwdaily',
                          'hoewtousestwdaily', 'howetousestwdaily', 'hodwtousestwdaily', 'howdtousestwdaily',
                          'hoswtousestwdaily', 'howstousestwdaily', 'hoawtousestwdaily', 'howatousestwdaily',
                          'howrtousestwdaily', 'howtrousestwdaily', 'how5tousestwdaily', 'howt5ousestwdaily',
                          'how6tousestwdaily', 'howt6ousestwdaily', 'howytousestwdaily', 'howtyousestwdaily',
                          'howhtousestwdaily', 'howthousestwdaily', 'howgtousestwdaily', 'howtgousestwdaily',
                          'howftousestwdaily', 'howtfousestwdaily', 'howtiousestwdaily', 'howtoiusestwdaily',
                          'howt9ousestwdaily', 'howto9usestwdaily', 'howt0ousestwdaily', 'howto0usestwdaily',
                          'howtpousestwdaily', 'howtopusestwdaily', 'howtlousestwdaily', 'howtolusestwdaily',
                          'howtkousestwdaily', 'howtokusestwdaily', 'howtoyusestwdaily', 'howtouysestwdaily',
                          'howto7usestwdaily', 'howtou7sestwdaily', 'howto8usestwdaily', 'howtou8sestwdaily',
                          'howtouisestwdaily', 'howtouksestwdaily', 'howtojusestwdaily', 'howtoujsestwdaily',
                          'howtohusestwdaily', 'howtouhsestwdaily', 'howtouasestwdaily', 'howtousaestwdaily',
                          'howtouwsestwdaily', 'howtouswestwdaily', 'howtouesestwdaily', 'howtoudsestwdaily',
                          'howtousdestwdaily', 'howtouxsestwdaily', 'howtousxestwdaily', 'howtouzsestwdaily',
                          'howtouszestwdaily', 'howtousewstwdaily', 'howtous3estwdaily', 'howtouse3stwdaily',
                          'howtous4estwdaily', 'howtouse4stwdaily', 'howtousrestwdaily', 'howtouserstwdaily',
                          'howtousfestwdaily', 'howtousefstwdaily', 'howtousedstwdaily', 'howtouseastwdaily',
                          'howtousesatwdaily', 'howtouseswtwdaily', 'howtousesetwdaily', 'howtousesdtwdaily',
                          'howtousexstwdaily', 'howtousesxtwdaily', 'howtousezstwdaily', 'howtousesztwdaily',
                          'howtousesrtwdaily', 'howtousestrwdaily', 'howtouses5twdaily', 'howtousest5wdaily',
                          'howtouses6twdaily', 'howtousest6wdaily', 'howtousesytwdaily', 'howtousestywdaily',
                          'howtouseshtwdaily', 'howtousesthwdaily', 'howtousesgtwdaily', 'howtousestgwdaily',
                          'howtousesftwdaily', 'howtousestfwdaily', 'howtousestqwdaily', 'howtousestwqdaily',
                          'howtousest2wdaily', 'howtousestw2daily', 'howtousest3wdaily', 'howtousestw3daily',
                          'howtousestewdaily', 'howtousestwedaily', 'howtousestdwdaily', 'howtousestswdaily',
                          'howtousestwsdaily', 'howtousestawdaily', 'howtousestwadaily', 'howtousestwdsaily',
                          'howtousestwdeaily', 'howtousestwrdaily', 'howtousestwdraily', 'howtousestwfdaily',
                          'howtousestwdfaily', 'howtousestwcdaily', 'howtousestwdcaily', 'howtousestwxdaily',
                          'howtousestwdxaily', 'howtousestwdqaily', 'howtousestwdaqily', 'howtousestwdwaily',
                          'howtousestwdawily', 'howtousestwdasily', 'howtousestwdaxily', 'howtousestwdzaily',
                          'howtousestwdazily', 'howtousestwdauily', 'howtousestwdaiuly', 'howtousestwda8ily',
                          'howtousestwdai8ly', 'howtousestwda9ily', 'howtousestwdai9ly', 'howtousestwdaoily',
                          'howtousestwdaioly', 'howtousestwdalily', 'howtousestwdakily', 'howtousestwdaikly',
                          'howtousestwdajily', 'howtousestwdaijly', 'howtousestwdailky', 'howtousestwdailoy',
                          'howtousestwdaiply', 'howtousestwdailpy', 'howtousestwdailty', 'howtousestwdailyt',
                          'howtousestwdail6y', 'howtousestwdaily6', 'howtousestwdail7y', 'howtousestwdaily7',
                          'howtousestwdailuy', 'howtousestwdailyu', 'howtousestwdailjy', 'howtousestwdailyj',
                          'howtousestwdailhy', 'howtousestwdailyh', 'howtousestwdailgy', 'howtousestwdailyg',
                          'ow2usestwdaily', 'hw2usestwdaily', 'ho2usestwdaily', 'howusestwdaily', 'how2sestwdaily',
                          'how2uestwdaily', 'how2usstwdaily', 'how2usetwdaily', 'how2useswdaily', 'how2usestdaily',
                          'how2usestwaily', 'how2usestwdily', 'how2usestwdaly', 'how2usestwdaiy', 'how2usestwdail',
                          'hhow2usestwdaily', 'hoow2usestwdaily', 'howw2usestwdaily', 'how22usestwdaily',
                          'how2uusestwdaily', 'how2ussestwdaily', 'how2useestwdaily', 'how2usesstwdaily',
                          'how2usesttwdaily', 'how2usestwwdaily', 'how2usestwddaily', 'how2usestwdaaily',
                          'how2usestwdaiily', 'how2usestwdailly', 'how2usestwdailyy', 'ohw2usestwdaily',
                          'hwo2usestwdaily', 'ho2wusestwdaily', 'howu2sestwdaily', 'how2suestwdaily', 'how2uesstwdaily',
                          'how2ussetwdaily', 'how2usetswdaily', 'how2useswtdaily', 'how2usestdwaily', 'how2usestwadily',
                          'how2usestwdialy', 'how2usestwdaliy', 'how2usestwdaiyl', 'gow2usestwdaily', 'yow2usestwdaily',
                          'uow2usestwdaily', 'jow2usestwdaily', 'now2usestwdaily', 'bow2usestwdaily', 'hiw2usestwdaily',
                          'h9w2usestwdaily', 'h0w2usestwdaily', 'hpw2usestwdaily', 'hlw2usestwdaily', 'hkw2usestwdaily',
                          'hoq2usestwdaily', 'ho22usestwdaily', 'ho32usestwdaily', 'hoe2usestwdaily', 'hod2usestwdaily',
                          'hos2usestwdaily', 'hoa2usestwdaily', 'how2ysestwdaily', 'how27sestwdaily', 'how28sestwdaily',
                          'how2isestwdaily', 'how2ksestwdaily', 'how2jsestwdaily', 'how2hsestwdaily', 'how2uaestwdaily',
                          'how2uwestwdaily', 'how2ueestwdaily', 'how2udestwdaily', 'how2uxestwdaily', 'how2uzestwdaily',
                          'how2uswstwdaily', 'how2us3stwdaily', 'how2us4stwdaily', 'how2usrstwdaily', 'how2usfstwdaily',
                          'how2usdstwdaily', 'how2ussstwdaily', 'how2useatwdaily', 'how2usewtwdaily', 'how2useetwdaily',
                          'how2usedtwdaily', 'how2usextwdaily', 'how2useztwdaily', 'how2usesrwdaily', 'how2uses5wdaily',
                          'how2uses6wdaily', 'how2usesywdaily', 'how2useshwdaily', 'how2usesgwdaily', 'how2usesfwdaily',
                          'how2usestqdaily', 'how2usest2daily', 'how2usest3daily', 'how2usestedaily', 'how2usestddaily',
                          'how2usestsdaily', 'how2usestadaily', 'how2usestwsaily', 'how2usestweaily', 'how2usestwraily',
                          'how2usestwfaily', 'how2usestwcaily', 'how2usestwxaily', 'how2usestwdqily', 'how2usestwdwily',
                          'how2usestwdsily', 'how2usestwdxily', 'how2usestwdzily', 'how2usestwdauly', 'how2usestwda8ly',
                          'how2usestwda9ly', 'how2usestwdaoly', 'how2usestwdally', 'how2usestwdakly', 'how2usestwdajly',
                          'how2usestwdaiky', 'how2usestwdaioy', 'how2usestwdaipy', 'how2usestwdailt', 'how2usestwdail6',
                          'how2usestwdail7', 'how2usestwdailu', 'how2usestwdailj', 'how2usestwdailh', 'how2usestwdailg',
                          'ghow2usestwdaily', 'hgow2usestwdaily', 'yhow2usestwdaily', 'hyow2usestwdaily',
                          'uhow2usestwdaily', 'huow2usestwdaily', 'jhow2usestwdaily', 'hjow2usestwdaily',
                          'nhow2usestwdaily', 'hnow2usestwdaily', 'bhow2usestwdaily', 'hbow2usestwdaily',
                          'hiow2usestwdaily', 'hoiw2usestwdaily', 'h9ow2usestwdaily', 'ho9w2usestwdaily',
                          'h0ow2usestwdaily', 'ho0w2usestwdaily', 'hpow2usestwdaily', 'hopw2usestwdaily',
                          'hlow2usestwdaily', 'holw2usestwdaily', 'hkow2usestwdaily', 'hokw2usestwdaily',
                          'hoqw2usestwdaily', 'howq2usestwdaily', 'ho2w2usestwdaily', 'ho3w2usestwdaily',
                          'how32usestwdaily', 'hoew2usestwdaily', 'howe2usestwdaily', 'hodw2usestwdaily',
                          'howd2usestwdaily', 'hosw2usestwdaily', 'hows2usestwdaily', 'hoaw2usestwdaily',
                          'howa2usestwdaily', 'how2yusestwdaily', 'how2uysestwdaily', 'how27usestwdaily',
                          'how2u7sestwdaily', 'how28usestwdaily', 'how2u8sestwdaily', 'how2iusestwdaily',
                          'how2uisestwdaily', 'how2kusestwdaily', 'how2uksestwdaily', 'how2jusestwdaily',
                          'how2ujsestwdaily', 'how2husestwdaily', 'how2uhsestwdaily', 'how2uasestwdaily',
                          'how2usaestwdaily', 'how2uwsestwdaily', 'how2uswestwdaily', 'how2uesestwdaily',
                          'how2udsestwdaily', 'how2usdestwdaily', 'how2uxsestwdaily', 'how2usxestwdaily',
                          'how2uzsestwdaily', 'how2uszestwdaily', 'how2usewstwdaily', 'how2us3estwdaily',
                          'how2use3stwdaily', 'how2us4estwdaily', 'how2use4stwdaily', 'how2usrestwdaily',
                          'how2userstwdaily', 'how2usfestwdaily', 'how2usefstwdaily', 'how2usedstwdaily',
                          'how2useastwdaily', 'how2usesatwdaily', 'how2useswtwdaily', 'how2usesetwdaily',
                          'how2usesdtwdaily', 'how2usexstwdaily', 'how2usesxtwdaily', 'how2usezstwdaily',
                          'how2usesztwdaily', 'how2usesrtwdaily', 'how2usestrwdaily', 'how2uses5twdaily',
                          'how2usest5wdaily', 'how2uses6twdaily', 'how2usest6wdaily', 'how2usesytwdaily',
                          'how2usestywdaily', 'how2useshtwdaily', 'how2usesthwdaily', 'how2usesgtwdaily',
                          'how2usestgwdaily', 'how2usesftwdaily', 'how2usestfwdaily', 'how2usestqwdaily',
                          'how2usestwqdaily', 'how2usest2wdaily', 'how2usestw2daily', 'how2usest3wdaily',
                          'how2usestw3daily', 'how2usestewdaily', 'how2usestwedaily', 'how2usestdwdaily',
                          'how2usestswdaily', 'how2usestwsdaily', 'how2usestawdaily', 'how2usestwadaily',
                          'how2usestwdsaily', 'how2usestwdeaily', 'how2usestwrdaily', 'how2usestwdraily',
                          'how2usestwfdaily', 'how2usestwdfaily', 'how2usestwcdaily', 'how2usestwdcaily',
                          'how2usestwxdaily', 'how2usestwdxaily', 'how2usestwdqaily', 'how2usestwdaqily',
                          'how2usestwdwaily', 'how2usestwdawily', 'how2usestwdasily', 'how2usestwdaxily',
                          'how2usestwdzaily', 'how2usestwdazily', 'how2usestwdauily', 'how2usestwdaiuly',
                          'how2usestwda8ily', 'how2usestwdai8ly', 'how2usestwda9ily', 'how2usestwdai9ly',
                          'how2usestwdaoily', 'how2usestwdaioly', 'how2usestwdalily', 'how2usestwdakily',
                          'how2usestwdaikly', 'how2usestwdajily', 'how2usestwdaijly', 'how2usestwdailky',
                          'how2usestwdailoy', 'how2usestwdaiply', 'how2usestwdailpy', 'how2usestwdailty',
                          'how2usestwdailyt', 'how2usestwdail6y', 'how2usestwdaily6', 'how2usestwdail7y',
                          'how2usestwdaily7', 'how2usestwdailuy', 'how2usestwdailyu', 'how2usestwdailjy',
                          'how2usestwdailyj', 'how2usestwdailhy', 'how2usestwdailyh', 'how2usestwdailgy',
                          'how2usestwdailyg', 'nstruction', 'istruction', 'intruction', 'insruction', 'instuction',
                          'instrction', 'instrution', 'instrucion', 'instructon', 'instructin', 'instructio',
                          'iinstruction', 'innstruction', 'insstruction', 'insttruction', 'instrruction',
                          'instruuction', 'instrucction', 'instructtion', 'instructiion', 'instructioon',
                          'instructionn', 'nistruction', 'isntruction', 'intsruction', 'insrtuction', 'insturction',
                          'instrcution', 'instrutcion', 'instruciton', 'instructoin', 'instructino', 'unstruction',
                          '8nstruction', '9nstruction', 'onstruction', 'lnstruction', 'knstruction', 'jnstruction',
                          'ibstruction', 'ihstruction', 'ijstruction', 'imstruction', 'inatruction', 'inwtruction',
                          'inetruction', 'indtruction', 'inxtruction', 'inztruction', 'insrruction', 'ins5ruction',
                          'ins6ruction', 'insyruction', 'inshruction', 'insgruction', 'insfruction', 'insteuction',
                          'inst4uction', 'inst5uction', 'insttuction', 'instguction', 'instfuction', 'instduction',
                          'instryction', 'instr7ction', 'instr8ction', 'instriction', 'instrkction', 'instrjction',
                          'instrhction', 'instruxtion', 'instrudtion', 'instruftion', 'instruvtion', 'instrucrion',
                          'instruc5ion', 'instruc6ion', 'instrucyion', 'instruchion', 'instrucgion', 'instrucfion',
                          'instructuon', 'instruct8on', 'instruct9on', 'instructoon', 'instructlon', 'instructkon',
                          'instructjon', 'instructiin', 'instructi9n', 'instructi0n', 'instructipn', 'instructiln',
                          'instructikn', 'instructiob', 'instructioh', 'instructioj', 'instructiom', 'uinstruction',
                          'iunstruction', '8instruction', 'i8nstruction', '9instruction', 'i9nstruction',
                          'oinstruction', 'ionstruction', 'linstruction', 'ilnstruction', 'kinstruction',
                          'iknstruction', 'jinstruction', 'ijnstruction', 'ibnstruction', 'inbstruction',
                          'ihnstruction', 'inhstruction', 'injstruction', 'imnstruction', 'inmstruction',
                          'inastruction', 'insatruction', 'inwstruction', 'inswtruction', 'inestruction',
                          'insetruction', 'indstruction', 'insdtruction', 'inxstruction', 'insxtruction',
                          'inzstruction', 'insztruction', 'insrtruction', 'ins5truction', 'inst5ruction',
                          'ins6truction', 'inst6ruction', 'insytruction', 'instyruction', 'inshtruction',
                          'insthruction', 'insgtruction', 'instgruction', 'insftruction', 'instfruction',
                          'insteruction', 'instreuction', 'inst4ruction', 'instr4uction', 'instr5uction',
                          'instrtuction', 'instrguction', 'instrfuction', 'instdruction', 'instrduction',
                          'instryuction', 'instruyction', 'instr7uction', 'instru7ction', 'instr8uction',
                          'instru8ction', 'instriuction', 'instruiction', 'instrkuction', 'instrukction',
                          'instrjuction', 'instrujction', 'instrhuction', 'instruhction', 'instruxction',
                          'instrucxtion', 'instrudction', 'instrucdtion', 'instrufction', 'instrucftion',
                          'instruvction', 'instrucvtion', 'instrucrtion', 'instructrion', 'instruc5tion',
                          'instruct5ion', 'instruc6tion', 'instruct6ion', 'instrucytion', 'instructyion',
                          'instruchtion', 'instructhion', 'instrucgtion', 'instructgion', 'instructfion',
                          'instructuion', 'instructiuon', 'instruct8ion', 'instructi8on', 'instruct9ion',
                          'instructi9on', 'instructoion', 'instructlion', 'instructilon', 'instructkion',
                          'instructikon', 'instructjion', 'instructijon', 'instructioin', 'instructio9n',
                          'instructi0on', 'instructio0n', 'instructipon', 'instructiopn', 'instructioln',
                          'instructiokn', 'instructiobn', 'instructionb', 'instructiohn', 'instructionh',
                          'instructiojn', 'instructionj', 'instructiomn', 'instructionm', 'nst', 'ist', 'int', 'ins',
                          'iinst', 'innst', 'insst', 'instt', 'nist', 'isnt', 'ints', 'unst', '8nst', '9nst', 'onst',
                          'lnst', 'knst', 'jnst', 'ibst', 'ihst', 'ijst', 'imst', 'inat', 'inwt', 'inet', 'indt',
                          'inxt', 'inzt', 'insr', 'ins5', 'ins6', 'insy', 'insh', 'insg', 'insf', 'uinst', 'iunst',
                          '8inst', 'i8nst', '9inst', 'i9nst', 'oinst', 'ionst', 'linst', 'ilnst', 'kinst', 'iknst',
                          'jinst', 'ijnst', 'ibnst', 'inbst', 'ihnst', 'inhst', 'injst', 'imnst', 'inmst', 'inast',
                          'insat', 'inwst', 'inswt', 'inest', 'inset', 'indst', 'insdt', 'inxst', 'insxt', 'inzst',
                          'inszt', 'insrt', 'instr', 'ins5t', 'inst5', 'ins6t', 'inst6', 'insyt', 'insty', 'insht',
                          'insth', 'insgt', 'instg', 'insft', 'instf', 'orehelp', 'mrehelp', 'moehelp', 'morhelp',
                          'moreelp', 'morehlp', 'morehep', 'morehel', 'mmorehelp', 'moorehelp', 'morrehelp',
                          'moreehelp', 'morehhelp', 'moreheelp', 'morehellp', 'morehelpp', 'omrehelp', 'mroehelp',
                          'moerhelp', 'morheelp', 'moreehlp', 'morehlep', 'morehepl', 'norehelp', 'jorehelp',
                          'korehelp', 'mirehelp', 'm9rehelp', 'm0rehelp', 'mprehelp', 'mlrehelp', 'mkrehelp',
                          'moeehelp', 'mo4ehelp', 'mo5ehelp', 'motehelp', 'mogehelp', 'mofehelp', 'modehelp',
                          'morwhelp', 'mor3help', 'mor4help', 'morrhelp', 'morfhelp', 'mordhelp', 'morshelp',
                          'moregelp', 'moreyelp', 'moreuelp', 'morejelp', 'morenelp', 'morebelp', 'morehwlp',
                          'moreh3lp', 'moreh4lp', 'morehrlp', 'morehflp', 'morehdlp', 'morehslp', 'morehekp',
                          'moreheop', 'morehepp', 'morehelo', 'morehel0', 'morehell', 'nmorehelp', 'mnorehelp',
                          'jmorehelp', 'mjorehelp', 'kmorehelp', 'mkorehelp', 'miorehelp', 'moirehelp', 'm9orehelp',
                          'mo9rehelp', 'm0orehelp', 'mo0rehelp', 'mporehelp', 'moprehelp', 'mlorehelp', 'molrehelp',
                          'mokrehelp', 'moerehelp', 'mo4rehelp', 'mor4ehelp', 'mo5rehelp', 'mor5ehelp', 'motrehelp',
                          'mortehelp', 'mogrehelp', 'morgehelp', 'mofrehelp', 'morfehelp', 'modrehelp', 'mordehelp',
                          'morwehelp', 'morewhelp', 'mor3ehelp', 'more3help', 'more4help', 'morerhelp', 'morefhelp',
                          'moredhelp', 'morsehelp', 'moreshelp', 'moreghelp', 'morehgelp', 'moreyhelp', 'morehyelp',
                          'moreuhelp', 'morehuelp', 'morejhelp', 'morehjelp', 'morenhelp', 'morehnelp', 'morebhelp',
                          'morehbelp', 'morehwelp', 'morehewlp', 'moreh3elp', 'morehe3lp', 'moreh4elp', 'morehe4lp',
                          'morehrelp', 'moreherlp', 'morehfelp', 'moreheflp', 'morehdelp', 'morehedlp', 'morehselp',
                          'moreheslp', 'moreheklp', 'morehelkp', 'moreheolp', 'morehelop', 'moreheplp', 'morehelpo',
                          'morehel0p', 'morehelp0', 'morehelpl', 'lshelp', 'pshelp', 'plhelp', 'plselp', 'plshlp',
                          'plshep', 'plshel', 'pplshelp', 'pllshelp', 'plsshelp', 'plshhelp', 'plsheelp', 'plshellp',
                          'plshelpp', 'lpshelp', 'pslhelp', 'plhselp', 'plsehlp', 'plshlep', 'plshepl', 'olshelp',
                          '0lshelp', 'llshelp', 'pkshelp', 'poshelp', 'ppshelp', 'plahelp', 'plwhelp', 'plehelp',
                          'pldhelp', 'plxhelp', 'plzhelp', 'plsgelp', 'plsyelp', 'plsuelp', 'plsjelp', 'plsnelp',
                          'plsbelp', 'plshwlp', 'plsh3lp', 'plsh4lp', 'plshrlp', 'plshflp', 'plshdlp', 'plshslp',
                          'plshekp', 'plsheop', 'plshepp', 'plshelo', 'plshel0', 'plshell', 'oplshelp', 'polshelp',
                          '0plshelp', 'p0lshelp', 'lplshelp', 'pklshelp', 'plkshelp', 'ploshelp', 'plpshelp',
                          'plashelp', 'plsahelp', 'plwshelp', 'plswhelp', 'pleshelp', 'plsehelp', 'pldshelp',
                          'plsdhelp', 'plxshelp', 'plsxhelp', 'plzshelp', 'plszhelp', 'plsghelp', 'plshgelp',
                          'plsyhelp', 'plshyelp', 'plsuhelp', 'plshuelp', 'plsjhelp', 'plshjelp', 'plsnhelp',
                          'plshnelp', 'plsbhelp', 'plshbelp', 'plshwelp', 'plshewlp', 'plsh3elp', 'plshe3lp',
                          'plsh4elp', 'plshe4lp', 'plshrelp', 'plsherlp', 'plshfelp', 'plsheflp', 'plshdelp',
                          'plshedlp', 'plshselp', 'plsheslp', 'plsheklp', 'plshelkp', 'plsheolp', 'plshelop',
                          'plsheplp', 'plshelpo', 'plshel0p', 'plshelp0', 'plshelpl', 'utorial', 'ttorial', 'tuorial',
                          'tutrial', 'tutoial', 'tutoral', 'tutoril', 'tutoria', 'ttutorial', 'tuutorial', 'tuttorial',
                          'tutoorial', 'tutorrial', 'tutoriial', 'tutoriaal', 'tutoriall', 'uttorial', 'ttuorial',
                          'tuotrial', 'tutroial', 'tutoiral', 'tutorail', 'tutorila', 'rutorial', '5utorial',
                          '6utorial', 'yutorial', 'hutorial', 'gutorial', 'futorial', 'tytorial', 't7torial',
                          't8torial', 'titorial', 'tktorial', 'tjtorial', 'thtorial', 'turorial', 'tu5orial',
                          'tu6orial', 'tuyorial', 'tuhorial', 'tugorial', 'tuforial', 'tutirial', 'tut9rial',
                          'tut0rial', 'tutprial', 'tutlrial', 'tutkrial', 'tutoeial', 'tuto4ial', 'tuto5ial',
                          'tutotial', 'tutogial', 'tutofial', 'tutodial', 'tutorual', 'tutor8al', 'tutor9al',
                          'tutoroal', 'tutorlal', 'tutorkal', 'tutorjal', 'tutoriql', 'tutoriwl', 'tutorisl',
                          'tutorixl', 'tutorizl', 'tutoriak', 'tutoriao', 'tutoriap', 'rtutorial', 'trutorial',
                          '5tutorial', 't5utorial', '6tutorial', 't6utorial', 'ytutorial', 'tyutorial', 'htutorial',
                          'thutorial', 'gtutorial', 'tgutorial', 'ftutorial', 'tfutorial', 'tuytorial', 't7utorial',
                          'tu7torial', 't8utorial', 'tu8torial', 'tiutorial', 'tuitorial', 'tkutorial', 'tuktorial',
                          'tjutorial', 'tujtorial', 'tuhtorial', 'turtorial', 'tutrorial', 'tu5torial', 'tut5orial',
                          'tu6torial', 'tut6orial', 'tutyorial', 'tuthorial', 'tugtorial', 'tutgorial', 'tuftorial',
                          'tutforial', 'tutiorial', 'tutoirial', 'tut9orial', 'tuto9rial', 'tut0orial', 'tuto0rial',
                          'tutporial', 'tutoprial', 'tutlorial', 'tutolrial', 'tutkorial', 'tutokrial', 'tutoerial',
                          'tutoreial', 'tuto4rial', 'tutor4ial', 'tuto5rial', 'tutor5ial', 'tutotrial', 'tutortial',
                          'tutogrial', 'tutorgial', 'tutofrial', 'tutorfial', 'tutodrial', 'tutordial', 'tutoruial',
                          'tutoriual', 'tutor8ial', 'tutori8al', 'tutor9ial', 'tutori9al', 'tutoroial', 'tutorioal',
                          'tutorlial', 'tutorilal', 'tutorkial', 'tutorikal', 'tutorjial', 'tutorijal', 'tutoriqal',
                          'tutoriaql', 'tutoriwal', 'tutoriawl', 'tutorisal', 'tutoriasl', 'tutorixal', 'tutoriaxl',
                          'tutorizal', 'tutoriazl', 'tutoriakl', 'tutorialk', 'tutoriaol', 'tutorialo', 'tutoriapl',
                          'tutorialp', 'ow', 'hw', 'ho', 'hhow', 'hoow', 'howw', 'ohw', 'hwo', 'gow', 'yow', 'uow',
                          'jow', 'now', 'bow', 'hiw', 'h9w', 'h0w', 'hpw', 'hlw', 'hkw', 'hoq', 'ho3', 'hoe', 'hod',
                          'hos', 'hoa', 'ghow', 'hgow', 'yhow', 'hyow', 'uhow', 'huow', 'jhow', 'hjow', 'nhow', 'hnow',
                          'bhow', 'hbow', 'hiow', 'hoiw', 'h9ow', 'ho9w', 'h0ow', 'ho0w', 'hpow', 'hopw', 'hlow',
                          'holw', 'hkow', 'hokw', 'hoqw', 'howq', 'ho3w', 'how3', 'hoew', 'howe', 'hodw', 'howd',
                          'hosw', 'hows', 'hoaw', 'howa', 'কিভাবে2', 'com 2', 'jak 2', 'πώς2', 'cómo2', 'kuidas2',
                          'miten2', 'કેવી રીતે2', 'yadda2', 'איך 2', 'कैसे2', 'hogyan2', 'どうやって2', 'kaip2', 'kā2',
                          'कसे2', 'bagaimana2', 'jak2', 'cum2', 'как2', 'ako2', 'хов2', 'vipi2', 'எப்படி2', 'ఎలా2',
                          'nasıl2', 'کیسے 2', '怎么样2', '怎麼樣2', 'com2', 'کیسے2', 'hoxw2', 'how2n', 'zhow2', 'iow2',
                          'sow2', 'how2y', 'row2', 'hobw2', 'howg2', 'howj2', 'fhow2', 'howj', 'hown', 'howp2', 'hohw2',
                          'how2r', 'hvw2', 'huw2', 'hoi2', 'ahow2', 'homw2', 'how2g', 'howr', 'hogw2', 'dow2', 'honw2',
                          'cow2', 'hxw2', 'how2k', 'hbw2', 'hoc2', 'mhow2', 'how2q', 'hzow2', 'eow2', 'hog2', 'hdow2',
                          'hwow2', 'how2i', 'howu', 'xow2', 'tow2', 'hop2', 'vhow2', 'pow2', 'mow2', 'hojw2', 'howy',
                          'howl', 'hoz2', 'hov2', 'hoh2', 'hww2', 'hvow2', 'oow2', 'hotw2', 'hqw2', 'htow2', 'hcow2',
                          'hor2', 'phow2', 'howx2', 'low2', 'howc2', 'how2z', 'howg', 'hol2', 'hyw2', 'ehow2', 'how2f',
                          'whow2', 'hrow2', 'hown2', 'wow2', 'howc', 'hhw2', 'how2d', 'vow2', 'how2p', 'howo2', 'hok2',
                          'howt2', 'hzw2', 'how2b', 'haow2', 'hmw2', 'howb', 'zow2', 'howm2', 'khow2', 'hom2', 'haw2',
                          'hou2', 'hox2', 'hoyw2', 'hrw2', 'qow2', 'how2s', 'how2x', 'hovw2', 'hon2', 'howu2', 'howv',
                          'hcw2', 'kow2', 'howf2', 'howp', 'howi', 'hdw2', 'hoo2', 'howr2', 'horw2', 'hot2', 'hozw2',
                          'how2m', 'lhow2', 'howk2', 'hof2', 'hob2', 'howh', 'hsw2', 'hgw2', 'aow2', 'xhow2', 'ihow2',
                          'ohow2', 'howk', 'hocw2', 'how2l', 'hjw2', 'howi2', 'howh2', 'howz2', 'how2c', 'dhow2',
                          'howz', 'rhow2', 'how2a', 'houw2', 'hmow2', 'howv2', 'show2', 'hofw2', 'how2u', 'chow2',
                          'how2e', 'hfw2', 'howy2', 'fow2', 'howl2', 'htw2', 'how2h', 'hqow2', 'how2t', 'how2w', 'howm',
                          'hxow2', 'howf', 'how2v', 'thow2', 'hoj2', 'qhow2', 'hnw2', 'how2j', 'howx', 'heow2', 'hew2',
                          'howb2', 'hsow2', 'how2o', 'hoy2', 'hfow2', 'h8w2', 'h;w2', 'h*w2', 'h(w2', 'h)w2', 'ho12',
                          'ho!2', 'ho@2', 'ho#2', 'how1', 'how!', 'how@', 'how#', 'howtg', 'hzwto', 'howtot', 'howtt',
                          'houwto', 'hdowto', 'howqo', 'howtbo', 'howteo', 'howtoq', 'hzowto', 'hozwto', 'hoxto',
                          'phowto', 'howlto', 'zhowto', 'howtd', 'howuto', 'iowto', 'hnwto', 'hokto', 'horwto',
                          'howtoe', 'howtor', 'howtov', 'hvwto', 'hozto', 'howtoj', 'chowto', 'fhowto', 'hrowto',
                          'hqwto', 'howoto', 'qhowto', 'hcwto', 'kowto', 'houto', 'honto', 'hojto', 'hoywto', 'vowto',
                          'howtw', 'hogto', 'haowto', 'hxowto', 'howjo', 'homto', 'howtxo', 'hdwto', 'rowto', 'dhowto',
                          'aowto', 'lowto', 'howuo', 'hxwto', 'hohto', 'hopto', 'howpo', 'zowto', 'howtog', 'heowto',
                          'vhowto', 'hvowto', 'powto', 'hsowto', 'thowto', 'hoito', 'howtso', 'howxo', 'rhowto',
                          'howtod', 'ihowto', 'hfowto', 'hbwto', 'howtc', 'hoxwto', 'howtow', 'howito', 'howvto',
                          'holto', 'howso', 'howtom', 'whowto', 'howzto', 'hoyto', 'wowto', 'howzo', 'howtdo', 'hwwto',
                          'hwowto', 'hogwto', 'howtjo', 'cowto', 'hobwto', 'howtx', 'hofwto', 'oowto', 'howton',
                          'hojwto', 'howtoa', 'howta', 'howtoc', 'hocto', 'howtco', 'ehowto', 'howtj', 'hcowto',
                          'howtu', 'howdo', 'hjwto', 'howtox', 'howtn', 'howtou', 'howbto', 'howtm', 'hohwto', 'howco',
                          'howtq', 'howtqo', 'htowto', 'howmo', 'howty', 'howtr', 'howio', 'hywto', 'hrwto', 'howao',
                          'howcto', 'hfwto', 'lhowto', 'hewto', 'hhwto', 'howtb', 'fowto', 'howbo', 'mowto', 'huwto',
                          'hswto', 'khowto', 'hgwto', 'hobto', 'hovwto', 'howvo', 'howtao', 'howwo', 'mhowto', 'htwto',
                          'hofto', 'howtob', 'qowto', 'hownto', 'howtz', 'hovto', 'howpto', 'hmwto', 'hooto', 'howtwo',
                          'hotto', 'howmto', 'sowto', 'xowto', 'howtzo', 'howtf', 'howtmo', 'howte', 'howtv', 'honwto',
                          'howxto', 'howtof', 'hotwto', 'dowto', 'howkto', 'eowto', 'ahowto', 'howtoh', 'howts',
                          'xhowto', 'howlo', 'howtno', 'howtuo', 'howoo', 'howtos', 'hawto', 'hmowto', 'hqowto',
                          'howko', 'ohowto', 'howth', 'howtvo', 'towto', 'howtoz', 'howtoy', 'homwto', 'hocwto',
                          'horto', 'howeo', 'howno', 'howjto', 'showto', 'h8wto', 'h;wto', 'h*wto', 'h(wto', 'h)wto',
                          'ho1to', 'ho!to', 'ho@to', 'ho#to', 'how4o', 'how$o', 'how%o', 'how^o', 'howt8', 'howt;',
                          'howt*', 'howt(', 'howt)', 'vhowtouse', 'holtouse', 'howteuse', 'howptouse', 'howktouse',
                          'howtosse', 'hoitouse', 'howtzouse', 'howtousc', 'howtogse', 'rowtouse', 'hmwtouse',
                          'howtoxuse', 'howotouse', 'howdouse', 'howtowuse', 'howtousex', 'howtoese', 'hdowtouse',
                          'howtobse', 'howtoune', 'howtoush', 'howtousei', 'hdwtouse', 'hownouse', 'dowtouse',
                          'hvowtouse', 'howtoupe', 'cowtouse', 'howtouseu', 'howtoose', 'howkouse', 'howtzuse',
                          'hoxwtouse', 'howcouse', 'howtousj', 'hzowtouse', 'howeouse', 'howtousbe', 'howztouse',
                          'howiouse', 'hoytouse', 'towtouse', 'howtouvse', 'hswtouse', 'hojtouse', 'howtoule',
                          'howtouske', 'hoptouse', 'hawtouse', 'howtouseg', 'howtonuse', 'howtousge', 'howtousoe',
                          'howtobuse', 'howtoust', 'ohowtouse', 'howtbouse', 'howtouve', 'howtxuse', 'howvtouse',
                          'howbtouse', 'phowtouse', 'hortouse', 'homwtouse', 'howtruse', 'howtousec', 'howtmouse',
                          'howtouspe', 'mhowtouse', 'hojwtouse', 'howtouste', 'howvouse', 'howtouge', 'howtousje',
                          'hzwtouse', 'showtouse', 'howtouie', 'howtause', 'howtcuse', 'howtousv', 'hozwtouse',
                          'xowtouse', 'howtousm', 'thowtouse', 'howtomse', 'howtoguse', 'howtouseq', 'hobtouse',
                          'howtouue', 'howxtouse', 'howtousl', 'xhowtouse', 'howtoxse', 'rhowtouse', 'hfwtouse',
                          'howtuuse', 'howtvouse', 'howtozuse', 'hoktouse', 'howteouse', 'hxwtouse', 'howtousie',
                          'mowtouse', 'howtoase', 'hvwtouse', 'howtjouse', 'haowtouse', 'chowtouse', 'howtousea',
                          'howtouset', 'howtousqe', 'howtofse', 'howtourse', 'htwtouse', 'howtousy', 'howltouse',
                          'howtguse', 'hcowtouse', 'howtqouse', 'howtocse', 'howbouse', 'honwtouse', 'howtoumse',
                          'howtouce', 'horwtouse', 'hrwtouse', 'howtousk', 'iowtouse', 'hogwtouse', 'khowtouse',
                          'hovwtouse', 'howtousi', 'hqowtouse', 'aowtouse', 'howtouqse', 'howtoute', 'howtoucse',
                          'hmowtouse', 'hottouse', 'howtoufse', 'howmouse', 'howtousz', 'hrowtouse', 'howtouseh',
                          'howtouke', 'hovtouse', 'howtouso', 'heowtouse', 'howtounse', 'howtmuse', 'howtopse',
                          'hewtouse', 'howtuouse', 'howtouje', 'howtoqse', 'howtoume', 'hofwtouse', 'howtousa',
                          'howtousue', 'hoctouse', 'whowtouse', 'eowtouse', 'homtouse', 'kowtouse', 'hqwtouse',
                          'howtouhe', 'howtoause', 'hotwtouse', 'hohtouse', 'hootouse', 'howtxouse', 'howtousme',
                          'ehowtouse', 'howtouye', 'qhowtouse', 'huwtouse', 'hhwtouse', 'howqouse', 'howtouqe',
                          'zowtouse', 'howtoquse', 'houwtouse', 'howtorse', 'howtousve', 'howaouse', 'howjouse',
                          'howtotse', 'howtousye', 'howtouseo', 'ahowtouse', 'howtsouse', 'howtoutse', 'oowtouse',
                          'hsowtouse', 'howttuse', 'howtquse', 'howtozse', 'hogtouse', 'howoouse', 'hxowtouse',
                          'houtouse', 'hjwtouse', 'howtousey', 'howtousel', 'howtousp', 'howntouse', 'hcwtouse',
                          'howwouse', 'hoxtouse', 'fowtouse', 'howtoulse', 'howtousce', 'howtousez', 'howtbuse',
                          'howtousg', 'lowtouse', 'hoywtouse', 'howmtouse', 'howtouseb', 'howtnouse', 'howthuse',
                          'howtouoe', 'howutouse', 'howtoure', 'howtoupse', 'howtdouse', 'howtousev', 'vowtouse',
                          'hwowtouse', 'howtousle', 'howtcouse', 'hbwtouse', 'howtonse', 'howlouse', 'hobwtouse',
                          'howtwouse', 'howsouse', 'hoztouse', 'howtoeuse', 'howtolse', 'howtoushe', 'hnwtouse',
                          'howtosuse', 'howxouse', 'zhowtouse', 'howtwuse', 'howtfuse', 'howtoubse', 'howtduse',
                          'hohwtouse', 'hfowtouse', 'htowtouse', 'howtougse', 'fhowtouse', 'ihowtouse', 'howjtouse',
                          'howtoube', 'howtousen', 'hocwtouse', 'howtocuse', 'dhowtouse', 'howtnuse', 'howtofuse',
                          'howpouse', 'howtoruse', 'howtyuse', 'howtousu', 'qowtouse', 'howtoufe', 'howtaouse',
                          'hywtouse', 'hontouse', 'howtvuse', 'howtousn', 'howtovuse', 'lhowtouse', 'howtousem',
                          'howtousx', 'hgwtouse', 'howtousek', 'wowtouse', 'howtovse', 'howtsuse', 'howtousne',
                          'howitouse', 'hwwtouse', 'howtjuse', 'howuouse', 'howtousb', 'howtoduse', 'howtousej',
                          'howtowse', 'howtotuse', 'howzouse', 'howctouse', 'sowtouse', 'howtodse', 'hoftouse',
                          'howtouose', 'howtousq', 'howtomuse', 'howtousep', 'powtouse', 'h8wtouse', 'h;wtouse',
                          'h*wtouse', 'h(wtouse', 'h)wtouse', 'ho1touse', 'ho!touse', 'ho@touse', 'ho#touse',
                          'how4ouse', 'how$ouse', 'how%ouse', 'how^ouse', 'howt8use', 'howt;use', 'howt*use',
                          'howt(use', 'howt)use', 'howto6se', 'howto^se', 'howto&se', 'howto*se', 'howtous2',
                          'howtous$', 'howtous#', 'howtous@', 'hon2use', 'hhw2use', 'hou2use', 'vhow2use', 'how2uje',
                          'how2umse', 'how2usel', 'howguse', 'hogw2use', 'how2une', 'hqw2use', 'hojw2use', 'ahow2use',
                          'how2ust', 'how2nuse', 'how2usp', 'fhow2use', 'hbw2use', 'how2usea', 'houw2use', 'hrw2use',
                          'how2usx', 'heow2use', 'how2cuse', 'howquse', 'how2useq', 'how2usge', 'kow2use', 'how2usn',
                          'how2zuse', 'hox2use', 'how2usei', 'how2wse', 'how2uso', 'how2uqe', 'low2use', 'how2ugse',
                          'how2usz', 'how2usi', 'how2usek', 'how2uste', 'howcuse', 'hsw2use', 'hcow2use', 'rhow2use',
                          'hvw2use', 'howbuse', 'hfw2use', 'hjw2use', 'tow2use', 'fow2use', 'xow2use', 'phow2use',
                          'how2usce', 'hoy2use', 'how2usne', 'howjuse', 'howm2use', 'zow2use', 'how2tuse', 'how2ese',
                          'howc2use', 'how2utse', 'howkuse', 'dhow2use', 'how2uqse', 'hozw2use', 'how2ase', 'hop2use',
                          'how2uue', 'how2usev', 'hmow2use', 'how2ush', 'how2xuse', 'hof2use', 'how2usec', 'whow2use',
                          'hohw2use', 'row2use', 'hoyw2use', 'hcw2use', 'howzuse', 'qow2use', 'how2usie', 'hown2use',
                          'ehow2use', 'hzw2use', 'how2fse', 'hnw2use', 'how2puse', 'howu2use', 'sow2use', 'how2usq',
                          'iow2use', 'how2ufse', 'hov2use', 'how2pse', 'hxow2use', 'how2ulse', 'howuuse', 'hoc2use',
                          'how2uve', 'how2unse', 'ihow2use', 'how2guse', 'how2uce', 'htow2use', 'howause', 'how2uke',
                          'how2vse', 'how2usve', 'how2usye', 'how2ufe', 'how2ose', 'hfow2use', 'howduse', 'how2ubse',
                          'how2useg', 'how2mse', 'how2xse', 'howxuse', 'hmw2use', 'oow2use', 'horw2use', 'how2ume',
                          'dow2use', 'hom2use', 'thow2use', 'hocw2use', 'how2usej', 'how2usem', 'how2usa', 'how2usje',
                          'how2upse', 'hotw2use', 'howx2use', 'how2useh', 'hyw2use', 'howt2use', 'hoh2use', 'how2usez',
                          'howg2use', 'how2sse', 'how2nse', 'how2usy', 'howv2use', 'hok2use', 'how2uose', 'qhow2use',
                          'how2luse', 'how2fuse', 'hoxw2use', 'howk2use', 'huw2use', 'cow2use', 'how2ule', 'howr2use',
                          'how2uge', 'show2use', 'howpuse', 'hqow2use', 'how2zse', 'how2usex', 'how2usc', 'how2usb',
                          'aow2use', 'hsow2use', 'howeuse', 'how2gse', 'howf2use', 'chow2use', 'how2cse', 'how2ute',
                          'hoi2use', 'how2usu', 'lhow2use', 'howh2use', 'how2usl', 'how2usen', 'how2useu', 'hor2use',
                          'how2useb', 'mhow2use', 'how2muse', 'how2uhe', 'how2upe', 'how2urse', 'honw2use', 'how2usue',
                          'how2bse', 'how2uvse', 'how2ube', 'how2usbe', 'mow2use', 'howj2use', 'howb2use', 'hovw2use',
                          'howhuse', 'hwow2use', 'howluse', 'how2wuse', 'hrow2use', 'hdw2use', 'hdow2use', 'pow2use',
                          'howwuse', 'how2ure', 'how2uspe', 'how2qse', 'how2usk', 'hzow2use', 'hol2use', 'howy2use',
                          'how2usqe', 'how2duse', 'howi2use', 'how2uoe', 'vow2use', 'how2usep', 'how2ause', 'hgw2use',
                          'hofw2use', 'hot2use', 'how2ouse', 'wow2use', 'eow2use', 'hoz2use', 'hob2use', 'howiuse',
                          'howl2use', 'how2ucse', 'howfuse', 'ohow2use', 'how2uie', 'hoj2use', 'how2rse', 'haw2use',
                          'how2quse', 'htw2use', 'how2usv', 'xhow2use', 'how2usey', 'zhow2use', 'how2ruse', 'howruse',
                          'hvow2use', 'howyuse', 'haow2use', 'how2suse', 'howsuse', 'how2usg', 'howvuse', 'homw2use',
                          'hew2use', 'hog2use', 'how2usj', 'how2buse', 'how2tse', 'how2uske', 'howp2use', 'how2usm',
                          'how2euse', 'how2useo', 'how2lse', 'hoo2use', 'hxw2use', 'how2usoe', 'howmuse', 'khow2use',
                          'how2dse', 'how2uset', 'hownuse', 'how2usme', 'howz2use', 'howo2use', 'how2ushe', 'hww2use',
                          'how2uye', 'how2usle', 'how2vuse', 'hobw2use', 'h8w2use', 'h;w2use', 'h*w2use', 'h(w2use',
                          'h)w2use', 'ho12use', 'ho!2use', 'ho@2use', 'ho#2use', 'how1use', 'how!use', 'how@use',
                          'how#use', 'how3use', 'how26se', 'how2^se', 'how2&se', 'how2*se', 'how2us2', 'how2us$',
                          'how2us#', 'how2us@', 'tutorialw', 'tbtorial', 'tutoriala', 'sutorial', 'autorial',
                          'tuzorial', 'tutoriae', 'tutqrial', 'tutorhal', 'tntorial', 'tutorianl', 'tutfrial',
                          'tutoribl', 'tgtorial', 'tutoriax', 'tvutorial', 'tutorival', 'tutoriayl', 'tutoriel',
                          'tutoaial', 'tutorcal', 'mtutorial', 'tutoriaj', 'tutorialg', 'tuttrial', 'tutorialz',
                          'tutobial', 'ztutorial', 'tutorbal', 'tutormial', 'tutomial', 'tutojial', 'tdutorial',
                          'tutoriat', 'tatorial', 'tutorirl', 'tutoriay', 'tutowial', 'jutorial', 'tutoriaf',
                          'tutorifl', 'tutorxal', 'tuatorial', 'tutorinal', 'tutorialr', 'tutorian', 'tuuorial',
                          'tutoriad', 'tutozrial', 'txutorial', 'butorial', 'tutoryial', 'tltorial', 'tutolial',
                          'tutoraial', 'tutoribal', 'tutoriafl', 'tutoryal', 'tutorialc', 'wutorial', 'jtutorial',
                          'teutorial', 'tutbrial', 'tutomrial', 'tutoripl', 'tutorivl', 'tutoyial', 'stutorial',
                          'tutoriaml', 'tutorqial', 'tutmorial', 'tutoriali', 'tutxorial', 'tutornial', 'tutsorial',
                          'tuqorial', 'tuetorial', 'tutorcial', 'putorial', 'tutoriale', 'tutoriagl', 'tuvtorial',
                          'tutoriac', 'tutorpial', 'tmutorial', 'tutovial', 'tutonial', 'tutdrial', 'tutorxial',
                          'qtutorial', 'tutvorial', 'tutorimal', 'tuworial', 'tutcrial', 'tutorialx', 'nutorial',
                          'tutorijl', 'tutoriacl', 'tutorzial', 'tutonrial', 'tutozial', 'tutorigal', 'tutohial',
                          'vutorial', 'txtorial', 'tutorical', 'tstorial', 'tuvorial', 'tuxorial', 'tztorial',
                          'tutgrial', 'eutorial', 'tutorigl', 'tutoxrial', 'tutoridal', 'tzutorial', 'atutorial',
                          'tetorial', 'ctutorial', 'tutorbial', 'tutoriam', 'tutaorial', 'tusorial', 'tutorfal',
                          'tutoriaul', 'tutormal', 'tcutorial', 'tutoriab', 'tudtorial', 'tutoriajl', 'tutsrial',
                          'tutoriaq', 'tuporial', 'tuwtorial', 'tutorialn', 'tutoriail', 'tumtorial', 'lutorial',
                          'tutoarial', 'tustorial', 'mutorial', 'tutoraal', 'tnutorial', 'tutoricl', 'tutnrial',
                          'tuaorial', 'tutoriil', 'tqutorial', 'tujorial', 'tuztorial', 'tutoridl', 'tutoriyl',
                          'tuntorial', 'tutocrial', 'tueorial', 'tutorialj', 'tutoriul', 'tutourial', 'qutorial',
                          'tutosial', 'tuthrial', 'tutoriyal', 'tutoriaz', 'vtutorial', 'tutoriaw', 'tutojrial',
                          'tutqorial', 'tutorpal', 'tutorsal', 'tutorqal', 'tuxtorial', 'tutorialb', 'tutvrial',
                          'tutoiial', 'tutuorial', 'tunorial', 'tutorialy', 'tultorial', 'tuptorial', 'tutorral',
                          'tutocial', 'tutoriael', 'tutoripal', 'trtorial', 'tftorial', 'tsutorial', 'tuturial',
                          'tutjorial', 'tutokial', 'tukorial', 'tutzrial', 'tutorialt', 'tutovrial', 'tutoreal',
                          'tdtorial', 'kutorial', 'tutorwal', 'tutorialm', 'tutorwial', 'tutorifal', 'ltutorial',
                          'tutcorial', 'tutoriavl', 'tutorias', 'tlutorial', 'tutjrial', 'tutoriah', 'tumorial',
                          'tutorialq', 'tutoriahl', 'xtutorial', 'tutorzal', 'tutordal', 'toutorial', 'tutorsial',
                          'tutoriabl', 'tutrrial', 'tutoqial', 'twtorial', 'tubtorial', 'tutorieal', 'tputorial',
                          'tutoriatl', 'btutorial', 'tutoriald', 'iutorial', 'tudorial', 'tutyrial', 'tutorihal',
                          'tutosrial', 'tuiorial', 'tutohrial', 'tutoritl', 'tutborial', 'tutobrial', 'tutorhial',
                          'tttorial', 'tutorgal', 'tutoriadl', 'tucorial', 'tutworial', 'ntutorial', 'tutxrial',
                          'zutorial', 'tutoqrial', 'tutorital', 'totorial', 'ptutorial', 'ututorial', 'tutopial',
                          'tutmrial', 'tuotorial', 'uutorial', 'tutorialh', 'tutorialu', 'tutoriarl', 'twutorial',
                          'dutorial', 'tutoriol', 'tuctorial', 'tqtorial', 'tutorialf', 'itutorial', 'tutoriau',
                          'tutarial', 'tutorialv', 'tutoriaa', 'tutoriai', 'tutorill', 'tptorial', 'wtutorial',
                          'tutorikl', 'tutoriml', 'tutoriar', 'tutorvial', 'tuteorial', 'tuborial', 'tutoriral',
                          'dtutorial', 'tutornal', 'tutortal', 'tutoriav', 'tutowrial', 'tutoyrial', 'tutoxial',
                          'xutorial', 'tutoriag', 'tutorihl', 'cutorial', 'tutorval', 'tvtorial', 'tautorial',
                          'tmtorial', 'outorial', 'etutorial', 'ktutorial', 'tbutorial', 'tutorinl', 'tuterial',
                          'tuqtorial', 'tulorial', 'tctorial', 'tutwrial', 'otutorial', 'tutorials', 'tuoorial',
                          'tutooial', 'tutnorial', 'tutouial', 'tutdorial', 'tutzorial', '4utorial', '$utorial',
                          '%utorial', '^utorial', 't6torial', 't^torial', 't&torial', 't*torial', 'tu4orial',
                          'tu$orial', 'tu%orial', 'tu^orial', 'tut8rial', 'tut;rial', 'tut*rial', 'tut(rial',
                          'tut)rial', 'tuto3ial', 'tuto#ial', 'tuto$ial', 'tuto%ial', 'tutor7al', 'tutor&al',
                          'tutor*al', 'tutor(al', 'tutoria;', 'tutoria/', 'tutoria.', 'tutoria,', 'tutoria?',
                          'tutoria>', 'tutoria<', 'tuit', 'but', 'tu', 'ttu', 'tute', 'taut', 'yut', 'tuto', 'tutg',
                          'tul', 'utt', 'tmt', 'tt', 'tcut', 'tuti', 'put', 'tzt', 'tuxt', 'ut', 'tuq', 'tui', 'tht',
                          'tat', 'lut', 'tgut', 'btut', 'vut', 'tutt', 'tutx', 'tuvt', 'tus', 'tutn', 'tuw', 'tutf',
                          'tout', 'kut', 'tue', 'ztut', 'tbt', 'tuth', 'stut', 'tjt', 'tjut', 'vtut', 'dut', 'tut',
                          'txut', 'tuv', 'tuot', 'tet', 'tujt', 'tmut', 'tyut', 'twt', 'tzut', 'tutv', 'ttut', 'tot',
                          'tuts', 'tud', 'itut', 'tumt', 'tuy', 'ntut', 'tct', 'tuct', 'tult', 'tit', 'tpt', 'tukt',
                          'tuyt', 'iut', 'tupt', 'tuty', 'ttt', 'jut', 'ftut', 'gtut', 'qut', 'uut', 'atut', 'tqt',
                          'ytut', 'thut', 'tub', 'tuqt', 'dtut', 'tuut', 'tst', 'xut', 'tuht', 'wut', 'tug', 'nut',
                          'tux', 'gut', 'otut', 'htut', 'mut', 'tlt', 'tuk', 'zut', 'wtut', 'ltut', 'jtut',
                          'teut', 'tutz', 'tutq', 'tbut', 'tutd', 'tutp', 'tuzt', 'tun', 'tutj', 'ctut', 'rtut', 'trt',
                          'tkut', 'tutw', 'tuz', 'tlut', 'tutl', 'sut', 'tup', 'etut', 'tum', 'rut', 'ptut', 'tfut',
                          'cut', 'tyt', 'tqut', 'tubt', 'tur', 'tutc', 'tuj', 'tsut', 'mtut', 'tutb', 'tkt', 'trut',
                          'tgt', 'tutr', 'tuc', 'tft', 'tvt', 'xtut', 'tuft', 'tutm', 'ktut', 'tvut', 'tuu',
                          'eut', 'tnut', 'tput', 'fut', 'tuwt', 'hut', 'txt', 'tuet', 'tuf', 'tudt', 'tuo', 'tdut',
                          'tuta', 'utut', 'tdt', 'tunt', 'tnt', 'tugt', 'tua', 'tutk', 'turt', 'tutu', 'tuat', 'qtut',
                          'tust', 'tuh', 'twut', 'tiut', '4ut', '5ut', '6ut', '$ut', '%ut', '^ut', 't6t', 't7t', 't8t',
                          't^t', 't&t', 't*t', 'tu4', 'tu5', 'tu6', 'tu$', 'tu%', 'tu^', 'ivstruction', 'ifstruction',
                          'insotruction', 'instructzion', 'inostruction', 'instrquction', 'instrucmtion', 'inseruction',
                          'instructioyn', 'instrfction', 'insbtruction', 'iistruction', 'insaruction', 'instsruction',
                          'instrzuction', 'iestruction', 'instructiog', 'insiruction', 'instructionr', 'wnstruction',
                          'insmruction', 'inqtruction', 'instructiox', 'instrumtion', 'ienstruction', 'instructcon',
                          'instluction', 'pnstruction', 'instructiod', 'insjruction', 'instructions', 'instrxuction',
                          'instruwction', 'insbruction', 'igstruction', 'inntruction', 'instrucxion', 'instructiozn',
                          'isnstruction', 'xnstruction', 'instrqction', 'instructionv', 'instructioc', 'inhtruction',
                          'instrucwtion', 'insxruction', 'zinstruction', 'instructiotn', 'instructionx', 'inlstruction',
                          'instrvction', 'ivnstruction', 'instructioq', 'ninstruction', 'instrsuction', 'enstruction',
                          'instrusction', 'instructioa', 'instzruction', 'instructizon', 'ixnstruction', 'instrucntion',
                          'instructimon', 'incstruction', 'icnstruction', 'inutruction', 'instructionl', 'instoruction',
                          'instkuction', 'instructaion', 'rinstruction', 'hnstruction', 'instiuction', 'iostruction',
                          'intstruction', 'ipnstruction', 'instrubtion', 'instructioy', 'instruczion', 'inmtruction',
                          'instouction', 'instrxction', 'instcuction', 'instrucoion', 'ingstruction', 'iwstruction',
                          'instructioo', 'rnstruction', 'instructionz', 'cinstruction', 'instructionq', 'iqnstruction',
                          'instrujtion', 'instruoction', 'isstruction', 'instructidn', 'instruccion', 'instructxon',
                          'instrucation', 'instructiogn', 'instructsion', 'instrucotion', 'tnstruction', 'instructbion',
                          'fnstruction', 'instrpction', 'instrucnion', 'instructiorn', 'instrucstion', 'instsuction',
                          'instqruction', 'yinstruction', 'instrrction', 'instrucution', 'instruwtion', 'instructifn',
                          'iwnstruction', 'instrupction', 'iystruction', 'ignstruction', 'inpstruction', 'ipstruction',
                          'insitruction', 'instruution', 'insuruction', 'instructijn', 'iastruction', 'instructign',
                          'instructiol', 'instraction', 'instructionk', 'snstruction', 'insoruction', 'instmruction',
                          'instvuction', 'insptruction', 'instrucdion', 'instrbuction', 'instructiwn', 'instructivn',
                          'instrucjtion', 'instrurtion', 'inftruction', 'inrtruction', 'infstruction', 'instrzction',
                          'idstruction', 'inustruction', 'instructionc', 'instructihn', 'insthuction', 'instrucqtion',
                          'instjuction', 'idnstruction', 'instructnion', 'injtruction', 'inctruction', 'instructibn',
                          'instrucbtion', 'instructiony', 'instructiof', 'instpuction', 'instructaon', 'inbtruction',
                          'instwuction', 'cnstruction', 'inqstruction', 'instruciion', 'instructionp', 'insturuction',
                          'instvruction', 'instrucaion', 'instructinn', 'winstruction', 'ainstruction', 'instrgction',
                          'instructwion', 'instiruction', 'instrucmion', 'instructfon', 'insjtruction', 'instrcction',
                          'inssruction', 'instruntion', 'instructeion', 'instructior', 'instrnction', 'instjruction',
                          'instructqon', 'instructiyn', 'instructicon', 'anstruction', 'inktruction', 'instrection',
                          'instruztion', 'instxuction', 'instructihon', 'pinstruction', 'instrdction', 'instrustion',
                          'instruption', 'instructizn', 'instructqion', 'instruation', 'instruition', 'instructifon',
                          'ixstruction', 'instructiqn', 'instrsction', 'instructiton', 'instrucsion', 'insvtruction',
                          'hinstruction', 'inscruction', 'instructios', 'mnstruction', 'instructzon', 'instructimn',
                          'instrauction', 'instlruction', 'insvruction', 'instrultion', 'inspruction', 'instructian',
                          'instruceion', 'instrmuction', 'xinstruction', 'instructirn', 'insktruction', 'instructpion',
                          'instructiong', 'instruckion', 'instructgon', 'instructixn', 'instrwuction', 'instructcion',
                          'instrluction', 'instructnon', 'instquction', 'instructiosn', 'iynstruction', 'instructionu',
                          'inptruction', 'insnruction', 'instructiron', 'instruqtion', 'instructiov', 'instzuction',
                          'instructiok', 'instrtction', 'instructmon', 'instructiont', 'vinstruction', 'instructron',
                          'icstruction', 'irstruction', 'instkruction', 'instructiou', 'inistruction', 'instructbon',
                          'instructisn', 'instructiwon', 'instxruction', 'inslruction', 'instrucbion', 'inltruction',
                          'instrubction', 'einstruction', 'instrucktion', 'instrurction', 'instructiow', 'instructeon',
                          'insltruction', 'instbuction', 'ianstruction', 'instrugtion', 'instrwction', 'instructpon',
                          'instruetion', 'instrouction', 'instrucwion', 'instruytion', 'instrugction', 'instructidon',
                          'instructiona', 'instruhtion', 'instructiyon', 'instyuction', 'instructiono', 'instructioen',
                          'ingtruction', 'minstruction', 'instructioxn', 'instructionf', 'dinstruction', 'instmuction',
                          'instcruction', 'instruection', 'instructson', 'gnstruction', 'instructioi', 'instruzction',
                          'sinstruction', 'iznstruction', 'ikstruction', 'izstruction', 'instructieon', 'instructiun',
                          'instrutction', 'inszruction', 'instrmction', 'qinstruction', 'instruclion', 'instructvion',
                          'insqruction', 'insdruction', 'instruqction', 'instbruction', 'instwruction', 'inotruction',
                          'instauction', 'instructiofn', 'instrlction', 'instructibon', 'vnstruction', 'instruaction',
                          'ynstruction', 'insntruction', 'instrpuction', 'invtruction', 'nnstruction', 'instrucztion',
                          'znstruction', 'inrstruction', 'instruktion', 'instructioni', 'instructiown', 'instructxion',
                          'qnstruction', 'itstruction', 'instroction', 'instructhon', 'tinstruction', 'instuuction',
                          'instrnuction', 'instnruction', 'instructitn', 'instrucjion', 'instructwon', 'instructioe',
                          'instructdon', 'insctruction', 'instructioz', 'instruttion', 'instructvon', 'irnstruction',
                          'instrucption', 'instrvuction', 'ifnstruction', 'insutruction', 'instructigon', 'initruction',
                          'instructinon', 'instrucqion', 'inskruction', 'instrucpion', 'instrcuction', 'instructiond',
                          'instructionw', 'itnstruction', 'instructiodn', 'instruotion', 'instrucetion', 'instructmion',
                          'invstruction', 'finstruction', 'instructien', 'insmtruction', 'insqtruction', 'instructiqon',
                          'instrucltion', 'instructison', 'instnuction', 'instrbction', 'inttruction', 'instructdion',
                          'instrunction', 'instructiovn', 'instaruction', 'iqstruction', 'instrumction', 'inystruction',
                          'instructioun', 'instructixon', 'instructiaon', 'instructicn', 'instrucition', 'bnstruction',
                          'instructioan', 'ilstruction', 'inswruction', 'ginstruction', 'instpruction', 'inkstruction',
                          'instrucvion', 'instructiot', 'instructiop', 'dnstruction', 'instructione', 'instructivon',
                          'binstruction', 'instrucuion', 'instructiocn', 'iustruction', 'inytruction', 'instructton',
                          'instrulction', 'instructyon', 'instructioqn', '7nstruction', '&nstruction', '*nstruction',
                          '(nstruction', 'i,struction', 'i<struction', 'ins4ruction', 'ins$ruction', 'ins%ruction',
                          'ins^ruction', 'inst3uction', 'inst#uction', 'inst$uction', 'inst%uction', 'instr6ction',
                          'instr^ction', 'instr&ction', 'instr*ction', 'instruc4ion', 'instruc$ion', 'instruc%ion',
                          'instruc^ion', 'instruct7on', 'instruct&on', 'instruct*on', 'instruct(on', 'instructi8n',
                          'instructi;n', 'instructi*n', 'instructi(n', 'instructi)n', 'instructio,', 'instructio<',
                          'intst', 'vinst', 'inrt', 'inbt', 'inlt', 'inrst', 'insmt', 'izst', 'xinst', 'inist',
                          'iwst', 'isnst', 'incst', 'icnst', 'inyst', 'binst', 'inslt', 'rinst', 'cinst',
                          'innt', 'iwnst', 'ifst', 'xnst', 'insit', 'inpt', 'inyt', 'inqt', 'instd', 'instk', 'znst',
                          'insz', 'insd', 'ninst', 'gnst', 'insi', 'vnst', 'pnst', 'rnst', 'ipnst', 'ynst', 'ipst',
                          'snst', 'ixst', 'iest', 'inspt', 'inot', 'minst', 'insjt', 'zinst', 'instl', 'inqst', 'inskt',
                          'hnst', 'itnst', 'inut', 'tnst', 'ifnst', 'ikst', 'inht', 'instq', 'irnst', 'insx', 'ignst',
                          'insa', 'irst', 'ianst', 'nnst', 'insb', 'inpst', 'insqt', 'iust', 'wnst', 'instn', 'insct',
                          'iast', 'instx', 'insto', 'ienst', 'yinst', 'inust', 'injt', 'inste', 'anst', 'itst', 'instb',
                          'ingt', 'instp', 'tinst', 'inkt', 'iznst', 'bnst', 'inse', 'instm', 'ixnst', 'insti',
                          'icst', 'insw', 'einst', 'iynst', 'inkst', 'inmt', 'insbt',
                          'ainst', 'finst', 'insq', 'insu', 'insj', 'ingst', 'insm', 'dinst', 'inlst', 'instw', 'instz',
                          'pinst', 'infst', 'ivnst', 'winst', 'insp', 'insnt', 'insts', 'dnst', 'cnst', 'iost', 'ginst',
                          'sinst', 'inost', 'insot', 'insvt', 'enst', 'insta', 'iqst', 'mnst', 'iqnst', 'insl', 'instj',
                          'idnst', 'hinst', 'insn', 'insc', 'instu', 'instc', 'ivst', 'insut', '7nst',
                          '&nst', '*nst', '(nst', 'i,st', 'i<st', 'ins4', 'ins$', 'ins%', 'ins^', 'morephelp',
                          'morehelv', 'morihelp', 'mgorehelp', 'moaehelp', 'morehehp', 'mgrehelp', 'morehelj',
                          'moreielp', 'moreheap', 'morehetp', 'moreherp', 'morehesp', 'momrehelp', 'morehelpj',
                          'morehhlp', 'moreheli', 'pmorehelp', 'mhrehelp', 'moreheup', 'morepelp', 'morefelp',
                          'moreheblp', 'merehelp', 'morehelap', 'gorehelp', 'morehels', 'morecelp', 'morewelp',
                          'corehelp', 'mowehelp', 'murehelp', 'moiehelp', 'rmorehelp', 'morehulp', 'vmorehelp',
                          'mojehelp', 'moreheltp', 'morehelwp', 'morhhelp', 'mcorehelp', 'moreheep', 'molehelp',
                          'morekhelp', 'wmorehelp', 'morehelbp', 'morehqlp', 'morehelpe', 'momehelp', 'mouehelp',
                          'sorehelp', 'torehelp', 'mrrehelp', 'morehecp', 'morehelpw', 'mdrehelp', 'mqorehelp',
                          'morehelm', 'mowrehelp', 'myorehelp', 'dorehelp', 'ymorehelp', 'moreihelp', 'morelhelp',
                          'morzehelp', 'morehedp', 'morehetlp', 'morehylp', 'myrehelp', 'mtorehelp', 'morohelp',
                          'marehelp', 'morqhelp', 'borehelp', 'moyehelp', 'mooehelp', 'fmorehelp', 'morhehelp',
                          'amorehelp', 'morehelpa', 'meorehelp', 'morehelr', 'mmrehelp', 'morehelep', 'moriehelp',
                          'moreqhelp', 'morphelp', 'mobrehelp', 'moreahelp', 'morehelph', 'morehehlp', 'mvorehelp',
                          'morqehelp', 'morehelpm', 'moremhelp', 'morehelrp', 'worehelp', 'morehelgp', 'morehlelp',
                          'moruehelp', 'morehelz', 'lorehelp', 'morehelg', 'cmorehelp', 'qmorehelp', 'morehelpv',
                          'horehelp', 'morehxlp', 'moreheglp', 'morexhelp', 'morehealp', 'mqrehelp', 'morehelcp',
                          'rorehelp', 'morevhelp', 'morehelu', 'movehelp', 'oorehelp', 'morehqelp', 'morehele',
                          'mrorehelp', 'moryhelp', 'morghelp', 'moreheqlp', 'moreheylp', 'morjhelp', 'mdorehelp',
                          'morerelp', 'movrehelp', 'moroehelp', 'moreheln', 'morehzlp', 'msorehelp', 'zorehelp',
                          'morezelp', 'morzhelp', 'morehezlp', 'moarehelp', 'porehelp', 'moretelp', 'morehela',
                          'uorehelp', 'morehelqp', 'monrehelp', 'morehelup', 'mocehelp', 'morehelyp', 'moqrehelp',
                          'morehelpc', 'mohehelp', 'moredelp', 'monehelp', 'morjehelp', 'morehelfp', 'mxrehelp',
                          'morxehelp', 'morehelh', 'morehelpy', 'iorehelp', 'mokehelp', 'morehelpn', 'mwrehelp',
                          'morehmlp', 'mormhelp', 'moxehelp', 'forehelp', 'morehmelp', 'moreselp', 'mornehelp',
                          'mzorehelp', 'morkhelp', 'zmorehelp', 'morlehelp', 'dmorehelp', 'morehtelp', 'yorehelp',
                          'moreheld', 'morehevlp', 'morehplp', 'umorehelp', 'mosehelp', 'moruhelp', 'morehelk',
                          'morvehelp', 'mopehelp', 'morehelx', 'morekelp', 'msrehelp', 'mjrehelp', 'omorehelp',
                          'morehelvp', 'morehclp', 'morehejp', 'morbehelp', 'morehelb', 'morlhelp', 'morehielp',
                          'morehexlp', 'morehefp', 'moreoelp', 'mvrehelp', 'morehemlp', 'mocrehelp', 'morehelpz',
                          'morehelt', 'morehelpu', 'morkehelp', 'morehelpr', 'mborehelp', 'moreheldp', 'morehglp',
                          'xorehelp', 'morehelq', 'moreheqp', 'morbhelp', 'morehezp', 'moreohelp', 'moreheulp',
                          'morehjlp', 'mzrehelp', 'morahelp', 'muorehelp', 'mworehelp', 'morehklp', 'eorehelp',
                          'morthelp', 'morehpelp', 'moreheclp', 'mormehelp', 'morehblp', 'gmorehelp', 'morehely',
                          'morehemp', 'mozehelp', 'moxrehelp', 'morehelxp', 'morehelip', 'morehzelp', 'bmorehelp',
                          'aorehelp', 'emorehelp', 'morehevp', 'hmorehelp', 'xmorehelp', 'morevelp', 'morehebp',
                          'mtrehelp', 'morehcelp', 'morehelhp', 'moreaelp', 'smorehelp', 'mnrehelp', 'morehexp',
                          'mhorehelp', 'morehelsp', 'mornhelp', 'mobehelp', 'moqehelp', 'mozrehelp', 'morvhelp',
                          'vorehelp', 'morehaelp', 'morxhelp', 'moreqelp', 'morehenp', 'mbrehelp', 'morehejlp',
                          'morehelnp', 'morehnlp', 'morehelw', 'mfrehelp', 'moreheilp', 'moreheip', 'morehelf',
                          'mcrehelp', 'morehelc', 'morelelp', 'morexelp', 'moryehelp', 'morehelpb', 'maorehelp',
                          'morethelp', 'moreeelp', 'morehegp', 'morechelp', 'qorehelp', 'morehelpx', 'tmorehelp',
                          'morehelps', 'morehkelp', 'morehoelp', 'morehvelp', 'moreheljp', 'mforehelp', 'morchelp',
                          'morehelpg', 'morehvlp', 'mojrehelp', 'moreholp', 'morehalp', 'mosrehelp', 'morcehelp',
                          'moreheyp', 'morehelpf', 'morehelpi', 'mourehelp', 'morezhelp', 'mxorehelp', 'morehelpd',
                          'lmorehelp', 'morehenlp', 'moraehelp', 'morehilp', 'morehelmp', 'morpehelp', 'morehelpt',
                          'morehelpk', 'morehtlp', 'morehllp', 'imorehelp', 'morehelpq', 'morehewp', 'morehelzp',
                          'moyrehelp', 'mohrehelp', 'morehxelp', 'moremelp', ',orehelp', '<orehelp', 'm8rehelp',
                          'm;rehelp', 'm*rehelp', 'm(rehelp', 'm)rehelp', 'mo3ehelp', 'mo#ehelp', 'mo$ehelp',
                          'mo%ehelp', 'mor2help', 'mor$help', 'mor#help', 'mor@help', 'moreh2lp', 'moreh$lp',
                          'moreh#lp', 'moreh@lp', 'morehe;p', 'morehe/p', 'morehe.p', 'morehe,p', 'morehe?p',
                          'morehe>p', 'morehe<p', 'morehel9', 'morehel-', 'morehel[', 'morehel]', 'morehel;',
                          'morehel(', 'morehel)', 'morehel_', 'morehel=', 'morehel+', 'morehel{', 'morehel}',
                          'morehel:', 'plsthelp', 'prlshelp', 'plshelup', 'plsheilp', 'plshzelp', 'yplshelp',
                          'plsfhelp', 'iplshelp', 'plshefp', 'pulshelp', 'plshelpz', 'plshelip', 'plvhelp', 'pxshelp',
                          'plshelpa', 'plslelp', 'plshxlp', 'plshtelp', 'pclshelp', 'xlshelp', 'plshela', 'plshedp',
                          'pdshelp', 'plphelp', 'plshelpw', 'dlshelp', 'plskelp', 'plshelpv', 'pnshelp', 'plyhelp',
                          'slshelp', 'plshhlp', 'ptshelp', 'plstelp', 'phlshelp', 'plnhelp', 'plshvelp', 'plshelc',
                          'zlshelp', 'plshcelp', 'plsfelp', 'qlshelp', 'plsheqlp', 'plshelpe', 'pglshelp', 'pjlshelp',
                          'wplshelp', 'plshelpg', 'pllhelp', 'plshetlp', 'plshalp', 'plmhelp', 'klshelp', 'plbhelp',
                          'plscelp', 'zplshelp', 'pbshelp', 'plshelcp', 'plsherp', 'plshelb', 'plsheup', 'plshewp',
                          'pzlshelp', 'plsheyp', 'plsrhelp', 'rplshelp', 'plshelj', 'plshnlp', 'plsholp', 'plsqhelp',
                          'nplshelp', 'plsheap', 'plshelyp', 'plshelpc', 'prshelp', 'plsheld', 'plshelpb', 'plsheqp',
                          'plshelf', 'pluhelp', 'plshilp', 'pyshelp', 'plhshelp', 'plshelpf', 'plshelt', 'plshelxp',
                          'plsheip', 'plshylp', 'pqlshelp', 'mlshelp', 'pcshelp', 'jplshelp', 'plchelp', 'pishelp',
                          'plshllp', 'plrhelp', 'plsselp', 'plshelpq', 'plsheep', 'pylshelp', 'plshejlp', 'plshmlp',
                          'pvshelp', 'ilshelp', 'pzshelp', 'plbshelp', 'plsheljp', 'plshelpd', 'plnshelp', 'plyshelp',
                          'jlshelp', 'elshelp', 'plshelpr', 'plshelw', 'plsheglp', 'flshelp', 'plqhelp', 'plshebp',
                          'plsvelp', 'ylshelp', 'aplshelp', 'vlshelp', 'plshelq', 'plfhelp', 'plshevp', 'pmlshelp',
                          'plthelp', 'plspelp', 'plshelvp', 'fplshelp', 'plshexlp', 'plshkelp', 'plshelnp', 'plshqelp',
                          'plshealp', 'plsdelp', 'pljshelp', 'plsheylp', 'pushelp', 'plshelbp', 'plshelv', 'plshejp',
                          'plsheli', 'pelshelp', 'mplshelp', 'plshelps', 'pashelp', 'bplshelp', 'pvlshelp', 'plshglp',
                          'pblshelp', 'plohelp', 'plmshelp', 'plihelp', 'plshlelp', 'psshelp', 'plshemp', 'pljhelp',
                          'plshelhp', 'plseelp', 'pwlshelp', 'plshelk', 'pflshelp', 'plshegp', 'plshevlp', 'plslhelp',
                          'plshplp', 'plsqelp', 'plshelh', 'plshelpu', 'plshclp', 'plsheltp', 'plsohelp', 'plshenp',
                          'plsheulp', 'plshjlp', 'plsheblp', 'plsheclp', 'plshelpj', 'peshelp', 'plshelap', 'plushelp',
                          'plshelpk', 'plvshelp', 'uplshelp', 'plshqlp', 'xplshelp', 'plshely', 'plghelp', 'plshxelp',
                          'clshelp', 'plsvhelp', 'plshezp', 'plcshelp', 'plsrelp', 'plsihelp', 'alshelp', 'plsmhelp',
                          'gplshelp', 'pdlshelp', 'plshemlp', 'plshelg', 'plshoelp', 'dplshelp', 'plshelrp', 'plshelfp',
                          'plshelqp', 'pqshelp', 'plshklp', 'plshelsp', 'plshielp', 'kplshelp', 'plsheldp', 'hlshelp',
                          'plshelpi', 'plrshelp', 'plfshelp', 'pltshelp', 'palshelp', 'plshelph', 'plshzlp', 'plsheln',
                          'pjshelp', 'plshelr', 'plshelx', 'plshelgp', 'hplshelp', 'plshelmp', 'plshelu', 'pgshelp',
                          'plswelp', 'plshele', 'plshelm', 'plshehlp', 'plhhelp', 'plshelpt', 'plishelp', 'phshelp',
                          'plsmelp', 'pslshelp', 'plshenlp', 'plsielp', 'plshaelp', 'plskhelp', 'plshelep', 'plshelzp',
                          'wlshelp', 'plshezlp', 'plkhelp', 'plshehp', 'pnlshelp', 'rlshelp', 'pxlshelp', 'vplshelp',
                          'pfshelp', 'plshecp', 'plshexp', 'plsaelp', 'plshesp', 'plsphelp', 'plsoelp', 'tplshelp',
                          'qplshelp', 'pilshelp', 'blshelp', 'plshelpx', 'plshelpm', 'plshetp', 'plshelwp', 'pwshelp',
                          'plshels', 'glshelp', 'plshulp', 'plszelp', 'plsxelp', 'plshtlp', 'plshelpn', 'plshelz',
                          'nlshelp', 'plshvlp', 'ptlshelp', 'plshmelp', 'plqshelp', 'cplshelp', 'plgshelp', 'eplshelp',
                          'plshblp', 'splshelp', 'plshelpy', 'pmshelp', 'tlshelp', 'ulshelp', 'plschelp', 'plshpelp',
                          '9lshelp', '-lshelp', '[lshelp', ']lshelp', ';lshelp', '(lshelp', ')lshelp', '_lshelp',
                          '=lshelp', '+lshelp', '{lshelp', '}lshelp', ':lshelp', 'p;shelp', 'p/shelp', 'p.shelp',
                          'p,shelp', 'p?shelp', 'p>shelp', 'p<shelp', 'plsh2lp', 'plsh$lp', 'plsh#lp', 'plsh@lp',
                          'plshe;p', 'plshe/p', 'plshe.p', 'plshe,p', 'plshe?p', 'plshe>p', 'plshe<p', 'plshel9',
                          'plshel-', 'plshel[', 'plshel]', 'plshel;', 'plshel(', 'plshel)', 'plshel_', 'plshel=',
                          'plshel+', 'plshel{', 'plshel}', 'plshel:', 'hcow', 'mhow', 'dhow', 'dow', 'ehow', 'fow',
                          'hxw', 'hyw', 'hhw', 'hdow', 'hok', 'eow', 'hohw', 'htw', 'hoy', 'row', 'hew', 'xow', 'hou',
                          'hrw', 'rhow', 'hfow', 'hzw', 'hogw', 'heow', 'huw', 'sow', 'hvow',
                          'hoz', 'hwow', 'hoc', 'hon', 'hjw', 'hofw', 'cow', 'hdw', 'hrow', 'hom', 'hgw', 'hxow',
                          'hww', 'hcw', 'chow', 'hov', 'zhow', 'tow', 'horw', 'hqw', 'whow', 'aow',
                          'ahow', 'show', 'hsw', 'hqow', 'phow', 'qhow', 'hol', 'hovw', 'xhow', 'haow', 'haw', 'hog',
                          'hnw', 'hob', 'hocw', 'hotw', 'hoxw', 'hsow', 'iow', 'hfw', 'ohow', 'hoyw', 'hobw',
                          'hmow', 'fhow', 'homw', 'hox', 'houw', 'hvw', 'hor', 'hzow', 'hbw', 'hmw', 'thow', 'htow',
                          'hozw', 'hof', 'hojw', 'mow', 'ihow', 'hoh', 'hot', 'vhow', 'honw', 'hoi', 'hoj',
                          'hoo', 'vow', 'khow', 'lhow', 'h8w', 'h;w', 'h*w', 'h(w', 'h)w', 'ho1', 'ho!', 'ho@', 'ho#',
                          '/tut', '/morehelp', '/plshelp', '/how'],
                 extras={'emoji': "info", "args": {}, "dev": True,
                         "description_keys": ["how2.meta.description1", "how2.meta.description2",
                                              "how2.meta.description3"],
                         "name_key": "how2.slash.name"},
                 brief="how2.slash.description",
                 description="{0}\n⦾ {1}\n⦾ {2}")
    async def how2(self, ctx):
        """
        This function is the entry point for the how to use command when called traditionally

        Args:
            ctx (discord.ext.commands.Context): The context of the command call
        """
        await self.how_to_command(ctx)

    # @slash_command(name='how2', name_localizations=stw.I18n.construct_slash_dict("how2.slash.name"),
    #                description="View how to use STW Daily",
    #                description_localizations=stw.I18n.construct_slash_dict("how2.slash.description"),
    #                guild_ids=stw.guild_ids)
    # async def slashhow2(self, ctx):
    #     """
    #     This function is the entry point for the how to use command when called via slash command
    #
    #     Args:
    #         ctx: The context of the command
    #     """
    #     await self.how_to_command(ctx)


def setup(client):
    """
    This function is called when the cog is loaded via load_extension

    Args:
        client: The bot client
    """
    client.add_cog(HowTo(client))
